### ISSUE TITLE
Thread issue for capture

### ISSUE THREAD

**Issue by locke-lunarg** [LunarG/gfxreconstruct#1027]
https://github.com/locke-lunarg/gfxreconstruct/tree/thread
I have a branch that added a option `GFXRECON_ENABLE_EXCLUSIVE_LOCK` to set all API call using `AcquireExclusiveApiCallLock` to avoid thread issues.

Now, we have a thread issue for this PR
https://github.com/LunarG/gfxreconstruct/pull/995
This branch added a map to store pairs of handle and wrapper. When the applications run create/destroy multithread, it might conflict when inserting and erasing on the map. You can see a log, like `Create a duplicated Handle:.....`, when this conflict happens. The exclusive API lock could help it.

Also, `AcquireExclusiveApiCallLock` could serialize processes to rule out threading issues to help debug. Should we also add this on d3d12?

Plus, we have a crash issue for Wolf II. `ReadMe` in this shared folder descript the issue.
https://drive.google.com/drive/u/3/folders/1Om2M5YT1R76yxRInB0ThgoZn3bTenTb2
Whatever enabling exclusive lock or not, sometimes, it crashes before it runes `vkCmdBeginRenderPass` without running `vkBeginCommandBuffer`. The chance very is low. Sometimes, it's even 1/40. I'm not sure if it's related to thread. Plus, it doesn't happen if I don't enable GFXR or enable ValidationLayers. It looks like GFXR does something unknown to cause it.

**Comment by bradgrantham-lunarg** [comment]
E.g. in framework/encode/vulkan_handle_wrapper_util.h in `CreateWrappedNonDispatchHandle` there's a check.

**Comment by locke-lunarg** [comment]
Moved the crash issue to LunarG/Projects
https://github.com/LunarG/Projects/issues/619
