### ISSUE TITLE
[replay Android&Vulkan] About NativeWindowDestroyed Message

### ISSUE THREAD

**Issue by chenyangchenyang** [LunarG/gfxreconstruct#1033]
Hi,

**app get a NativeWindowDestroyed log  message during replay gfx after I disable some vkcmd**

![image](https://user-images.githubusercontent.com/28689129/224927616-f9f0a791-4be9-404b-85e3-96b2c25975ae.png)

The reason of disable some vkcmd is that I want to find  root cause of devicelost(vkQueueSubmit) 

I found my app(mobile&vulkan)  trigger a devicelost error of vkQueueSubmit and not validation error

I want to find the root cause of devicelost(vkQueueSubmit)  by  great gfx replay tools

I try to use --sync option while replaying gfx，found a devicelost of  vkQueueWaitIdle(**rename A**) after vkQueueSubmit(**rename B**)

![image](https://user-images.githubusercontent.com/28689129/224932443-f0fc0a24-b5d6-4cd7-aba0-aebee21490dc.png)

I think  **vkQueueSubmit(B)**  is root cause for a devicelost of  **vkQueueWaitIdle(A)**

I try to disable all vkcmd between BeginRenderPass and EndRenderPass  except NextSubpass about  **vkQueueSubmit(B)**

```
bool FileProcessor::ProcessFunctionCall(const format::BlockHeader& block_header, format::ApiCallId call_id)
{
    xxx
    if (success)
    {
        // my code begin
        if (somecondition())
        {
            return sucess;
        }
        // my code end

        for (auto decoder : decoders_)
        {
            if (decoder->SupportsApiCall(call_id))
            {
                DecodeAllocator::Begin();
                decoder->DecodeFunctionCall(call_id, call_info, parameter_buffer_.data(), parameter_buffer_size);
                DecodeAllocator::End();
            }
        }
    }
    xxx
}
```

I upload a part of key gfx becase source gfx is too large(3G)

[part_gfx.txt](https://github.com/LunarG/gfxreconstruct/files/10967422/part_gfx.txt)

I want to disable all vkcmd between 6120615 and 6121868 of "index" exception 6120615(vkCmdBeginRenderPass) , 6121661(vkCmdNextSubpass), and 6121868(vkCmdEndRenderPass)

But，After replay app decode 6120806(vkAllocateDescriptorSets) of "index", app get a NativeWindowDestroyed log  message and exited(no log message about gfxrecon)  

adblogcat:

[adb_log_cat.txt](https://github.com/LunarG/gfxreconstruct/files/10965364/adb_log_cat.txt)

Do you know the root cause of NativeWindowDestroyed?

**Comment by panos-lunarg** [comment]
With a quick glance you logic and changes look correct but a bit confusing.
To rule out anything crazy can you please change it to this:
```
bool FileProcessor::ProcessFunctionCall(const format::BlockHeader& block_header, format::ApiCallId call_id)
{
    xxx
    if (success)
    {
        // my code begin
        if (somecondition())
        {
            return sucess;
        }
        // my code end

        for (auto decoder : decoders_)
        {
            if (decoder->SupportsApiCall(call_id))
            {
                DecodeAllocator::Begin();
                decoder->DecodeFunctionCall(call_id, call_info, parameter_buffer_.data(), parameter_buffer_size);
                DecodeAllocator::End();
            }
        }
    }
    xxx
}
```
I can't see any information on why the application gets terminated. I see in the logcat a lot of
```
5283 W ratelimit: Single process limit 250/s drop xxx lines.
```
Do you know where this is coming from? Is there any chance that you added a lot of printfs in GFXR that is causing logcat to censor them so the reason for terminating is not printed?

> I want to disable all vkcmd between 6120615 and 6121868 of "index" exception 6120615

I think you are not including these commands in `part_gfx.txt`. It starts from `"index":61229With a quick glance you logic and changes look correct but a bit confusing.
To rule out anything crazy can you please change it to this:
```
bool FileProcessor::ProcessFunctionCall(const format::BlockHeader& block_header, format::ApiCallId call_id)
{
    xxx
    if (success)
    {
        // my code begin
        if (somecondition())
        {
            return sucess;
        }
        // my code end

        for (auto decoder : decoders_)
        {
            if (decoder->SupportsApiCall(call_id))
            {
                DecodeAllocator::Begin();
                decoder->DecodeFunctionCall(call_id, call_info, parameter_buffer_.data(), parameter_buffer_size);
                DecodeAllocator::End();
            }
        }
    }
    xxx
}
```
In the logcat I can't see any information on why the application gets terminated. I see a lot of:
```
5283 W ratelimit: Single process limit 250/s drop xxx lines.
```
Do you know where this is coming from? Is there any chance that you added a lot of printfs in GFXR that is causing logcat to censor them so the reason for terminating is not printed?

> I want to disable all vkcmd between 6120615 and 6121868 of "index" exception 6120615
I think you are not including these commands in `part_gfx.txt`. It starts from `"index":6122982`. Can you re-upload it with showing the correct commands?82`. Can you re-upload it with showing the correct commands?

**Comment by chenyangchenyang** [comment]
> With a quick glance you logic and changes look correct but a bit confusing. To rule out anything crazy can you please change it to this:
> 
> ```
> bool FileProcessor::ProcessFunctionCall(const format::BlockHeader& block_header, format::ApiCallId call_id)
> {
>     xxx
>     if (success)
>     {
>         // my code begin
>         if (somecondition())
>         {
>             return sucess;
>         }
>         // my code end
> 
>         for (auto decoder : decoders_)
>         {
>             if (decoder->SupportsApiCall(call_id))
>             {
>                 DecodeAllocator::Begin();
>                 decoder->DecodeFunctionCall(call_id, call_info, parameter_buffer_.data(), parameter_buffer_size);
>                 DecodeAllocator::End();
>             }
>         }
>     }
>     xxx
> }
> ```
> 
> I can't see any information on why the application gets terminated. I see in the logcat a lot of
> 
> ```
> 5283 W ratelimit: Single process limit 250/s drop xxx lines.
> ```
> 
> Do you know where this is coming from? Is there any chance that you added a lot of printfs in GFXR that is causing logcat to censor them so the reason for terminating is not printed?
> 
> > I want to disable all vkcmd between 6120615 and 6121868 of "index" exception 6120615
> 
> I think you are not including these commands in `part_gfx.txt`. It starts from `"index":61229With a quick glance you logic and changes look correct but a bit confusing. To rule out anything crazy can you please change it to this:
> 
> ```
> bool FileProcessor::ProcessFunctionCall(const format::BlockHeader& block_header, format::ApiCallId call_id)
> {
>     xxx
>     if (success)
>     {
>         // my code begin
>         if (somecondition())
>         {
>             return sucess;
>         }
>         // my code end
> 
>         for (auto decoder : decoders_)
>         {
>             if (decoder->SupportsApiCall(call_id))
>             {
>                 DecodeAllocator::Begin();
>                 decoder->DecodeFunctionCall(call_id, call_info, parameter_buffer_.data(), parameter_buffer_size);
>                 DecodeAllocator::End();
>             }
>         }
>     }
>     xxx
> }
> ```
> 
> In the logcat I can't see any information on why the application gets terminated. I see a lot of:
> 
> ```
> 5283 W ratelimit: Single process limit 250/s drop xxx lines.
> ```
> 
> Do you know where this is coming from? Is there any chance that you added a lot of printfs in GFXR that is causing logcat to censor them so the reason for terminating is not printed?
> 
> > I want to disable all vkcmd between 6120615 and 6121868 of "index" exception 6120615
> > I think you are not including these commands in `part_gfx.txt`. It starts from `"index":6122982`. Can you re-upload it with showing the correct commands?82`. Can you re-upload it with showing the correct commands?

Sorry , I have re-uploaded  `part_gfx.txt`

**Comment by chenyangchenyang** [comment]
> With a quick glance you logic and changes look correct but a bit confusing. To rule out anything crazy can you please change it to this:
> 
> ```
> bool FileProcessor::ProcessFunctionCall(const format::BlockHeader& block_header, format::ApiCallId call_id)
> {
>     xxx
>     if (success)
>     {
>         // my code begin
>         if (somecondition())
>         {
>             return sucess;
>         }
>         // my code end
> 
>         for (auto decoder : decoders_)
>         {
>             if (decoder->SupportsApiCall(call_id))
>             {
>                 DecodeAllocator::Begin();
>                 decoder->DecodeFunctionCall(call_id, call_info, parameter_buffer_.data(), parameter_buffer_size);
>                 DecodeAllocator::End();
>             }
>         }
>     }
>     xxx
> }
> ```
> 
> I can't see any information on why the application gets terminated. I see in the logcat a lot of
> 
> ```
> 5283 W ratelimit: Single process limit 250/s drop xxx lines.
> ```
> 
> Do you know where this is coming from? Is there any chance that you added a lot of printfs in GFXR that is causing logcat to censor them so the reason for terminating is not printed?
> 
> > I want to disable all vkcmd between 6120615 and 6121868 of "index" exception 6120615
> 
> I think you are not including these commands in `part_gfx.txt`. It starts from `"index":61229With a quick glance you logic and changes look correct but a bit confusing. To rule out anything crazy can you please change it to this:
> 
> ```
> bool FileProcessor::ProcessFunctionCall(const format::BlockHeader& block_header, format::ApiCallId call_id)
> {
>     xxx
>     if (success)
>     {
>         // my code begin
>         if (somecondition())
>         {
>             return sucess;
>         }
>         // my code end
> 
>         for (auto decoder : decoders_)
>         {
>             if (decoder->SupportsApiCall(call_id))
>             {
>                 DecodeAllocator::Begin();
>                 decoder->DecodeFunctionCall(call_id, call_info, parameter_buffer_.data(), parameter_buffer_size);
>                 DecodeAllocator::End();
>             }
>         }
>     }
>     xxx
> }
> ```
> 
> In the logcat I can't see any information on why the application gets terminated. I see a lot of:
> 
> ```
> 5283 W ratelimit: Single process limit 250/s drop xxx lines.
> ```
> 
> Do you know where this is coming from? Is there any chance that you added a lot of printfs in GFXR that is causing logcat to censor them so the reason for terminating is not printed?
> 
> > I want to disable all vkcmd between 6120615 and 6121868 of "index" exception 6120615
> > I think you are not including these commands in `part_gfx.txt`. It starts from `"index":6122982`. Can you re-upload it with showing the correct commands?82`. Can you re-upload it with showing the correct commands?

> 5283 W ratelimit: Single process limit 250/s drop xxx lines.

Hi, I don't know where is this message

**Comment by chenyangchenyang** [comment]
> Can you try not skipping `vkAllocateDescriptorSets`?

Hi,

When I try(twice) not skipping disable vkAllocateDescriptorSets, App receive aways NativeWindowDestroyed Message
1. afer decode  6120668(vkCmdDrawIndexed), Next vkcmd is 6120669(vkAllocateDescriptorSets), App receiveNativeWindowDestroyed Message
2. after decode 6120746(vkCmdBindIndexBuffer) ,Next vkcmd is  6120747(vkCmdDrawIndexed), App receive NativeWindowDestroyed Message

Attached Debugger(Android Studio) log:

```
$ adb shell cat /data/local/tmp/lldb-server | run-as com.lunarg.gfxreconstruct.replay sh -c 'cat > /data/data/com.lunarg.gfxreconstruct.replay/lldb/bin/lldb-server && chmod 700 /data/data/com.lunarg.gfxreconstruct.replay/lldb/bin/lldb-server'
$ adb shell cat /data/local/tmp/start_lldb_server.sh | run-as com.lunarg.gfxreconstruct.replay sh -c 'cat > /data/data/com.lunarg.gfxreconstruct.replay/lldb/bin/start_lldb_server.sh && chmod 700 /data/data/com.lunarg.gfxreconstruct.replay/lldb/bin/start_lldb_server.sh'
Starting LLDB server: /data/data/com.lunarg.gfxreconstruct.replay/lldb/bin/start_lldb_server.sh /data/data/com.lunarg.gfxreconstruct.replay/lldb unix-abstract /com.lunarg.gfxreconstruct.replay-0 platform-1678844007737.sock "lldb process:gdb-remote packets"
Debugger attached to process 30594
Debugger detached

Process finished with exit code 0
```

adb logcat:
```
2023-03-15 09:37:31.653 30594-30628/com.lunarg.gfxreconstruct.replay W/Adreno-GSL: <gsl_ldd_control:553>: ioctl fd 95 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 71 Protocol error
2023-03-15 09:37:31.653 30594-30628/com.lunarg.gfxreconstruct.replay W/Adreno-GSL: <log_gpu_snapshot:461>: panel.gpuSnapshotPath is not set.not generating user snapshot
2023-03-15 09:37:33.001 30594-30628/com.lunarg.gfxreconstruct.replay W/ratelimit: Single process limit 250/s drop 195 lines.
2023-03-15 09:37:33.463 30594-30628/com.lunarg.gfxreconstruct.replay W/Adreno-GSL: <gsl_ldd_control:553>: ioctl fd 95 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 71 Protocol error
2023-03-15 09:37:33.463 30594-30628/com.lunarg.gfxreconstruct.replay W/Adreno-GSL: <log_gpu_snapshot:461>: panel.gpuSnapshotPath is not set.not generating user snapshot
2023-03-15 09:37:34.015 30594-30594/com.lunarg.gfxreconstruct.replay W/ratelimit: Single process limit 250/s drop 2544 lines.
2023-03-15 09:37:34.015 30594-30594/com.lunarg.gfxreconstruct.replay V/threaded_app: Pause: 0x71002896b0
2023-03-15 09:37:34.015 30594-30628/com.lunarg.gfxreconstruct.replay V/threaded_app: activityState=13
2023-03-15 09:37:34.033 30594-30594/com.lunarg.gfxreconstruct.replay V/threaded_app: WindowFocusChanged: 0x71002896b0 -- 0
2023-03-15 09:37:35.219 30594-30594/com.lunarg.gfxreconstruct.replay V/threaded_app: NativeWindowDestroyed: 0x71002896b0 -- 0x71c02150a0
2023-03-15 09:37:35.219 30594-30628/com.lunarg.gfxreconstruct.replay V/threaded_app: APP_CMD_TERM_WINDOW
2023-03-15 09:37:35.219 30594-30628/com.lunarg.gfxreconstruct.replay V/threaded_app: APP_CMD_TERM_WINDOW
2023-03-15 09:37:35.255 30594-30594/com.lunarg.gfxreconstruct.replay V/threaded_app: Stop: 0x71002896b0
2023-03-15 09:37:35.255 30594-30628/com.lunarg.gfxreconstruct.replay V/threaded_app: activityState=14
2023-03-15 09:37:35.266 30594-30594/com.lunarg.gfxreconstruct.replay V/threaded_app: InputQueueDestroyed: 0x71002896b0 -- 0x712021ab20
2023-03-15 09:37:35.267 30594-30628/com.lunarg.gfxreconstruct.replay V/threaded_app: APP_CMD_INPUT_CHANGED
2023-03-15 09:37:35.267 30594-30594/com.lunarg.gfxreconstruct.replay V/threaded_app: Destroy: 0x71002896b0
2023-03-15 09:37:35.268 30594-30628/com.lunarg.gfxreconstruct.replay V/threaded_app: APP_CMD_DESTROY
2023-03-15 09:37:35.692 30594-30628/com.lunarg.gfxreconstruct.replay V/threaded_app: android_app_destroy!
```

It is look that app request  normally exit(no crash)
Do you know what happens ?

**Comment by panos-lunarg** [comment]
I am afraid I don't know what the problem might be from that information. I would try 2 things
1. Disable some of your `GFXRECON_WRITE_CONSOLE`. From the last logcat you posted I understand that the message `ratelimit: Single process limit 250/s drop 2341 lines.` is because you push too many lines in logcat:
```

**Comment by chenyangchenyang** [comment]
> I am afraid I don't know what the problem might be from that information. I understand that the behavior you are observing is not normal but I cannot see something wrong from gfxr side.
> 
> I can only interpret the abnormal termination as a crash from the driver (but this does not appear in logcat because it is flooded from too many messages) because you skip commands that are necessary for later commands that you do not skip.
> 
> I would try 2 things:
> 
> 1. Remove the `GFXRECON_WRITE_CONSOLE` commands that you added. From the last logcat you posted I understand that the message `ratelimit: Single process limit 250/s drop 2341 lines.` is because you push too many lines to logcat:
> 
> ```
> 03-15 10:45:59.067  6217  6252 V gfxrecon: Tog SkipCMD(SkipRenderPassCommand) : 6120616
> 
> ...
> 
> 03-15 10:45:59.070  6217  6252 V gfxrecon: Tog SkipCMD(SkipRenderPassCommand) : 6120863
> 03-15 10:46:00.671  6217  6217 W ratelimit: Single process limit 250/s drop 2341 lines.
> ```
> 
> There are 248 prints in logcat so I interpret the ratelimit message that logcat is dropping messages that come from gfxrecon process in order to avoid flooding. So if there was a message that would help explain the termination it does not get printed.
> 
> 2. Start removing the commands one by one. So start from running the trace with all commands (so that you get the `VK_DEVICE_LOST` error) and then start removing vulkan function calls one-by-one (I would start by removing only `vkCmd...()` commands i.e. start from `vkCmdDrawIndexed`) until you end up with the `NativeWindowDestroyed`. In other words try to find which commands is causing the `NativeWindowDestroyed` when it gets removed. Do you get the same problem if you remove only that one?

Surprise!

It's successful while I remove all GFXRECON_WRITE_CONSOLE commands that my added

But I am confuse for this result , why?

**Comment by chenyangchenyang** [comment]
> I'm not sure. Perhaps after a certain number of `W ratelimit: Single process limit 250/s drop 2341 lines.` warnings Android kills the process that makes the logcat noise?

Oh......Great!
Thanks
