### ISSUE TITLE
feature request: swapchain interchange

### ISSUE THREAD

**Issue by zmike** [LunarG/gfxreconstruct#1117]
Portability is an issue with gfxreconstruct: if someone captures a trace on Windows, it will use `VK_KHR_win32_surface` for the swapchain and thus be unreplayable on any other OS. The same issue exists for any trace captured on a different OS than the replayer.

It should be possible to capture a trace on one OS and then replay it on a different one.

**Comment by bradgrantham-lunarg** [comment]
`--wsi` option does this.  Try `--wsi auto`.

**Comment by bradgrantham-lunarg** [comment]
This option and a bunch of other useful options are mentioned in , including `--sfa`, `--remove-unsupported`, and `-m` (notably `-m rebind` as a big hammer for memory compatibility issues)

**Comment by ahcox** [comment]
Note, replaying on a different OS often means replaying on a completely independent Vulkan implementation with different features like numbers and configurations of queue families and queues even when the GPU hardware is identical. Nvidia proprietary transfers nicely between Linux and Windows but going between RADV on Linux and closed source vendor implementation on Windows is a larger jump.

**Comment by zmike** [comment]
I'm trying to replay on lavapipe, which should be identical between all OSes except for WSI.

`--wsi auto` doesn't work but `--wsi xcb` and `--wsi xlib` both do. It would be great if gfxreconstruct wasn't so hostile to users for stuff like this. Instead of following through a path that is known to fail, at least print out some helpful error diagnostics (e.g., for this case "Try adding `--wsi xlib`" based on detecting the `DISPLAY` env var) would go a long way towards reducing frustration and improving usability.

**Comment by bradgrantham-lunarg** [comment]
I think the swapchain interchange feature is already supported, as noted in the USAGE documents, so I'd like to close this issue.  @zmike do you want to file an additional enhancement requesting some prints with additional diagnostics?

**Comment by zmike** [comment]
Yeah I can do that.

**Comment by bradgrantham-lunarg** [comment]
Thank you!
