### ISSUE TITLE
[capture] Assertion during loading in Nier Replicant, `shader_wrapper != nullptr`

### ISSUE THREAD

**Issue by kkartaltepe** [LunarG/gfxreconstruct#1120]
**Describe the capture bug:**
Assertion during loading in Nier Replicant

NieR Replicant ver.1.22474487139.exe: /home/kk/.cache/yay/gfxreconstruct-git/src/gfxreconstruct/framework/encode/vulkan_state_tracker_initializers.h:426: void gfxrecon::encode::vulkan_state_tracker::InitializeGroupObjectState(ParentHandle, SecondaryHandle, Wrapper*, const CreateInfo*, gfxrecon::format::ApiCallId, gfxrecon::encode::CreateParameters) [with ParentHandle = VkDevice_T*; SecondaryHandle = VkPipelineCache_T*; Wrapper = gfxrecon::encode::PipelineWrapper; CreateInfo = VkComputePipelineCreateInfo; gfxrecon::encode::CreateParameters = std::shared_ptr<gfxrecon::util::MemoryOutputStream>]: Assertion `shader_wrapper != nullptr' failed.

**Build Environment:**
Built on cfcd69f8

**Capture Settings:**
GFXRECON_LOG_LEVEL=warning
GFXRECON_CAPTURE_FILE=/home/gfxrecon.gfxr
GFXRECON_CAPTURE_TRIGGER=F3
GFXRECON_CAPTURE_TRIGGER_FRAMES=10
VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct

**To Reproduce:**
Start the program.

**Screenshots:**
N/A

**System environment:**
 - A750 GPU.
 - Running on ANV/Mesa from 888bfa7f04 (23.2.0)
 - Linux 6.3.0-1-drm-tip-git-g1b2487d0f244
 - Running on Proton: 1683293476 experimental-8.0-20230505

**Title configuration:**
  - NieR Replicant ver.1.22474487139
  - 1113560
  - Is DXR enabled? Linux.

**Additional information (optional):**
  - is there a SHA for which capture is known to work? It used to crash at the same assert as #936 in 9.15. I don't know of a version that worked.
  - Does capture operate correctly on a different GPU or driver version? I dont have one handy to test.
  - Proton log shows various d3dcompiler trace messages printed on the same line as gfxreconstruct's assert. So presumably shaders are being compiled in parallel with this check if that matters.

**Comment by kkartaltepe** [comment]
It seems related to `VK_EXT_graphics_pipeline_library` support, `ANV_GPL=0` allows the game to start.

**Comment by bradgrantham-lunarg** [comment]
@kkartaltepe we've recently improved support for VK_EXT_graphics_pipeline_library.  Could you give your test case a try again?

**Comment by kkartaltepe** [comment]
on efc2dc83 the assert remains unchanged with GPL enabled in the driver.

**Comment by locke-lunarg** [comment]
@kkartaltepe  Could you please test PR https://github.com/LunarG/gfxreconstruct/pull/1162 with Nier? Thank you. I couldn't test it on my local. I tried running Nier with Proton 8.0 or Proton - Experimental without enabling any vulkan layers, but the game closed in one second.

**Comment by locke-lunarg** [comment]
I just figured out if I opened steam app by vkconfig, Nier could run without problems. I guess the reason was vkconfig overrided vulkan setting.

**Comment by locke-lunarg** [comment]
Nier works well with dxvk on windows with my desktop GTX 2070, but not my laptop GTX 3070. Both driver is Game Ready 536.40.

GFXR should work with PR https://github.com/LunarG/gfxreconstruct/pull/1162.  But the capture crashes randomly.  The reason is thread issues for Create and Destroy. Enabling `GFXRECON_FORCE_COMMAND_SERIALIZATION` could help it. Added a issue here https://github.com/LunarG/gfxreconstruct/issues/1189.

**Comment by kkartaltepe** [comment]
Steam appears to be overriding gfxreconstruct vulkan layers, so im not sure how to test this anymore.

**Comment by locke-lunarg** [comment]
I think we have two ways to test it. One is to run dxvk on windows. But it mightn't be available on some devices. Another is to use vkconfig to open steam app. vkconfig could overwrite vulkan setting. 
 
 https://www.lunarg.com/introducing-the-new-vulkan-configurator-vkconfig/

**Comment by kkartaltepe** [comment]
Sorry I don't have a windows system available to me (not sure if the intel windows driver even supports GPL right now either). Attempting to setup an environment to cross compile vkconfig for windows to run in proton is a bit less than awesome to try and test this too. Sorry.
