### ISSUE TITLE
[gfxrecon-convert] 'vkFlushMappedMemoryRanges' commands seem to be missing from the "jsonl" captures

### ISSUE THREAD

**Issue by SergioAlapontARM** [LunarG/gfxreconstruct#1127]
Hi, I was doing some debugging of an app and noticed that I couldn't see any of the "vkFlushMappedMemoryRanges" commands in the jsonl human-readable version of the capture after converting the "*.gfxr" with "gfxrecon-convert".

- Version: v0.9.19
- Platform: Windows

**Comment by bradgrantham-lunarg** [comment]
Another possibility is to try the `dev` branch to see if this is something that was fixed in our recent merge of contributed `convert` code.

**Comment by SergioAlapontARM** [comment]
Hi, there seemed to be a communication misunderstanding internally with a trace, everything is fine. Thanks for reaching out quickly though :)
