### ISSUE TITLE
[replay] Cannot reproduce  VK_ERROR_VALIDATION_FAILED_EXT. in replay

### ISSUE THREAD

**Issue by jdz1993** [LunarG/gfxreconstruct#1130]
**Describe the replay bug:**
I encounter a crash at startup my application, which is caused by a return value of VK_ERROR_VALIDATION_FAILED_EXT at vkCreateSwapchainKHR. I capture this sequence in the attachment("g2.gfxr.zip") and try to replay it, but find that replay cannot reproduce the error of VK_ERROR_VALIDATION_FAILED_EXT .
![image](https://github.com/LunarG/gfxreconstruct/assets/4002661/d973b4a9-e61b-4aaf-bd73-0365a3bed949)

I build a [validation-layer-master](https://github.com/KhronosGroup/Vulkan-ValidationLayers) and get a VK_SUCCESS from PreCallValidateCreateSwapchainKHR.
And in DispatchCreateSwapchainKHR, I get a VK_ERROR_VALIDATION_FAILED_EXT from layer_data->device_dispatch_table.CreateSwapchainKHR. Which seems to come from vulkan-1.dll and I don't have a clue why this still get validation-ing, and most strange thing is that replay returns VK_SUCCESS instead of VK_ERROR_VALIDATION_FAILED_EXT.
So if anyone can help me figure out why this is happening, thanks a lot.
![image](https://github.com/LunarG/gfxreconstruct/assets/4002661/84fbf2fd-a13f-463c-9c89-7617fe640136)

**Build Environment:**
Please include the SHA and PR or branch name used in capture and also used to build the replayer.
I use the gfxreconstruct in vulkanSDK version (VulkanSDK\1.3.236.0)

The file g2.gfxr I upload here can be replayed as:      python gfxrecon.py replay g2.gfxr

capture and replay is on: 
"deviceName": "NVIDIA GeForce RTX 2080",
"driverVersionText": "511.23.0.0",

[g2.gfxr.zip](https://github.com/LunarG/gfxreconstruct/files/11517008/g2.gfxr.zip)

**Comment by jdz1993** [comment]
> However, you can use the captured swapchain indices using `--use-captured-swapchain-indices`. Give that a try.
> 
> When I replay your capture file on my machine with `--validate --use-captured-swapchain-indices` I see a validation error on `vkCreateSwapchainKHR`:
> 
> ```
> VUID-VkSwapchainCreateInfoKHR-imageExtent-01274(ERROR / SPEC): msgNum: 2094043421 - Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x19df4cb0920, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (2560,30), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (320,240), minImageExtent = (320,240), maxImageExtent = (320,240). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://vulkan.lunarg.com/doc/view/1.3.246.0/windows/1.3-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
> [more imageExtent validation errors...]
> ```
@bradgrantham-lunarg Thanks for the reply, and after I upgrade vulkanSDK from 1.3.236.0(14-Dec-2022) to 1.3.246.1(11-May-2023), I'm able to get this error above. And 1.3.236.0(14-Dec-2022) definitely cannot print any errors like that. I'm going to check my implementation with this error info now.

**One more question**, I have compiled [Vulkan-ValidationLayers](https://github.com/KhronosGroup/Vulkan-ValidationLayers) by source (main) and do a validation-check myself but no error occurs, I wonder which version or which branch of validation-layer code you use, (I cannont find 

>"which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR()"

in my version of validation source code, which makes it hard on debugging. Could you please provide more info on validation-layer source code?

> Looking in the JSON output from your `.gfxr` file, it looks lilke your image extents to the swapchain are a little strange, almost random. Could you take a look at that and make sure the right values are being passed to `imageExtent`?

I am working on a an editor rendering on vulkan, so it consists of several windows, which is corresponding to several swapchains, surfaces, and they will not share same extent, but surely something went wrong and I will review my code now.

Thanks again, this problem really bothered me for a while~

**Comment by bradgrantham-lunarg** [comment]
> after I upgrade vulkanSDK from 1.3.236.0(14-Dec-2022) to 1.3.246.1(11-May-2023), I'm able to get this error above.
Great!

> I check the converted json(attachment g2.jsonl) and cannot find any vkGetPhysicalDeviceSurfaceCapabilitiesKHR that returns like "minImageExtent":{"width":320,"height":240},

I don't see it either or anything like that.  It's a mystery to me.  Is it possible there's another layer in the chain after GFXR which is doing something strange like creating a new device or Swapchain?

> I am working on a an editor rendering on vulkan, so it consists of several windows, which is corresponding to several swapchains, surfaces, and they will not share same extent

Sorry, that does make sense and I think those Swapchain image extents seem fine if that's the case.

> Could you please provide more info on validation-layer source code?

I don't know much about the validation layers, but for any given SDK release, like 1.3.250, there should be a tag that corresponds to that SDK release, like https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/v1.3.250 .

I'll add @ncesario-lunarg and @jeremyg-lunarg in case they have any insights into that `minImageExtent` error.

**Comment by bradgrantham-lunarg** [comment]
Is your issue with `gfxrecon-replay` resolved?

**Comment by jdz1993** [comment]
> Is your issue with `gfxrecon-replay` resolved?

I think issue with `gfxrecon-replay` is resolved. Thanks.
However I still got issue with `validation-layer` ...

>I don't know much about the validation layers, but for any given SDK release, like 1.3.250, there should be a tag that corresponds to that SDK release, like https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/v1.3.250 .
>I'll add @ncesario-lunarg and @jeremyg-lunarg in case they have any insights into that minImageExtent error.

 My validation code is the default main branch. Now that I have upgraded vulkan sdk to 1.3.246, I will switch to https://github.com/KhronosGroup/Vulkan-ValidationLayers/tree/v1.3.246 and see if any more information occurs.

> Is it possible there's another layer in the chain after GFXR which is doing something strange like creating a new device or Swapchain?

I suspect there is some other layer, but I cannot be able to find out where it is. I have tried to rename all of VkLayer_khronos_validation.dll I find on my computer, still happens. Is there a way to get trace of which layer this application is referencing?

**Comment by bradgrantham-lunarg** [comment]
When you run the application, try setting `VK_LOADER_DEBUG=layer` and see if the output helps.  I think this is officially not a GFXR issue anymore, but if you attach the output of `DEBUG=layer` I can see if there's anything obvious.

**Comment by bradgrantham-lunarg** [comment]
@jdz1993 I'll close this issue because you aren't seeing any further issues with GFXReconstruct specifically.  If you find something in the validation layers that seems inconsistent or wrong, please open an issue at https://github.com/KhronosGroup/Vulkan-ValidationLayers.  Thank you!

**Comment by jdz1993** [comment]
@bradgrantham-lunarg Thanks a lot for help, my issue with gfxrecon is indeed solved. Sorry for miss the last message. 
I will check on  https://github.com/KhronosGroup/Vulkan-ValidationLayers.
