### ISSUE TITLE
Windows dialog blocking isn't quite working

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/gfxreconstruct#1171]
We ran into an issue where a Windows CI `gfxrecon-replay` execution provoked a dialog box, which of course impacted all further runs until the issue was caught and the machine manually cleaned up.  This is the dialog box:

![heap](https://github.com/LunarG/gfxreconstruct/assets/45772930/7e6e86f7-bbd4-425b-9cda-3da43736a651)

The run command correctly set the `GFXRECON_NO_DEBUG_POPUP` environment variable, that's supposed to prevent such manifestations:
```
INFO: set GFXRECON_NO_DEBUG_POPUP=1
INFO: cd D:/j/workspace/gfxreconstruct/Debug32\vulkantest-results\vkcube\replay-results
INFO: executing #7: D:\j\workspace\gfxreconstruct\Debug32\gfxreconstruct\dbuild32\tools\replay\Debug\gfxrecon-replay.exe --sfa --no-debug-popup --screenshot-format bmp --screenshots 11,31,51,71,91 D:/j/workspace/gfxreconstruct/Debug32\vulkantest-results\vkcube\local-copy\vkcube_20201109T110737.gfxr
Build timed out (after 60 minutes). Marking the build as failed.
Build was aborted
Archiving artifacts
Finished: FAILURE
```

We need to research, consolidate, and implement comprehensive Windows dialog blocking.

Also pinging @charles-lunarg who has been looking into such things for other reasons.

**Comment by charles-lunarg** [comment]
In my testing, the way to get rid of all popups requires setting *all* of the various CRT error disablement functions, like so:
```c
    // Avoid "Abort, Retry, Ignore" dialog boxes
    _set_error_mode(_OUT_TO_STDERR);
    _set_abort_behavior(0, _WRITE_ABORT_MSG | _CALL_REPORTFAULT);
    SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
    _CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_FILE);
    _CrtSetReportFile(_CRT_ASSERT, _CRTDBG_FILE_STDERR);
    _CrtSetReportMode(_CRT_WARN, _CRTDBG_MODE_FILE);
    _CrtSetReportFile(_CRT_WARN, _CRTDBG_FILE_STDERR);
    _CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_FILE);
    _CrtSetReportFile(_CRT_ERROR, _CRTDBG_FILE_STDERR);
    ```
Especially note how _CrtSetReportMode &  _CrtSetReportFile have to be called thrice for each of the various causes of popus. 

Is there a way to reproduce the crash such that the popup occurs (aka a known bad commit) so it can be verified if adding these other error disablers works?

**Comment by lunarpapillo** [comment]
The chat discussion starts at: https://chat.google.com/room/AAAAGz74TDA/qgnaa-cQjEU

I compared the recommended way to disable dialog boxes documented at: https://docs.google.com/document/d/1W0W4Sm8hLC9Sh9xBwFJthPk7ZZzPxjqU68xDLZ6LyQY/edit#bookmark=id.4yvy0kvdgglg with what GFXR is actually doing.  My notes:
- GFXR does these all in different places, instead of all in one place - probably not an issue
- `gfxrecon-compress`, `gfxrecon-convert`, `gfxrecon-extract`, `gfxrecon-info`, and `gfxrecon-optimize` all call `_set_abort_behavior()` directly.  `gfxrecon-replay` calls `ProcessDisableDebugPopup()` which then calls `_set_abort_behavior()`.  These should probably all behave the same.
- `SetErrorMode()` is not called anywhere directly in GFXR, though it appears to be present in `AgilitySDK/d3d12SDKLayers.dll`, so it might be being called indirectly for DX12 (though I'm not exactly sure what it's doing there)
- `_CrtSetReportMode()` and `_CrtSetReportFile()` seem to be called only from `external/catch2/catch.hpp`

**Comment by bradgrantham-lunarg** [comment]
The known commit that causes a problem for me at the end of replay of a vkcube capture is e21a9abdf3436b863103be6a2b4387ed8095b4e1.

Dialog problem bandaided with https://github.com/LunarG/gfxreconstruct/pull/1174 using @charles-lunarg suggestions.

**Comment by andrew-lunarg** [comment]
> * `gfxrecon-compress`, `gfxrecon-convert`, `gfxrecon-extract`, `gfxrecon-info`, and `gfxrecon-optimize` all call `_set_abort_behavior()` directly.  `gfxrecon-replay` calls `ProcessDisableDebugPopup()` which then calls `_set_abort_behavior()`.  These should probably all behave the same.

This PR makes them all go through `ProcessDisableDebugPopup()` like `gfxrecon-replay` does: 
 https://github.com/LunarG/gfxreconstruct/pull/1178

**Comment by charles-lunarg** [comment]
> This PR makes them all go through `ProcessDisableDebugPopup()` like `gfxrecon-replay` does: #1178

Thats a copy-paste error if I've ever seen one!

**Comment by charles-lunarg** [comment]
With #1178 merged can this issue be closed?

**Comment by andrew-lunarg** [comment]
The original description refers to replay. #1178 doesn't affect replay, but all the other exes we build. #1174 is more likely to have helped replay.

**Comment by bradgrantham-lunarg** [comment]
@lunarpapillo Is it working now?

**Comment by lunarpapillo** [comment]
> Is it working now?

I'm not sure we identified a test for this?

> The known commit that causes a problem for me at the end of replay of a vkcube capture is https://github.com/LunarG/gfxreconstruct/commit/e21a9abdf3436b863103be6a2b4387ed8095b4e1

That's a whitespace-only commit, so unlikely to be the culprit...?

**Comment by bradgrantham-lunarg** [comment]
I tried out my test case back when I committed #1174 and it solved what we think was the issue at the time.  I think I'm going to close this and we can reopen if we experience a new and interesting case of a debug popup.
