### ISSUE TITLE
Add a MetaDataHeader for option GFXRECON_ALLOW_PIPELINE_COMPILE_REQUIRED

### ISSUE THREAD

**Issue by locke-lunarg** [LunarG/gfxreconstruct#1197]
`GFXRECON_ALLOW_PIPELINE_COMPILE_REQUIRED` will ignore writting Create*Pipeline to file when it's with `VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT`. But we want to leave a record in the file to convert it into .json file or print it during replay, like "application requested creategraphicspipelines but that wasn't passed on to Vulkan implementation".

**Comment by bradgrantham-lunarg** [comment]
From #1160
