### ISSUE TITLE
Is it possible to extract the resources used by the vertex and the fragement shader from the gfxr file 

### ISSUE THREAD

**Issue by aabhinavg** [LunarG/gfxreconstruct#1223]
I have a gfxr capture for a game. I am able to get the shader using gfxrecon-extract but I also want to get the resources used by the shader.
Is their anyway to get it?

**Comment by panos-lunarg** [comment]
Game assets are most likely protected by an IP license. Extracting and/or copying those assets is violating that license and is therefore illegal. gfxreconstruct should **not** be used for that purpose.
