### ISSUE TITLE
Documentation: Clarify what a trimmed capture is and how to create one

### ISSUE THREAD

**Issue by panos-lunarg** [LunarG/gfxreconstruct#1229]
It seems that people, both internal and external, after reading the documentation are left with the question what a trimmed capture is and how one can be created.

We should address this by adding something in the usage .md files. The new documentation should include at minimum:
- What is a trimmed capture
- How can one be created
- How an existing capture can be trimmed

**Comment by bradgrantham-lunarg** [comment]
Does #1230 fix this?

**Comment by panos-lunarg** [comment]
Yes. Closing
