### ISSUE TITLE
GFXRecon-Info Should Take One Pass Over File, Not 3 and Growing

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#1256]
Info currently takes up to three passes over the file to generate stats.
Our current capture files are all single-API other than the D3D12+AGS combo\*, limiting that to two passes, but we foresee use-cases for mixed API capture files.
This code from Info's main shows the structure.
```cpp
        if (gfxrecon::decode::DetectAPIs(input_filename, detected_d3d12, detected_vulkan)) // One pass over file. Partial but being partial makes it a heuristic.
        {
            if (detected_d3d12)
            {
                GatherD3D12Stats(input_filename); // Second pass over file.
            }
            if (detected_vulkan)
            {
                GatherVulkanStats(input_filename); // Third pass over file.
            }
            // Nth pass for API-N ???
        }
```
If we keep adding new APIs, following this structure will mean adding passes over the capture file.
If we do introduce more mixed-API captures, following this structure will mean extending the detection pass over the entire capture file, rather than terminating it early as now, since a new API could appear at any point.

# The Alternative

Instead of this we should do one pass over the file with all the stats consumers engaged.
* The stats consumers can each record the presence of their respective API as a side effect of their operation. No separate DetectionConsumers need be used.
* Annotations can be recorded outside of all consumers during this single pass by a single object shared by all API consumers:
  `class AnnotationRecorder : public gfxrecon::decode::AnnotationHandler {...}`

After the file is processed
* API-agnostic printing code can dump the same stats as would currently be duplicated for Vulkan and D3D12 mixed capture, but only dump them once. 
* API-specific printing code can dump the same stats as now.
* API-specific printing code can pull out annotations of interest to dump or we can have a shared api-agnostic section for annotations too.

## Benefits
* Makes Info streaming-capable again.
* Reduces IO required, and thus performance when IO is bottleneck (slow drives and network drives over narrow wires).
* Naturally separates API agnostic info from API-specific in future multi-API capture files.

# See also
* https://github.com/LunarG/gfxreconstruct/issues/1025
* Running Info already isn't cheap, justifying another look at it: https://github.com/LunarG/gfxreconstruct/issues/725

# Footnotes
\* Which we treat as a D3D12 capture.

**Comment by per-mathisen-arm** [comment]
I think the only model that actually makes sense in the long run is to trace to multiple output files and stitch them back together in post-processing. The tracing tool can attempt to do this for you automatically, and this should usually work and then the user will only see one nice, neat trace file - and when it fails you have a tool to stitch them up by hand. Otherwise you end up with impossible to satisfy requirements, like we're seeing in the above threads, and this will only get worse when we start looking at multi-threading where ideally you'd want to stream each thread to its own file to avoid enforced serialization of calls. There is also the problem that we cannot assume that tracing will always terminate nicely and a "kill -9" type ending should be assumed possible and be recoverable.

**Comment by andrew-lunarg** [comment]
> I think the only model that actually makes sense in the long run is to trace to multiple output files and stitch them back together in post-processing. ...

Definitely a reasonable position and it is also definitely always preferable to segregate the memory accesses and io of different threads, so separate arenas for alloc/dealloc, minimal global variables, and different files to write to (or different memory buffers asynchronously drained into a single file by a dedicated io thread). However, I am not seeing the connection to this issue, since the stitched-together file you posit would be file that would be input to Info in its normal usage that this issue relates to.

I want to emphasise that this issue suggests a trivial reorganisation of the existing code in the Info app, not any deep changes to the underlying framework of the project.

**Comment by rurra-amd** [comment]
The biggest thing that comes to mind with a `gfxrecon-info` refactor is regarding the data it already displays. The underlying code can be improved but I'd like to preserve what it currently displays. Lots of automated systems use this information, and if we change it, things will break. Requirements from my end:

1. Should not remove existing data
2. Should not modify strings that act as "keys" to existing data. For example, the `"Total frames"` string should remain as `"Total frames"`

**Comment by davidd-lunarg** [comment]
PR #1509 modified `gfxrecon-info` to use only a single pass over the capture file. Closing issue as complete.
