### ISSUE TITLE
Issue when copying pNext chains in VulkanStateTracker

### ISSUE THREAD

**Issue by marius-pelegrin-arm** [LunarG/gfxreconstruct#1269]
## Issue

The issue happens when you trim a capture that contains certain kind of Vulkan calls and then try to replay the trimmed capture.

### Description

When saving a `pNext` structure in a wrapper in the `VulkanStateTracker`, the copy of the structure does not copy resources accessed through a pointer.

For example, in `VulkanStateTracker::TrackImageMemoryBinding`, if a `VkBindImageMemoryDeviceGroupInfo` structure exists in the `pNext` chain of `bind_info_pnext`, the pointer `VkBindImageMemoryDeviceGroupInfo::pDeviceIndices` will be copied as-is in `wrapper->bind_pnext`.

If the underlying resource is freed by the application before the call to `VulkanStateWrite::WriteState`, this results in undefined behavior, ranging from data corruption to crash when replaying the capture.

### Reproducing this issue

Take an application that regularly calls a vulkan command that takes a `pNext` chain structure as an argument and where you can easily insert a structure containing a pointer (other than `pNext`) owned by the application in the `pNext` chain. For example, take an application that calls `vkBindImageMemory2` at each frame with a `VkBindImageMemoryDeviceGroupInfo` containing a device index in the `pNext` chain of `pBindInfos`.

Capture this application using GFXRECON_CAPTURE_FRAMES starting after a big number of calls (let's say frame 100).

Replay the capture obtained. You will most probably obtain a crash.

**Comment by charles-lunarg** [comment]
Closing as #1363 is now merged
