### ISSUE TITLE
"api_version" in the VkLayer_gfxreconstruct.json file doesn't have a value 

### ISSUE THREAD

**Issue by johnzupin** [LunarG/gfxreconstruct#1298]
The "api_version" field doesn't have  a value in the  `VkLayer_gfxreconstruct.json` file.

Stopped working after https://github.com/LunarG/gfxreconstruct/commit/f3de76c2808ddf296e1dc947c1837423ad8582c3

**Comment by bradgrantham-lunarg** [comment]
VULKAN_HEADERS_VERSION is empty.

I've temporarily forced the JSON version to 1.3.266 in layer/CMakeLists.txt in https://github.com/LunarG/gfxreconstruct/commit/bdc643cb4581437ad436297d22210b1a4497aecc

I have no idea where VULKAN_HEADERS_VERSION, added to layer/CMakeLists.txt f3de76c, is supposed to be set - I can't find it in the vulkan headers nor in our code.  It *was* being set in our cmake/FindVulkanVersion.cmake but now it isn't.

**Comment by charles-lunarg** [comment]
VULKAN_HEADERS_VERSION Should be from vulkan-headers.

**Comment by charles-lunarg** [comment]
But maybe that is not the right name for the variable in vulkan-headers’ cmakelists.txt

**Comment by charles-lunarg** [comment]
With #1299 and the revert of the original PR, I am going to close this as it is no longer an issue.
