### ISSUE TITLE
Resubmit #1272 resolving the layer JSON Vulkan version substitution

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#1300]
See #1298 

Some notes while I tried to fix this issue:
* I have no idea where `VULKAN_HEADERS_VERSION`, added in f3de76c, is supposed to be set - I can't find it in the vulkan headers nor in our code.
* There's a `VK_VERSION_STRING`, but...
* `set ... PARENT_SCOPE` in a CMakeLists.txt function only sets the variable in the scope of the caller of the function.  Not globally, so `VK_VERSION_STRING` is only available in the parent (Vulkan-Headers/CMakeLists.txt file scope) and not to the parent (gfxreconstruct/CMakeLists.txt)

**Comment by juan-lunarg** [comment]
> set ... PARENT_SCOPE in a CMakeLists.txt function only sets the variable in the scope of the caller of the function. Not globally, so VK_VERSION_STRING is only available in the parent (Vulkan-Headers/CMakeLists.txt file scope) and not to the parent (gfxreconstruct/CMakeLists.txt)

I believe that may be the crux of the issue. This variable you need simply isn't in scope for your project.

> I have no idea where VULKAN_HEADERS_VERSION, added in https://github.com/LunarG/gfxreconstruct/commit/f3de76c2808ddf296e1dc947c1837423ad8582c3, is supposed to be set - I can't find it in the vulkan headers nor in our code.

VULKAN_HEADERS_VERSION is defined by the project call in Vulkan-Headers. It's a variable created by the `project` command.
https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_VERSION.html

```
project(VULKAN_HEADERS LANGUAGES C VERSION ${VK_VERSION_STRING})
```

**Comment by charles-lunarg** [comment]
There is no reasonable path forward for the original PR to happen due to using add_subdirectory instead of find_package. Thus, I am going to close the issue since any potential solution is going to involve a much bigger change in the future to accommodate the one requested here.
