### ISSUE TITLE
enable ZSTD compression for Android

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#1313]
Scanning the Android build files and prebuilt libraries and then git log, I'm not sure I believe ZSTD was ever enabled for Android.  It was added to the USAGE file in a62fe2a3d, but I can't find any trace of ZSTD for Android at that commit or in current `dev`.

I think the tasks are to compile ZSTD for Android somehow, put the binaries in ./external/precompiled/android/lib/*/, check the header into ./external/precompiled/android/include, add ZSTD to android/framework/util/CMakeLists.txt, and then verify build output from our local build process, our internal CI builds, and then our per-commit CI builds on GitHub Actions.

**Comment by panos-lunarg** [comment]
Addressed by #1334
