### ISSUE TITLE
How to cut the gxfr when I have captured a frame

### ISSUE THREAD

**Issue by gmnail** [LunarG/gfxreconstruct#1333]
I want this effect that I know a bug in this frame such as a hang problem, but I do not know which draw causing  it. So, I must cut the frame to reduce number of draws in the frame, and replay the new gfxr file, but I do not know how to do this way.
Only I can get is a json file, and modify it, but how can I replay the json??

**Comment by panos-lunarg** [comment]
Trimming down to draw call granularity is not supported (yet) by GFXR. Also replaying the json file is not supported (yet) either.

You can trim down to queue submission level though using the `GFXRECON_CAPTURE_QUEUE_SUBMITS` option. Have you tried that?
Also when replaying you can use the `--sync` option, which will insert a `QueueWaitIdle` after every queue submission, effectively serializing queue submissions.
If there's only one queue submission in that frame then I don't think there's something out of the box that you can use.

**Comment by gmnail** [comment]
okay, there’s a long way to go...

**Comment by andrew-lunarg** [comment]
Thanks for your use of the project and bringing a reasonable use case to our attention. This is not quite an actual issue as phrased: it is more like a question asking for support. Perhaps the title and description can be rephrased into a specific issue that captures a task that we would want to pursue or you might want to contribute and then this could be reopened.

**Comment by gmnail** [comment]
OK, thank you for your answer, looking forward to your new features.
