### ISSUE TITLE
Update Vulkan Headers to v1.3.272

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#1361]
We are a few releases behind. Latest: https://github.com/KhronosGroup/Vulkan-Headers/releases/tag/v1.3.272

I did a dry run on 269\* and that needed some more investigation so 272 will need that work and maybe more.

\* https://github.com/andrew-lunarg/gfxreconstruct/tree/andy-headers_update-v1.3.269

**Comment by bradgrantham-lunarg** [comment]
fixed by #1392
