### ISSUE TITLE
[replay] Regarding screenshots of draw call units

### ISSUE THREAD

**Issue by Augustin0821** [LunarG/gfxreconstruct#1366]
Currently, the latest version of gfxrconstruct only supports screenshots in units of frames, and I was wondering if you have any plans to apply that feature to the new version or how to extract the screenshots in units of draw call.

**Comment by bradgrantham-lunarg** [comment]
Thanks for your question!

Screenshots at a higher frequency than frames is in development but we don't have a schedule to share at this time.  As far as "the new version", could you explain that in more detail?  We aren't engaged in any effort to create a new version that would exclude any current features.

If you'd like to discuss with us in more detail, please contact info@lunarg.com!
