### ISSUE TITLE
Support CmdPushDescriptorSetWithTemplate2KHR 

### ISSUE THREAD

**Issue by locke-lunarg** [LunarG/gfxreconstruct#1400]
After update to headers 1.3.275, it has a new function, CmdPushDescriptorSetWithTemplate2KHR , that need to support as CmdPushDescriptorSetWithTemplateKHR.

**Comment by bradgrantham-lunarg** [comment]
Additional guidance from @locke-lunarg : 
> CmdPushDescriptorSetWithTemplateKHR is already supported. The unsupported one is  CmdPushDescriptorSetWithTemplate2KHR. I mean that it needs to do something for CmdPushDescriptorSetWithTemplate2KHR as  CmdPushDescriptorSetWithTemplateKHR.
> If you search CmdPushDescriptorSetWithTemplateKHR, you could find many manual code for it. But all code of CmdPushDescriptorSetWithTemplate2KHR are generated.

So I was wrong in what I said - right now vkCmdPushDescriptorSetWithTemplateKHR  is implemented by hand in framework/encode/custom_vulkan_api_call_encoders.cpp; it's listed in framework/generated/vulkan_generators/blacklists.json.  But vkCmdPushDescriptorSetWithTemplate2KHR is still auto-generated and needs to be not generated, adapted from the the code for vkCmdPushDescriptorSetWithTemplateKHR.

**Comment by bradgrantham-lunarg** [comment]
Specifically this issue should be about supporting vkCmdPushDescriptorSetWithTemplate2KHR as much as vkCmdPushDescriptorSetWithTemplateKHR is also supported.  Submit a PR just to bring these to parity.

Note that neither one appears to currently work in trimming, so make a new issue regarding both functions for trimmed capture.
