### ISSUE TITLE
[trim] vkUpdateDescriptorSetTemplate path needs refinement

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/gfxreconstruct#1419]
From issue #1375, a change was added to properly track and record the accelerator data if used in a call to `vkUpdateDescriptorSetTemplate`.  This is done for now by writing out pNext data of an accelerator structure which matches the way the other descriptor set data is currently saved for this entrypoint.

This entrypoint should properly record the tracking data without the pNext data hack to more closely reproduce the original intent of the capture.

You can reproduce this on **Linux** (although it happens on other platforms) using [my fork of Sascha Willem's Vulkan examples](https://github.com/MarkY-LunarG/Vulkan). using the branch `marky_move_raytrace_reflect_to_desc_templates`.  Building this will produce a `raytracingreflectionsdesctemplates` sample which can be recorded and trimmed and then replayed.  Without the fix in #1375 it crashes, so when updating the source to properly fix this issue, run that sample and make sure a trimmed capture does not crash.

**Comment by bradgrantham-lunarg** [comment]
@fabian-lunarg want to take a crack at this?  I think it will mean reading through the existing code for tracking and descriptor set templates.  Please talk with @MarkY-LunarG if there is context you think you need that is missing.

**Comment by fabian-lunarg** [comment]
sounds good, will do :)
