### ISSUE TITLE
Support for multithreaded replays

### ISSUE THREAD

**Issue by jacobv-nvidia** [LunarG/gfxreconstruct#1450]
From my casual understanding of the replayer, as it stands now, it seems like it doesn't really do anything to try and match any of the multithreaded characteristics of the captured application. Is this accurate?

Considering the possible use cases of comparing performance of captures vs. native programs, it seems like such a feature would be necessary, but I haven't found much mention of it aside from [this comment in #1066](https://github.com/LunarG/gfxreconstruct/issues/1066#issuecomment-1485285377).

So I'm wondering, is multi-threaded replay on the roadmap for the project, or is it seen as more of a no/low priority?

**Comment by bradgrantham-lunarg** [comment]
@jacobv-nvidia It is on the roadmap and is seen as a high priority.  See also #190 and #1142 .  However our assessment so far has been that it would not only require creating multiple threads and synchronizing between them to replicate the application synchronization behavior but possibly also a file format change to record start and stop of functions.  Thus this is a potentially large change we have deferred.

**Comment by bradgrantham-lunarg** [comment]
dup of #1142
