### ISSUE TITLE
VulkanVirtualSwapchain to passthrough the swapchain under certain conditions

### ISSUE THREAD

**Issue by yaman-lunarg** [LunarG/gfxreconstruct#1454]
From @bradgrantham-lunarg 
We have the class `VulkanVirtualSwapchain` which makes images to stand in for the images from the Swapchain.  This isn't necessary if the number of swapchain images in replay is the same as in capture and also if the present mode is FIFO.  It would be helpful if `VulkanVirtualSwapchain` could detect that circumstance and then just passthrough the swapchain functions for that particular `VkSwapchain`.

**Comment by bradgrantham-lunarg** [comment]
The spec seems to say that FIFO means the order of presentation of images to the display is equivalent to the order of images QueuePresent'd, but that the Acquire image _ordering_ is not guaranteed.  We didn't seem to have a problem previously capturing and replaying FIFO with the same number of replay images as capture images so it seemed reasonable to assume that the Acquire image queue and the presentation image queue were essentially equivalent.  (We had issues with other present modes and when #images was different in replay from capture, but not when #images was the same and FIFO mode.)  Our experience had been that the ordering is maintained but that could have been dependent on the implementation.  Additional feedback on private channels indicates that this feature would fail on some implementations.

So don't implement this feature as the spec does not seem to guarantee that it will work.
