### ISSUE TITLE
Discard alpha in screenshot

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#1455]
One motivation for dumping alpha was that it provided more information to a developer who was using alpha (if the alpha values made it into the attachment).  However, RGB-only is most useful / least surprising because several developers have fought with screenshots that don't display as expected or compare correctly only because of the alpha channel. Maybe there are contexts like VR or a composited desktop where the alpha is useful, but those are probably much less common than our standard single-application desktop/mobile capture/replay workflow.

We are likely to merge the ability to dump intermediate buffers after Draw/Dispatch/TraceRays shortly.  A developer can use that to dump the actual attachments and therefore get alpha before QueuePresent and at more appropriate times for their pipeline.

For this task, remove alpha from the screenshot dumps for BMP and PNG, both Vulkan and DX12.

**Comment by yaman-lunarg** [comment]
The preferred way of performing `VK_FORMAT_*` conversions, such as `VK_FORMAT_B8G8R8A8_SRGB` to `VK_FORMAT_B8G8R8_UNORM`, is to use of the `vkCmdBlitImage()`; i.e. handle the conversion on the GPU.
However support for _3-channel images_ is not widely available; for example `VK_FORMAT_B8G8R8_UNORM` is not supported on RTX 3070Ti for both  `VK_IMAGE_TILING_OPTIMAL` and `VK_IMAGE_TILING_LINEAR`. One can appreciate the challenges this poses given the diversity of equipment LunarG is to support.
Removing alpha channel on the CPU involves separate memory copies for each pixel as well as an auxiliary piece of memory as the destination of those copies. Would blindly setting alpha value to full opacity for each pixel achieve the desired end result?
