### ISSUE TITLE
DX12 replay run Vulkan object.

### ISSUE THREAD

**Issue by locke-lunarg** [LunarG/gfxreconstruct#1465]
TestCode: https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12ExecuteIndirect

DX12 replay gets a warning `[gfxrecon] WARNING - Rendering was restricted to surface index 0, but a surface was never created for that index; replay created 0 surface(s)`. The warning is from `VulkanSwapchain::Clean()`. I feel DX12 replay shouldn't run Vulkan object.

**Comment by bradgrantham-lunarg** [comment]
Duplicate of #1402 ?

**Comment by locke-lunarg** [comment]
Yes. They are the same. Closed it.
