### ISSUE TITLE
Ensure GFXR builds for macOS x86_64

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#1516]

**Comment by fabian-lunarg** [comment]
I'm currently looking into that with an old intel-based macbook-pro mid2014, maxed out at macOS 11 (Big Sur)

those links make me think this might not be enough, so I'll need to rely on github's runners.

- https://en.wikipedia.org/wiki/MacBook_Pro_(Intel-based)#Software_and_operating_systems
- https://github.com/actions/runner-images/issues/9255

regarding the setup this is related to:
https://github.com/LunarG/gfxreconstruct/issues/1520 
so makes sense to do both

**Comment by fabian-lunarg** [comment]
so above means gfxreconstruct certainly builds **for** macOS x86_64.
I also checked if it compiles **on** macOS x86_64 and successfully built `libVkLayer_gfxreconstruct.dylib` on
macOS 11 with an old intel-based macbook.
compiling the tools, that require a window, failed though and required as minimum version macOS 12.

I don't think this is an issue, it's just a very old machine + OS-version and the project built fine on github's x86_64 runner.
let's close this after testing again for x86_64 with https://github.com/LunarG/gfxreconstruct/issues/1520 merged. 
fyi @bradgrantham-lunarg

**Comment by fabian-lunarg** [comment]
confirmed our builds work for x86_64.

when building from source we need to explicitely request that:
`cmake .. -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"`

yielding a universal library / tools.
