### ISSUE TITLE
Sign resulting DSOs so they can be loaded into signed apps like vkcube shipped with SDK

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#1517]

**Comment by fabian-lunarg** [comment]
we have an internal (temporary) solution to do this, which we can further improve. 
right now we're able to (manually) sign our macOS `libVkLayer_gfxreconstruct.dylib` using the same certificate
used to sign the SDK-apps.
using this signed layer-DSO I was successful capturing `vulkaninfo` and `vkcube` from our macOS SDK.

the question is whether to leave this issue open until we streamline this process further, integrate with CI, ...
what do you think @bradgrantham-lunarg ?

**Comment by bradgrantham-lunarg** [comment]
I think we will need to provide a script (as we've discussed) so that individual developers can sign the layer for their build.

I'm unsure exactly what we'll need to do for GitHub Release Packaging since we don't want to check in the certificate.  We probably should go with unsigned artifacts for now, and then either tell users to unpack and sign themselves or we have a manual step as part of GitHub Release Packaging.  We already have a need for setting executable bits in the Linux release tar, so maybe we can partially automate that with a post-release-build script that interacts with GitHub Releases through Github's web API.

**Comment by bradgrantham-lunarg** [comment]
I think to close out this task, commit your signing script codesign_macOS.sh except do the signing locally, then briefly document the reason for the script and how to use it in BUILD.md and mention briefly in USAGE_desktop_Vulkan.md that if people see a signing error they will need to sign their DSO.

**Comment by bradgrantham-lunarg** [comment]
Script is probably not useful - instead, put the few relevant lines in BUILD
