### ISSUE TITLE
[capture] Why capture failed with hwui=skiavk?

### ISSUE THREAD

**Issue by Zydiii** [LunarG/gfxreconstruct#1522]
Hi, I'd like to capture some apps like gallary or chrome when they are using skiavk for hwui. But the capture would fail under these apps.

Could you please tell me why this conflict would happen and how to fix it? Or is there any way else that could capture skiavk?

Thanks!

**Comment by bradgrantham-lunarg** [comment]
Can you give us more information about what is happening?

**Comment by Zydiii** [comment]
Thanks for your replay. What I have done are something like the followings, capture & replay gallery‘s system UI for example:

```
adb shell "setprop debug.vulkan.layers 'VK_LAYER_LUNARG_gfxreconstruct'"
adb shell "setprop debug.hwui.renderer 'skiavk'"
adb shell "setprop debug.gfxrecon.capture_file /storage/emulated/0/Download/gallary.gfxr"
```

After I got the capture file, I tried to replay it using gfxrecon.py:

```
PY -3 .\android\scripts\gfxrecon.py replay /sdcard/Download/gallary_20240620T012525.gfxr
```

But the replay shows nothing and quits soon. 

Is there anything missing when capturing data related with system ui, or replaying .gfxr to create system ui is not allowed?

**Comment by bradgrantham-lunarg** [comment]
It may be helpful to look at your content in JSON form for the rest of my message.  You can do that by running `gfxrecon-convert` on your .GFXR file, which will create a `.json` file with the same name.  You can open that in an editor or use `less` on Unix-like systems.

For content that is created for HWUI/SkiaVk, you'll probably see a call to `vkAllocateMemory` that has `VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO` and `VK_STRUCTURE_TYPE_IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID` structures in the pNext chain that imports an Android buffer as the backing for a VkImage.  Then, later, you'll probably see a call to `vkFrameBoundaryANDROID` that uses the same image handleId from that `vkAllocateMemory` call.  If that's the case, there is no drawn `VkSurface` and at the moment we don't support replay of those Images.  However, with a very recent version of `dev` branch, you can replay with `--screenshot-all` to write the screenshots for those images.  Give that a try.

In the JSON you may also see calls to `vkCreateAndroidSurfaceKHR`.  At the moment, our Android replayer has a limitation that it can only play the content for one `Surface`.  You may count up the number of surfaces created, and then please try `--surface-index` command-line parameter to the Android `gfxrecon.py` with one of those indices.  For example, if 2 surfaces are created, try indices 0 or 1, like this: `scripts/gfxrecon.py replay --surface-index 1 your-capture.gfxr`.

**Comment by Zydiii** [comment]
Thanks for your detailed explanations. The problem is exactly the case you mentioned that `vkAllocateMemory` has `VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO` and `VK_STRUCTURE_TYPE_IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID`, and the images are used in `vkFrameBoundaryANDROID`.

With `--screenshot-all` flag, the screenshots could be created correctly. This function is very helpful for debugging some Android apps.

Thanks again for your helpful tool.
