### ISSUE TITLE
Add macOS vkcube capture to internal CI

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#1544]

**Comment by fabian-lunarg** [comment]
requires https://github.com/LunarG/gfxreconstruct/issues/1517 first

**Comment by fabian-lunarg** [comment]
macOS: captures for vkcube and a small selection of Sascha's samples are in place for our internal CI.
let me know if there's more I can do  @lunarpapillo

**Comment by bradgrantham-lunarg** [comment]
I don't think this is completed until we can see it running in CI

**Comment by fabian-lunarg** [comment]
-> ok, test/confirm when closing this:
https://github.com/LunarG/Projects/issues/831

**Comment by johnzupin** [comment]
This should be ready to go forward with. I was testing it a little with the vkcube and vulkaninfo captures, trying to do a full run without any tests disabled: http://tcubuser:8080/view/Manual/job/manual-gfxreconstruct/887/console. I will get the commit suite configured to run @fabian-lunarg's other captures.

**Comment by johnzupin** [comment]
I'm getting a pass now on my tests with the current commit-suite: http://erusea:8080/view/Manual/job/manual-gfxreconstruct/891/console

Right now the` nas/smb_traces/vulkan/GFXR/macos/commit-sutite.json` file has a lot of the tests disabled, I think this file might have been copied from somewhere else. Could a gfxreconstruct engineer (@fabian-lunarg) check the `commit-suite.json` and configure it to their liking with the tests they want? And ensure the correct captures are enabled. Or if you want me to enable all of them I would be happy to.

**Comment by fabian-lunarg** [comment]
adjusted `commit-suite.json` and `extended-suite.json` to contain everything we got, but only the short- and -long-running captures respectively

**Comment by johnzupin** [comment]
@lunarpapillo Are we separating the two macs in jenkins with labels, one for VVL testing and one for GFXR testing?

**Comment by KarenGhavam-lunarG** [comment]
> @lunarpapillo Are we separating the two macs in jenkins with labels, one for VVL testing and one for GFXR testing?

I think we should use the same principle on the mac systems that we use elsewhere. One set of systems for capture based testing. One set of systems for non-capture based testing. Do we need to purchase more hardware?

**Comment by lunarpapillo** [comment]
> > @lunarpapillo Are we separating the two macs in jenkins with labels, one for VVL testing and one for GFXR testing?
> 
> I think we should use the same principle on the mac systems that we use elsewhere. One set of systems for capture based testing. One set of systems for non-capture based testing. Do we need to purchase more hardware?

Yes.  We'll need two more Macs.  The two new Macs should match each other, but don't necessarily have to match the two M1 Macs currently in CI (i.e. they can be newer M2 Mac Mini machines).

**Comment by KarenGhavam-lunarG** [comment]
@fabian-lunarg   Zupin has two new M2 mac Minis setup correct for CI. The captures you have are crashing. We believe it is because you did them on your older personal system that was M1. But having M1 instead of M2 shouldn't cause a crash. Would be good to investigate who is crashing and if that can be fixed. And then you probably need to create new captures on these new CI systems (tcmac0 and tcmac1)

**Comment by bradgrantham-lunarg** [comment]
Looks like `gfxreconstruct` is working on `tcmac0` (http://erusea:8080/view/Manual/job/manual-gfxreconstruct/947/ and http://erusea:8080/view/Manual/job/manual-gfxreconstruct/948/).  Is this resolved?  I wouldn't think that capturing again would be necessary unless something really changed in MoltenVk...

**Comment by johnzupin** [comment]
> Looks like `gfxreconstruct` is working on `tcmac0` (http://erusea:8080/view/Manual/job/manual-gfxreconstruct/947/ and http://erusea:8080/view/Manual/job/manual-gfxreconstruct/948/). Is this resolved? I wouldn't think that capturing again would be necessary unless something really changed in MoltenVk...

Yes, thanks to @fabian-lunarg's fix (https://github.com/LunarG/gfxreconstruct/pull/1792). I'm waiting on the gfxreconstruct CI to calm down in order to update the configuration matrix, so it doesn't try to run 32 on mac. Once that is updated I will close this issue out.

**Comment by johnzupin** [comment]
The Mac M2 has been enabled for GFXReconstruct testing in CI for the commit suite. I'm going to close this out.
