### ISSUE TITLE
Add macOS vulkaninfo capture to internal CI

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#1545]

**Comment by fabian-lunarg** [comment]
kind of blocked by https://github.com/LunarG/gfxreconstruct/issues/1580

**Comment by fabian-lunarg** [comment]
succesfully created a capture of (a up-to-date build of) vulkaninfo.
capture/replay works without issues after vulkaninfo applied this fix:
https://github.com/KhronosGroup/Vulkan-Tools/pull/1018

**Comment by fabian-lunarg** [comment]
done!
