### ISSUE TITLE
gfxrecon-toascii needs to support arbitrary path

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/gfxreconstruct#157]
gfxrecon-toascii currently creates a .txt file in the same directory as the trace.

It should take command-line options to allow the .txt file to go to any desired location (including stdout, for use in pipes).

**Comment by patrick-lunarg** [comment]
> @patrick-lunarg can you assign me for creating that feature?

Hey @Samsuper12 ,

Just checking in to see if you've made any progress on this issue.
If not, that's fine...just trying to determine where this issue is at for bug/feature prioritization.

Thanks,
-Patrick

**Comment by Samsuper12** [comment]
@patrick-lunarg Hi!

Now I work with some ASM optimizations in Mesa and allocate 100% of my time to resolve that. 

If you have any tasks for me, I'll be happy in the near future to close those after main work.

About that issue: progress is insignificant, so we can forget about this issue.

Thanks,
- Michael

**Comment by patrick-lunarg** [comment]
> @patrick-lunarg Hi!
> 
> Now I work with some ASM optimizations in Mesa and allocate 100% of my time to resolve that.
> 
> If you have any tasks for me, I'll be happy in the near future to close those after main work.
> 
> About that issue: progress is insignificant, so we can forget about this issue.
> 
> Thanks, -Michael

Thanks for the update.
I'll reassign this task to myself, not sure exactly when we'll get to it.

**Comment by bradgrantham-lunarg** [comment]
Fixed by #647
