### ISSUE TITLE
tracking ticket for multithreaded pipeline compiles

### ISSUE THREAD

**Issue by zmike** [LunarG/gfxreconstruct#1576]
This is a longstanding and important issue that needs to be solved at some point, so I'm making a ticket to track progress.

Computers are getting more cores every year, and engines are using those cores to compile thousands or even millions of pipelines. When replaying a trace from such an engine, a single thread for pipeline compilation is not going to be able to handle the task in a reasonable amount of time.

gfxreconstruct must support multi-threaded pipeline compilation.

**Comment by per-mathisen-arm** [comment]
I think this is tracked by https://github.com/LunarG/gfxreconstruct/issues/1142 already?

**Comment by zmike** [comment]
#1142 looked to me like a more general type of multi-threading ticket.

**Comment by per-mathisen-arm** [comment]
I don't think you're going to see much improvement from trying to add multi-threading into a single-threaded serialized command stream. I suspect you need to make way too many pessimistic assumptions for this to work well.

**Comment by bradgrantham-lunarg** [comment]
@per-mathisen-arm this represents a request for a potential spot-fix for creating a multithreaded queue for `vkCreateGraphicsPipeline`.  #1142 is still the more general ticket for honoring the threading structure in replay of the captured app.
