### ISSUE TITLE
BindVideoSessionMemoryKHR needs to be a method on VulkanResourceAllocator for "rebind" to work

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#1593]
Replaying a Vulkan video decode capture crashes in BindVideoSessionMemoryKHR because the creation of memory is deferred in VulkanRebindAllocator.  Encode will also fail the same way.

**Comment by bradgrantham-lunarg** [comment]
Also note that I wasn't able to run a video decode sample without "-m" nor with "-m realign"  nor "-m remap".

**Comment by locke-lunarg** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/307

VulkanMemoryAllocator doesn't support VideoSession, so some features in VulkanResourceAllocator aren't available.
