### ISSUE TITLE
[build] Missing linux arm precompiled libspirv-reflected 

### ISSUE THREAD

**Issue by infapi00** [LunarG/gfxreconstruct#1613]
Quoting from commit df2099076b71dd3e5bebc8784eaeb4a2b5a5ef9f:

> Remove SPIRV-Reflect submodule and include precompiled binaries

That commit added the following precompiled binaries:

```
./android/lib/arm64-v8a/libspirv-reflect-static.a
./android/lib/x86/libspirv-reflect-static.a
./android/lib/armeabi-v7a/libspirv-reflect-static.a
./android/lib/x86_64/libspirv-reflect-static.a
./linux/lib/x86/libspirv-reflect-static.a
./linux/lib/x86_64/libspirv-reflect-static.a
```

So for linux it only added x86 and x86_64. It is missing arm binaries (like aarch64) for linux. Without that, devices like the Raspberry Pi 5, that usually is used with the Raspberry Pi OS (based on Debian), fails with the following error:

```
[ 87%] Built target gfxrecon_application
/usr/bin/ld: skipping incompatible /home/pi/mesa/source/gfxreconstruct/external/precompiled/linux/lib/x86_64/libspirv-reflect-static.a when searching for -lspirv-reflect-static
/usr/bin/ld: cannot find -lspirv-reflect-static: No such file or directory
```

**Comment by fabian-lunarg** [comment]
heej @infapi00,

we merged a change that replaces precompiled spirv-reflect with a submodule
and I confirmed compilation on pi5 works again.

thanks for reporting!
