### ISSUE TITLE
[replay] Fail to generate VR scene on Android

### ISSUE THREAD

**Issue by Zydiii** [LunarG/gfxreconstruct#1645]
**Describe the replay bug:**
The VR scene dosen't be drawn in the screenshot for the ziroom APP(https://www.ziroom.com/). Sorry for it only has Chinese version.
For example, the original screenshot of the app is like the following:
![image](https://github.com/user-attachments/assets/5680d445-0747-4c08-81fa-5c26cbd99151)
While the screenshot created by replay is like the following, where the VR scene is black:
![image](https://github.com/user-attachments/assets/c97d885d-af16-437a-b20f-7080b16d1566)

**Build Environment:**
I build the capture and replayer on branch dev.

**To Reproduce**
1. Sorry for that I couldn't upload the .gfxr now. The way I create the capture file is:
  ```
  adb shell "setprop debug.vulkan.layers 'VK_LAYER_LUNARG_gfxreconstruct'"
  adb shell "setprop debug.gfxrecon.capture_file /storage/emulated/0/Download/ziroom_capture.gfxr"
  adb shell "setprop debug.hwui.renderer 'skiavk'"
  adb push .\arm64-v8a\libVkLayer_gfxreconstruct.so /data/app/{path}/com.ziroom.ziroomcustomer-{path}/lib/arm64
  ```
2. Run gfxrecon-replay with [PY -3 .\android\scripts\gfxrecon.py replay --screenshot-all --screenshot-dir /sdcard/Download/ziroom /sdcard/Download/ziroom_capture_20240731T021235.gfxr]

**System environment:**
- vulkan-version: 1.3.290

**Comment by KarenGhavam-lunarG** [comment]
We need a repro case to make any progress on this, even if it isn't the actual application but a test case.
