### ISSUE TITLE
[capture] Crash on a memcpy using page_guard (default)

### ISSUE THREAD

**Issue by shanminchao** [LunarG/gfxreconstruct#1664]
**Describe the capture bug:**
Trying to do a capture of the [SaschaWillems](https://github.com/SaschaWillems/Vulkan.git) Vulkan descriptorsets sample.
Running this through VSCode on a Linux machine. I get the following crash:

![image](https://github.com/user-attachments/assets/8054bc50-688f-4369-bdbf-14d0c53cd3a3)

If I set GFXRECON_MEMORY_TRACKING_MODE to "unassisted", the capture finishes successfully.

**Build Environment:**
Using SHA "5720914d71", dev branch.

**Capture Settings:**
No environment variables set when it crashes

**To Reproduce:**
Crashes on startup, running via VSCode. 

**Additional Info:**
Note: If I set GFXRECON_MEMORY_TRACKING_MODE to "unassisted" and get a successful capture, and then try to replay that capture, I get the following:

$ ./gfxrecon-replay ~/src/SaschaWillems/gfxrecon_capture_20240812T125353.gfxr 
[gfxrecon] INFO - Replay has removed the following layers from VkInstanceCreateInfo when calling vkCreateInstance:
[gfxrecon] INFO - 	VK_LAYER_LUNARG_gfxreconstruct
[gfxrecon] WARNING - Requested window size (1280x720) exceeds current screen size (1440x640); replay may fail due to inability to create a window of the appropriate size.
[gfxrecon] WARNING - Requested window size (1280x720) exceeds current screen size (1440x640); replay may fail due to inability to create a window of the appropriate size.
[gfxrecon] FATAL - API call at index: 465 thread: 1 vkQueuePresentKHR returned error value VK_ERROR_OUT_OF_DATE_KHR that does not match the result from the capture file: VK_SUCCESS. Replay cannot continue.
Replay has encountered a fatal error and cannot continue: a surface has changed in such a way that it is no longer compatible with the swapchain

I'm not sure if that's a legitimate bug or not, but worth documenting.

**Comment by panos-lunarg** [comment]
Regarding the page faults.
This is normal. `page_guard` detects user writes (and reads) to mapped device memory regions by protecting the memory. You need to tell vscode to ignore seg faults. You can add this in the debug configuration in `launch.json`.
```
"setupCommands": [
    {
        "description": "Ignore SIGSEGV",
        "text": "handle SIGSEGV nostop noprint pass",
        "ignoreFailures": true
    },
    {
        "text": "handle SIGSEGV nostop noprint pass"
    }
],
```

Alternatively you can try the `userfaultfd` mechanism instead of `page_guard` or `unassisted`.

**Comment by panos-lunarg** [comment]
Regarding the replay failure.
It appears that in the capture file it's recorded a larger swapchain resolution than the one supported by the replaying. Is the capture created in one device and you are attempting to replay on another?

**Comment by shanminchao** [comment]
Ah ha! The "setupCommands" bit solved the issue.
And I debugged the replay issue and narrowed it down to the remote-desktopping I was doing when running Replay. Oops!

Thanks for the quick response!
