### ISSUE TITLE
[build] Spirv-reflect build issue

### ISSUE THREAD

**Issue by bartosz-muszarski-arm** [LunarG/gfxreconstruct#1674]
We're observing build issues on x86 config since spirv-reflect was introduced.
It seems like spirv-reflect is always build as x64, regardless of the selected architecture, then fails on linking against other modules build with the selected arch.

To reproduce:
```
python scripts/build.py -c debug -a x86
```
Relevant logs:
```
/usr/bin/ld: i386:x86-64 architecture of input file `../external/SPIRV-Reflect/libspirv-reflect-static.a(spirv_reflect.c.o)' is incompatible with i386 output
collect2: error: ld returned 1 exit status
make[2]: *** [layer/CMakeFiles/VkLayer_gfxreconstruct.dir/build.make:108: layer/libVkLayer_gfxreconstruct.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:790: layer/CMakeFiles/VkLayer_gfxreconstruct.dir/all] Error 2
```
Tested on latest dev (f5df57e92d3cd403d9536b0a9db50976b12fc155)

**Comment by fabian-lunarg** [comment]
ok, this seems odd. our CI routinely builds/tests **gfxreconstruct** also for x86 on all platforms, so I'm not sure what's causing this issue.

**Comment by bartosz-muszarski-arm** [comment]
I've no idea why it was not picked up by your CI, I had a repro in a fresh ubuntu 22 docker image.
Anyway, this PR fixed the issue https://github.com/LunarG/gfxreconstruct/pull/1676. Thanks!
