### ISSUE TITLE
[openxr] Implement correct Consumer state update for Destroy functions 

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/gfxreconstruct#1718]
Implement correct Consumer state update for Destroy functions (this should probably await code gen cleanup, as clean up operation “mostly noop” calls and overloads can be injected most efficiently in code generation):

* Explicit destroy operations
* Implicit destroy operations to drive the above

**Comment by jzulauf-lunarg** [comment]
Next (last?) piece #1873

**Comment by jzulauf-lunarg** [comment]
All replay generated objects now have cleanup paths for direct and indirect destruction.
