### ISSUE TITLE
[openxr] Refactor replay state/process to match Vulkan

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/gfxreconstruct#1719]
Refactor the OpenXR replay Update functionality to more closely match the behavior in the Vulkan replay path. Currently consumer state is tracked separate from handle info.  Create derived class state object to support single creation, lookup, and cleanup.

**Comment by jzulauf-lunarg** [comment]
@MarkY-LunarG  -- rewrote description to match planned work.

**Comment by MarkY-LunarG** [comment]
Isn't this complete?

**Comment by jzulauf-lunarg** [comment]
merged as shown above
