### ISSUE TITLE
[openxr] Cleanup OpenXR Virtual swapchain code

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/gfxreconstruct#1724]
Clean up and re-organize the OpenXR specific virtual swapchain code.  The would ensure cleanup at shutdown of session application etc. This could include to fallback  to a non-virtual swapchain path (similar to Vulkan).

**Comment by jzulauf-lunarg** [comment]
@MarkY-LunarG -- don't think a non-virtualized swapchain is possible.

**Comment by MarkY-LunarG** [comment]
Ok.  Why don't we close this for now, then.  With a comment somewhere that we don't think it's possible to do.
