### ISSUE TITLE
[capture] trimmed capture of VkSurfaceFullScreenExclusiveWin32InfoEXT crashes

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#1734]
**Describe the capture bug:**
Capture of vkcube modified to add VkSurfaceFullScreenExclusiveWin32InfoEXT and VkSurfaceFullScreenExclusiveInfoEXT causes crash in GFXR

**Build Environment:**
Windows 10
dev, ed4b4b66da027efc8a4a1897f0ebc8d58be633bc

**Capture Settings:**
VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct VK_LAYER_PATH=$GFXR_ROOT/build/layer/Debug GFXRECON_CAPTURE_TRIGGER=F5  vkcube.exe

**To Reproduce:**
Apply the attached [patch.txt](https://github.com/user-attachments/files/16967622/patch.txt) to vkcube

**Screenshots:**
NA

**System environment:**
RTX 2070 Super, 551.76
However, crash is in GFXR and appears unrelated to the driver or GPU

**Additional information (optional):**
Capture succeeds in f6e175620b7fbf7554d60abc06c72a30223e809d

In particular capture succeeds if this line is commented, but that is just for investigation, not a fix:
https://github.com/LunarG/gfxreconstruct/blob/544fb679efa651542c3a1938a8221c2361967083/framework/generated/generated_vulkan_struct_deep_copy.cpp#L15211

**Comment by dgraves** [comment]
For some additional details about the crash, an access violation is raised when a generated struct copy function specifies an opaque handle as the source parameter for a memcpy call. 

This commit adds logic to the struct copy code generator to detect these types of opaque objects and avoid attempting to copy them: fb10c2bbc4b88969885389aa0aa58e17bea73049

There are some additional details in the commit message. The commit could be used as a starting point for a fix. There is also an additional consideration, as noted in the commit message, needed for VkPushDescriptorSetWithTemplateInfoKHR::pData, which would require a custom copy routine based on the layout of the descriptor update template.
