### ISSUE TITLE
How about support capture/replay vulkan api vkDebugMarkerSetObjectNameEXT?

### ISSUE THREAD

**Issue by JasonWinston** [LunarG/gfxreconstruct#1742]
I capture gfxr file, then use renderdoc capture the gfxr replay. but, all texture/buffer meaningful name disappear. because gfxr do not support capture/replay vkDebugMarkerSetObjectNameEXT ,why , is there some problem for supporting this api?

**Comment by per-mathisen-arm** [comment]
Does your capture and replay hosts both support VK_EXT_debug_marker? Did you check if the calls ended up in the gfxr trace file (using gfxr-convert to convert it to json)?

**Comment by fabian-lunarg** [comment]
hello @JasonWinston!

we do have support for `VK_EXT_debug_marker` including `vkDebugMarkerSetObjectNameEXT`.

I tried reproducing the steps you took, capturing this [sample](https://github.com/SaschaWillems/Vulkan/tree/master/examples/debugutils) using both GFXReconstruct and Renderdoc.

In Renderdoc all debug-labels/names are present, as expected.
then I confirmed the debug-labels and -names are present in the `.gfxr` file by using `gfxrecon-convert` and inspected the resulting `.json`.

lastly I used `gfxrecon-replay` to replay the captured `.gfxr` and captured that using Renderdoc.
you can see on the attached screenshots, everything seems fine, the labels survived all operations and I was not able to reproduce the error.

original renderdoc-capture:
![2024_09_18_debugutils_renderdoc](https://github.com/user-attachments/assets/3ee524d9-4293-4217-b55d-063a83db15ec)

gfxrecon-replay renderdoc-capture:
![2024_09_18_debugutils_replay_renderdoc png](https://github.com/user-attachments/assets/c166d7dd-a343-4876-8c7c-bb64eef1f920)

would you be able to provide additional information, helping us understand what/where things go wrong in your case?

**Comment by fabian-lunarg** [comment]
after posting that above I was able to reproduce a case where in fact labels where present in Renderdoc but missing from a gfxr-capture.  
A possible reason (and explanation in my case) 'might' be:
- the application you're capturing did not enable [VK_EXT_debug_marker](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_debug_marker.html) at all, but Renderdoc injected it for you (Renderdoc will adjust the instance/device layer-stack)
- GFXReconstruct does not temper with requested layers, so `VK_EXT_debug_marker` won't be used automatically

**Comment by fabian-lunarg** [comment]
closing this issue after being inactive for a while. if the explanations offered here were missing something, we'll get back to it.
