### ISSUE TITLE
[openxr] Fix xrLocateViewSpace issues for OpenXR 1.0

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/gfxreconstruct#1770]
The entrypoints we use to convert a presented surface to local view space on replay are only available in OpenXR 1.1.  There is functionality we can use for 1.0, it just requires more work.  But it needs to be implemented.

**Comment by jzulauf-lunarg** [comment]
Fixed by https://github.com/LunarG/gfxreconstruct/pull/1774
