### ISSUE TITLE
Invalid table in USAGE_desktop_Vulkan

### ISSUE THREAD

**Issue by Avokadoen** [LunarG/gfxreconstruct#1856]
Seems to be introduced recently in 31e59f54dbc6d32f92b9ec8b6f3b70509fc43358

Anchor link to table: https://github.com/LunarG/gfxreconstruct/blob/dev/USAGE_desktop_Vulkan.md#supported-options

Scroll and you should see the table is no longer rendering and all the remaining table entries are presented in plain text

**Comment by panos-lunarg** [comment]
Thanks for bringing this up. https://github.com/LunarG/gfxreconstruct/pull/1857 should fix the table

**Comment by panos-lunarg** [comment]
https://github.com/LunarG/gfxreconstruct/pull/1857 has been in `dev`
