### ISSUE TITLE
[replay] unable to dump all image resources

### ISSUE THREAD

**Issue by citrix123** [LunarG/gfxreconstruct#1865]
**Describe the replay bug:**
I was trying to dump all image resources using "--dump-resources-dump-all-image-subresources"
Is there anything i am doing wrong ?

**Verify before submission:**
* Was trimming enabled?
No
* Was replayer renamed if necessary?
No
* Was --sync used if title is known to need forced synchronization?
No
* Was replay working without any extra params
Yes

**Build Environment:**
SHA - ba00d9d9fd180b25fcccb8b4a892700f6aba65cc

**To Reproduce**
1. you can take any gfxr trace, i tried with vkcube.
2. Run gfxrecon-replay with [--dump-resources-dump-all-image-subresources] 
```sh
./gfxrecon-replay --dump-resources-dump-all-image-subresources /tmp/gfxrecon_capture_20241104T190350.gfxr
```

**System environment:**
 - GPU and driver version on which capture was taken
RX 7900 XT + AMDVLK
 - GPU and driver version on which capture file was replayed with issue
RX 7900 XT + AMDVLK

**Comment by panos-lunarg** [comment]
`dump-resources-dump-all-image-subresources` is for dumping image _sub_ resources (i.e. all mip levels and array layers). You still need to specify the block indixes of the commands you want to dump (draw calls / disaptch etc)

**Comment by citrix123** [comment]
Thanks for your reply, Can you please help to point me to some example?

**Comment by panos-lunarg** [comment]
I think there are a couple of examples in https://github.com/LunarG/gfxreconstruct/blob/dev/vulkan_dump_resources.md

**Comment by bradgrantham-lunarg** [comment]
Hi @citrix123 , were you able to resolve your issue?

**Comment by citrix123** [comment]
Sorry for the late reply, Yes I was able to dump the images after
understanding the json content 😊

Although I feel it was be a bit complex in my case when I have a ~4 GB
trace file. Is there any way to dump out all the draws by frame numbers
like I want to dump the resources of certain frame?

**Comment by panos-lunarg** [comment]
No, unfortunately there's no such option

**Comment by bradgrantham-lunarg** [comment]
I apologize but the feature is meant to be used by an interactive tool which can programmatically determine block indices and use them to request pre- and post-draw-call images for a Vulkan analysis tool with a GUI.

**Comment by citrix123** [comment]
Thanks for the info, yes I assumed the same ☺️
Do you know if there are any gui tools to load gfxr and determine blocks
etc?
