### ISSUE TITLE
Crash when using page_guard on macOS

### ISSUE THREAD

**Issue by DDoS** [LunarG/gfxreconstruct#1893]
~I built for macOS, following the instructions in the doc, but the layer didn't load. I found out `MACOS` is missing in `layer/json/VkLayer_gfxreconstruct.json.in`.~ After adding it I could use the tool, except I had to use `unassisted` for the memory tracking mode. The default mode crashed.

**Comment by bradgrantham-lunarg** [comment]
I just tested `dev` on my Macbook Pro with macOS 12.6.7 and loader 1.3.296 and didn't need `MACOS` in the manifest in order to capture a Vulkan test program I have here.  Is it possible you changed something else when you added `MACOS`?  Can you give more details on your version of macOS and your loader version?

@charles-lunarg I don't see any reference to `"MACOS"` in the loader - is `"platforms"` ignored?

@DDoS The default mode should probably have worked unless the application is doing something clever with signal handlers that conflicts with our `mprotect` signal handler.  Can you tell us anything else about the app?

**Comment by bradgrantham-lunarg** [comment]
It looks from the Loader Layer Interface doc (https://github.com/KhronosGroup/Vulkan-Loader/blob/main/docs/LoaderLayerInterface.md) that "platforms" is for documentation and tool use only.
 
```
The ability to briefly document the layer thanks to the fields:

    "introduction": Presentation of the purpose of the layer in a paragraph.
    "url": A link the the layer home page.
    "platforms": The list of supported platforms of the layer
    "status": The life cycle of the layer: Alpha, Beta, Stable, or Deprecated

These changes were made to enable third-party layers to expose their features within [Vulkan Configurator](https://github.com/LunarG/VulkanTools/blob/main/vkconfig/README.md) or other tools.
```
So that sounds like we should add `"MACOS"` for tooling purposes.

I'd like to focus on the memory tracking mode.  Can you tell us more about what happens with the default page_guard memory tracking mode?

**Comment by DDoS** [comment]
I think what happened with `MACOS` is that I was actually having a dylib path issue, and noticed it was missing in the JSON while looking for the solution, so I added thinking it was part of the problem. But I didn't think to retest without it once I resolved my path issue. I'll try that tomorrow morning, but I expect it'll work. Sorry for the misleading issue.

About the crash, I was trying to record an OpenUSD rendering test, using Lavapipe as the driver. It was crashing on some VMA code. I'll share a stack trace context info tomorrow when I'm back at work.

**Comment by DDoS** [comment]
I tested again this morning, and indeed the missing `MACOS` platform is not an issue.

When running a `Release` or `RelWithDebInfo` build, I get this crash:
```
WARNING | LAYER:   Layer "VK_LAYER_LUNARG_gfxreconstruct" forced enabled due to env var 'VK_LOADER_LAYERS_ENABLE'
WARNING | LAYER:   Layer "VK_LAYER_LUNARG_gfxreconstruct" forced enabled due to env var 'VK_LOADER_LAYERS_ENABLE'
[gfxrecon] INFO - Settings Loader: Found option "GFXRECON_CAPTURE_FILE" with value "usd_capture.gfxr"
[gfxrecon] INFO - Settings Loader: Found option "GFXRECON_MEMORY_TRACKING_MODE" with value "unassisted"
[gfxrecon] INFO - Initializing GFXReconstruct capture layer
[gfxrecon] INFO -   GFXReconstruct Version 1.0.5 (35e9638) RelWithDebInfo
[gfxrecon] INFO - Recording graphics API capture to usd_capture_20241128T104057.gfxr
Exception: EXC_BAD_ACCESS (code=1, address=0xffffffffffffffff)

gfxrecon::encode::CommonCaptureManager::CreateCaptureFile(gfxrecon::format::ApiFamilyId, const std::string &) capture_manager.cpp:1027
gfxrecon::encode::CommonCaptureManager::Initialize(gfxrecon::format::ApiFamilyId, std::string, const gfxrecon::encode::CaptureSettings::TraceSettings &) capture_manager.cpp:379
gfxrecon::encode::CommonCaptureManager::LockedCreateInstance(gfxrecon::encode::ApiCaptureManager *, const std::function<…> &) capture_manager.cpp:173
gfxrecon::encode::CommonCaptureManager::CreateInstance(gfxrecon::encode::ApiCaptureManager *, const std::function<…> &) capture_manager.cpp:130
gfxrecon::encode::CommonCaptureManager::CreateInstance<…>() capture_manager.h:175
[Inlined] gfxrecon::encode::VulkanCaptureManager::CreateInstance() vulkan_capture_manager.cpp:65
gfxrecon::encode::VulkanCaptureManager::OverrideCreateInstance(const VkInstanceCreateInfo *, const VkAllocationCallbacks *, VkInstance_T **) vulkan_capture_manager.cpp:587
gfxrecon::encode::CreateInstance(const VkInstanceCreateInfo *, const VkAllocationCallbacks *, VkInstance_T **) generated_vulkan_api_call_encoders.cpp:67
loader_create_instance_chain 0x0000000104792e38
vkCreateInstance 0x000000010479896c
... USD code omitted ...
start 0x0000000191a5b154

env_vars[env_vars.size() - 1] = '\0'; // It's empty!
```

With a `Debug` build this crash doesn't happen, and instead I get another crash on [this line](https://github.com/PixarAnimationStudios/OpenUSD/blob/baf2d090a35445ad6bc30c26e3cf19fa57331525/pxr/imaging/hgiVulkan/buffer.cpp#L246) on the very first call. Looks like `map` is an invalid pointer. No crash in `unassisted` mode.

**Comment by panos-lunarg** [comment]
Can you try again this time with `GFXRECON_PAGE_GUARD_SIGNAL_HANDLER_WATCHER=true`?

**Comment by DDoS** [comment]
> `GFXRECON_PAGE_GUARD_SIGNAL_HANDLER_WATCHER`

No difference.

**Comment by bradgrantham-lunarg** [comment]
> [gfxrecon] INFO - Settings Loader: Found option "GFXRECON_MEMORY_TRACKING_MODE" with value "unassisted"

This or `assisted` implies no `page_guard` and so `SIGNAL_HANDLER_WATCHER` doesn't apply.

@DDoS  You said you had tried the default for memory tracking; the default for `GFXRECON_MEMORY_TRACKING_MODE` is "page_guard".  I verified with hacked source that if I don't set `GFXRECON_MEMORY_TRACKING_MODE` it's set to "page_guard".  Have you always set `TRACKING_MODE` or have you tried capturing without setting that environment variable?

**Comment by DDoS** [comment]
On debugging the second crash I also removed `GFXRECON_MEMORY_TRACKING_MODE`. The log from my previous comment is about a first crash happening inside `gfxrecon::encode::CommonCaptureManager::CreateCaptureFile`, which only happens in release builds.

For the second crash happening when memcpy'ing to the pointer returned by VMA, I removed the environment variables and set `GFXRECON_PAGE_GUARD_SIGNAL_HANDLER_WATCHER=true`. It made no difference. I'll retry to be sure and share a log tomorrow when I'm back at work.

**Comment by bradgrantham-lunarg** [comment]
Are you able to capture vkcube?

**Comment by DDoS** [comment]
> Are you able to capture vkcube?

Doesn't seem possible on macOS. `vkcube.app` is a hardened binary, so it won't load libraries that aren't signed by the same origin. The solution mentioned in [BUILD.md](https://github.com/LunarG/gfxreconstruct/blob/dev/BUILD.md#code-signing) only works if you have the signing keys for the app.

It also won't load from relative paths, which is how it's setup in the JSON file.
```
dlopen(libVkLayer_gfxreconstruct.dylib, 0x0005): tried: 'libVkLayer_gfxreconstruct.dylib' (relative path not allowed in hardened program)
```

**Comment by bradgrantham-lunarg** [comment]
> `vkcube.app` is a hardened binary

Yes, I think I made an assumption that you had built from scratch.  Sorry about that.

I was able to run vkgears @6294ee08c7bc33ddea2e39b6e5f57bc15f6ffb70 (main just now) and capture with default settings on MoltenVk.  I've attached my capture, which you may be able to replay.

[vkgears-capture.zip](https://github.com/user-attachments/files/17981857/vkgears-capture.zip)

You can look at the output of `gfxrecon-convert` to verify that `vkMapMemory` was called successfully.   (I also verified with printf.)

I had to add `VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME` to `ppEnabledExtensionNames` and `.flags = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR` to the instance createinfo in `vkgears` in order to run it with MoltenVk (otherwise CreateInstance will return `VK_ERROR_INCOMPATIBLE_DRIVER`), so I suspect you have local changes that may affect your build or maybe you did not actually get MoltenVk when you thought you did.  I think it would be worth you trying on a clean build of demos and the SDK and make sure with `VK_LOADER_DEBUG=all` that you are getting the environment variables and ICD that you want.

**Comment by DDoS** [comment]
I was able to replay your capture with MoltenVK.

I just discovered if I don't run with a debugger it works fine. Was that the problem all along? Sorry for wasting your time if capturing while debugging was never supposed to work...

Anyway here's the full debug log: [log.txt](https://github.com/user-attachments/files/17995928/log.txt)

**Comment by DDoS** [comment]
@bradgrantham-lunarg Should I open a separate issue for the environment variable code crash mentioned in https://github.com/LunarG/gfxreconstruct/issues/1893#issuecomment-2506417931?

**Comment by bradgrantham-lunarg** [comment]
> @bradgrantham-lunarg Should I open a separate issue for the environment variable code crash mentioned in [#1893 (comment)](https://github.com/LunarG/gfxreconstruct/issues/1893#issuecomment-2506417931)?

I wasn't able to reproduce that either.
```
Bradleys-MacBook-Pro:vulkan grantham$ GFXRECON_CAPTURE_FILE=usd_capture.gfxr GFXRECON_MEMORY_TRACKING_MODE=unassisted VK_LAYER_PATH=~/trees/gfxreconstruct/build/layer/ VK_LOADER_LAYERS_ENABLE=VK_LAYER_LUNARG_gfxreconstruct ./vkgears
[gfxrecon] INFO - Settings Loader: Found option "GFXRECON_CAPTURE_FILE" with value "usd_capture.gfxr"
[gfxrecon] INFO - Settings Loader: Found option "GFXRECON_MEMORY_TRACKING_MODE" with value "unassisted"
[gfxrecon] INFO - Initializing GFXReconstruct capture layer
[gfxrecon] INFO -   GFXReconstruct Version 1.0.5-dev (dev:57e25f6) Release
[gfxrecon] INFO - Recording graphics API capture to usd_capture_20241203T180557.gfxr
[gfxrecon] INFO -   Vulkan Header Version 1.3.296
vkMapMemory succeeded
16259 frames in 5.0 seconds = 3251.656 FPS
```
I don't understand your comment `env_vars[env_vars.size() - 1] = '\0'; // It's empty!`.  Can you explain what you mean by that?

**Comment by DDoS** [comment]
The `env_vars` string was empty, `size()` was zero.

**Comment by bradgrantham-lunarg** [comment]
> The `env_vars` string was empty, `size()` was zero.

Got it.  I was looking at `dev`, which wraps that with a check against `size`.  That was fixed two months ago in #1786.  I suggest you update to `dev`, maybe today's will work for you.

**Comment by bradgrantham-lunarg** [comment]
Hm.  I think the implication is that GFXR included in SDK 1.3.296 won't run in Release on MacOS!

**Comment by DDoS** [comment]
I didn't know gfxreconstruct was included in the macOS Vulkan SDK. I built the latest release from source because I couldn't find it in the latest Vulkan SDK install. Maybe it's just an installer option I missed or I didn't search well enough.

Anyway nice to see it's already fixed. That's all my issues resolved, thanks for all the help.

**Comment by bradgrantham-lunarg** [comment]
Looks like I'm inventing things - GFXR macOS isn't in the SDK yet.

I'm glad you brought up the issues and I had to learn some new things and add some notes to our docs.
