### ISSUE TITLE
Implement Portability Mode

### ISSUE THREAD

**Issue by dustin-lunarg** [LunarG/gfxreconstruct#192]
Implement a portability mode when attempting to replay on a system with a different GPU/driver than the capture system.  This would include the following:
This feature will be implemented with the following sub-tasks.
- [x] Device selection (#275 )
- [x] Memory Type Translation (#276)
- [x] Swapchain Adjustment (#277)

Differences with device features or extensions would most likely need to be handled at capture time, where the capture layer, or the existing dev-sim layer, could disable any features or extensions that will not be supported on the replay device.

Differences with the number of available queue families and number of queues available per family could potentially be handled on replay with some sort of mapping, but care would need to be taken when consolidating queue submissions from N queues to 1 queue to avoid synchronization issues and ensure submissions are merged in the correct order.  It may be simpler to handle this case by using the dev-sim layer to report fewer available queues on capture.

**Comment by ashmittal85** [comment]
Do we have an ETA to try this out?

**Comment by ashishmittal85** [comment]
Hi Dustin,
Could you elaborate on how we can select the device and memory type when replaying on Linux?

Ashish

**Comment by dustin-lunarg** [comment]
This feature isn't available yet.  We are currently focused on implementing the trimming feature, but I currently expect the portability feature to be our next priority after trimming is complete.  This issue will be updated when initial support for portability is available.

**Comment by tanty** [comment]
How is this relating to #384 ? Is that PR going to be dropped altogether since this is the planned solution for the same problem?

**Comment by dustin-lunarg** [comment]
@tanty PR #384 will become a new option for the existing memory translation feature.  It is currently going through review, and may receive some updates this week.
