### ISSUE TITLE
generate_vulkan.py reorders methods and structs in generated_* files causing compilation failure

### ISSUE THREAD

**Issue by werman** [LunarG/gfxreconstruct#226]
I'm to make a change in one of the generators however when I run `generate_vulkan.py` it updates all `generated_*` files reordering structs and methods in them. This causes compilation failure due to incomplete type passed to `StructPointerDecoder`:
```
framework/decode/struct_pointer_decoder.h: In instantiation of ‘class gfxrecon::decode::StructPointerDecoder<gfxrecon::decode::Decoded_VkDeviceQueueCreateInfo>’:
generated/generated_vulkan_struct_decoders.h:52:59:   required from here
decode/struct_pointer_decoder.h:57:30: error: invalid use of incomplete type ‘struct gfxrecon::decode::Decoded_VkDeviceQueueCreateInfo’
     typename T::struct_type* GetPointer() const { return struct_memory_; }
                              ^~~~~~~~~~
In file included from decode/descriptor_update_template_decoder.h:23,
                 from decode/descriptor_update_template_decoder.cpp:18:
generated/generated_vulkan_struct_decoders_forward.h:76:8: note: forward declaration of ‘struct gfxrecon::decode::Decoded_VkDeviceQueueCreateInfo’
 struct Decoded_VkDeviceQueueCreateInfo;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dustin-lunarg** [comment]
Are you using Python 2? If so, you will need to use Python 3.  

The code generation scripts are based on the Khronos XML Registry scripts from the [Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers) repository, which uses Python 3. I have noticed the reordering issue you describe when attempting to use Python 2 with the code generator.

**Comment by werman** [comment]
Yes, I used python2. Initially I tried python3 but if I remember correctly it wasn't able to find generator dependency however I away from that machine at the moment and probably it was something trivial. 
Thanks!

**Comment by werman** [comment]
Ok, I had two packages which conflicted with registry's scripts: `py-generator` and `reg`; uninstalling them solved the issues.

Since the original issue is resolved I'm closing this.
