### ISSUE TITLE
Allow to select the physical device with the replay tool

### ISSUE THREAD

**Issue by hakzsam** [LunarG/gfxreconstruct#247]
Hi,

gfxcon-replay doesn't support selecting the physical device and it always uses the first one.
In a multi-gpu scenario, this doesn't allow to replay traces on the second gpu for example.
Can you add a new option please?
Thanks!

**Comment by dustin-lunarg** [comment]
When you say that gfxrecon-replay will always use the first physical device, are you experiencing an issue where you create a capture on the second device, but gfxrecon-replay will always try to replay on the first device?  Or would you like a new option that will allow you to capture on the first device and replay the same capture on both the first device and the second device?

**Comment by hakzsam** [comment]
I only want a new option that allows to select the physical device with gfxrecon-replay.

**Comment by dustin-lunarg** [comment]
I have submitted #248 to add a command line option to specify the replay device.

**Comment by hakzsam** [comment]
Great, thanks!
