### ISSUE TITLE
API Features Not Currently Supported for Trimming

### ISSUE THREAD

**Issue by dustin-lunarg** [LunarG/gfxreconstruct#273]
Support needs to be added to the trimming state tracker for the following:

- [x] vkBindImageMemory2 and VkBindBufferMemory2 (partially supported)
- [x] vkBindImageMemorySwapchainInfoKHR
- [x] VK_EXT_inline_uniform_block
- [x] VK_EXT_full_screen_exclusive
- [x] VK_AMD_display_native_hdr (vkSetLocalDimmingAMD)
- [x] VK_NV_ray_tracing (probably very similar to ~KHR_ray_tracing~ KHR_ray_tracing_pipeline)
* ~VK_NVX_device_generated_commands~ defer to post-1.0 trimming support
* ~VK_KHR_timeline_semaphore~ #505 
- [x] VK_KHR_create_renderpass2 - tracked as if ithe associated structs are the ones for 1.0 renderpass, so some things are not tracked correctly (see #551 )

**Comment by dustin-lunarg** [comment]
PR #335 added support for tracking resource/memory bindings performed with vkBindImageMemory2 and VkBindBufferMemory2 , but does not track extensions structures provided to those calls.

**Comment by locke-lunarg** [comment]
Closed VK_NV_ray_tracing , since it has supported VK_KHR_ray_tracing_pipeline. Even NVidia recommend using VK_KHR_ray_tracing_pipeline, so I think we could skip VK_NV_ray_tracing .
https://github.com/nvpro-samples/vk_raytracing_tutorial_nv
