### ISSUE TITLE
screenshot and gfxreconstruct have different frame number conventions

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/gfxreconstruct#284]
`VK_LAYER_LUNARG_screenshot` uses 0-based frame numbers (frame 0 is the first frame, etc.).  `gfxreconstruct` uses 1-based frame numbers (frame 1 is the first frame).

This leads to user confusion when, for example, the user has identified that frame **X** in a trace is important, and uses it as a screenshot keyframe; but to trim to just that frame in `gfxreconstruct` would require trimming to frame **X+1**.

We should be consistent.  Although I prefer the `gfxreconstruct` convention, it's more important to be consistent with the earlier `screenshot` standard.

**Comment by wbarnesSamsung** [comment]
Renderdoc and other common gfx tools index from 0, as well.  In addition, trimming gfxr files will sometimes include additional presents that further changes the gfxr frame start of indexing.

**Comment by dustin-lunarg** [comment]
We may reevaluate the indexing scheme prior to the 1.0 release, but for now I would recommend using the replay tool's new built-in screenshot support.  It uses the same frame number convention as the capture layer and will ignore the additional presents that are executed for trimmed file replay.

For trimmed file replay, swapchain images are acquired and presented during the initial state setup.  The number of images presented will vary, based on the index of the image used in the first trimmed frame.  We basically need acquire and present images to march forward to the index that the first frame expects to use.

There is no way for the screenshot layer to distinguish between present calls made for the state setup and present calls made when rendering the captured frame(s), but the replay tool is able to make this distinction and will not generate screenshots for the present calls that are made during setup.

**Comment by lunarpapillo** [comment]
> I would recommend using the replay tool's new built-in screenshot support.

I agree.  This will allow us to exercise the internal image capture functionality, and would simplify the image comparison logic (we wouldn't need a full convolution comparison to figure out which screenshots are unintended).

This is planned for the next revision of the **gfxreconstruct** test support.

There's still something to be said for having a consistent ecosystem, with tools that all use the same indexing conventions, both for the appearance of professionalism and to avoid confusing users.
