### ISSUE TITLE
How to Documentation

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/gfxreconstruct#322]
A document is needed to indicate how the GFX Reconstruct tool is  used. A getting started or something...

**Comment by dustin-lunarg** [comment]
The basic usage documentation is referenced from README.md with the following links:
* [Using the Vulkan Layer](https://github.com/LunarG/gfxreconstruct/blob/master/layer/README.md)
* [Using the GFXReconstruct Replay tool](https://github.com/LunarG/gfxreconstruct/blob/master/tools/replay/README.md)
