### ISSUE TITLE
Add Zstandard compression support

### ISSUE THREAD

**Issue by tanty** [LunarG/gfxreconstruct#330]
`gfxreconstruct` supports LZ4, which is very fast but doesn't have a very good compression ratio, and ZLIB which provides a nice compression ratio but is much slower.

It would be great if Zstandard would be also available as a compression alternative since it is way faster than ZLIB while also providing a good compression ratio:
https://facebook.github.io/zstd/

**Comment by dustin-lunarg** [comment]
PR #334 adds initial support for Zstandard compression.  It doesn't include precompiled binaries for Windows or Android yet, but CMake should automatically detect and build with Zstandard compression enabled for Linux with the appropriate packages installed.

LZ4 is still the default compression format, but you can enable Zstandard for capture by setting `GFXRECON_CAPTURE_COMPRESSION_TYPE=zstd`.  The gfxrecon-compress utility can also be used to convert existing files to Zstandard:
```
$ ./gfxrecon-compress test_20200225T171645.gfxr test_zstd.gfxr ZSTD      
Compression Results:
  Original Size   [Compression:   LZ4] = 283426 bytes
  Compressed Size [Compression:  ZSTD] = 213723 bytes
  Percent Reduction                    = 24.59%
```

**Comment by dustin-lunarg** [comment]
PR #334 has merged with the dev branch.
