### ISSUE TITLE
Unable to trace Subnautica

### ISSUE THREAD

**Issue by Evernow** [LunarG/gfxreconstruct#343]
Hello there!

Have been trying to trace Subnautica to help troubleshoot a hang that occurs with Navi, but the game crashes shortly after opening.

This was previously opened in https://github.com/LunarG/VulkanTools/issues/989

Short summary is this is what happens when I try to do it: 

In the command window it kept spamming "type known not a basic type"

To confirm the commands I ran were in order:

export VK_LAYER_PATH=//run/media/daniel/O/gfxreconstruct/gfxreconstruct/build/layer:$VK_LAYER_PATH

export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct

steam steam://rungameid/264710

This was the file I got in the game's directory:

https://github.com/LunarG/VulkanTools/files/4489185/gfxrecon_capture_20200416T144213.gfxr.zip

When running the file through gfxrecon-toascii I got: https://github.com/LunarG/VulkanTools/files/4490703/gfxrecon_capture_20200416T144213.txt

When using the API dump layer I get: (extracted it is an insane 450mb):

https://drive.google.com/file/d/1hCakmLaAJjq6nD_c6XorenrRGM8tZd8x/view?usp=sharing

System:

Manjaro
5700 XT
Mesa 20.1.0-devel (git-cab245ea15)
LLVM 11 git
ACO enabled

**Comment by dustin-lunarg** [comment]
For this case, we have a Unity game that is using Mono on Linux.  It looks like there is a conflict between Mono exception handling and the way that the capture layer detects modifications to memory.  

We may be able to address this issue by changing the way that we set up a signal handler in the layer.  Mono is using an alternate signal stack, and setting the layer's signal handler to use the alternate signal stack seems to resolve the issue.

I was able to get a good capture with the following change:
```
diff --git a/framework/util/page_guard_manager.cpp b/framework/util/page_guard_manager.cpp
index ac96a4f..fc2209d 100644
--- a/framework/util/page_guard_manager.cpp
+++ b/framework/util/page_guard_manager.cpp
@@ -331,7 +331,7 @@ void PageGuardManager::AddExceptionHandler()
         }
 #else
         struct sigaction sa;
-        sa.sa_flags = SA_SIGINFO;
+        sa.sa_flags = SA_SIGINFO|SA_ONSTACK;
         sigemptyset(&sa.sa_mask);
         sa.sa_sigaction = PageGuardExceptionHandler;
         if (sigaction(SIGSEGV, &sa, &s_old_sigaction) == -1)
```

An official fix may require some additional work and may not be available right away.  Let me know if you want me to create a branch with a quick fix, and I'll create one as soon as possible.

**Comment by Evernow** [comment]
> For this case, we have a Unity game that is using Mono on Linux. It looks like there is a conflict between Mono exception handling and the way that the capture layer detects modifications to memory.
> 
> We may be able to address this issue by changing the way that we set up a signal handler in the layer. Mono is using an alternate signal stack, and setting the layer's signal handler to use the alternate signal stack seems to resolve the issue.
> 
> I was able to get a good capture with the following change:
> 
> ```
> diff --git a/framework/util/page_guard_manager.cpp b/framework/util/page_guard_manager.cpp
> index ac96a4f..fc2209d 100644
> --- a/framework/util/page_guard_manager.cpp
> +++ b/framework/util/page_guard_manager.cpp
> @@ -331,7 +331,7 @@ void PageGuardManager::AddExceptionHandler()
>          }
>  #else
>          struct sigaction sa;
> -        sa.sa_flags = SA_SIGINFO;
> +        sa.sa_flags = SA_SIGINFO|SA_ONSTACK;
>          sigemptyset(&sa.sa_mask);
>          sa.sa_sigaction = PageGuardExceptionHandler;
>          if (sigaction(SIGSEGV, &sa, &s_old_sigaction) == -1)
> ```
> 
> An official fix may require some additional work and may not be available right away. Let me know if you want me to create a branch with a quick fix, and I'll create one as soon as possible.

Apologies for the delay and thank you! Out of curiosity how does one apply that patch? Normally I do them through PKGBUILDs but this is not available in the AUR, a branch with the fix would be greatly appreciated!

**Comment by dustin-lunarg** [comment]
>Apologies for the delay and thank you! Out of curiosity how does one apply that patch? Normally I do them through PKGBUILDs but this is not available in the AUR, a branch with the fix would be greatly appreciated!

No worries.  I just merged a fix to the dev branch if you want to try it out.  Regarding the patch from my last reply, it should be possible to apply by copying it to a file and then running something like `patch -p < filename` from the top level directory of the GFXReconstruct repository.

**Comment by dustin-lunarg** [comment]
The fix for this issue has been merged to the master branch.
