### ISSUE TITLE
The Witcher 2 (DXVK) will not capture

### ISSUE THREAD

**Issue by Evernow** [LunarG/gfxreconstruct#345]
Hello there!

Sadly do not have much information to provide, there is no file provided anywhere, perhaps this is due to the Witcher 2 being 32bit?

To confirm the commands I ran were in order:

export VK_LAYER_PATH=/run/media/daniel/O/gfxreconstruct/gfxreconstruct/build/layer:$VK_LAYER_PATH

export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct

steam steam://rungameid/20920

Vktrace does not provide anything useful either, only provides this 200kb file: 
[thewitcher2.vktrace.zip](https://github.com/LunarG/gfxreconstruct/files/4511850/thewitcher2.vktrace.zip)

**Comment by dustin-lunarg** [comment]
You are correct that this is due to the game being 32-bit.  I was able to capture successfully with a 32-bit build of the capture layer.

The build instructions do not currently document 32-bit builds for Linux, but I did the following:
First, I had to install 32-bit dependencies.  For Fedora, this was:
```
sudo dnf install libstdc++-devel.i686 glibc-devel.i686 libX11-devel.i686 libxcb-devel.i686 \ 
        libXrandr-devel.i686 wayland-devel.i686 xcb-util-keysyms-devel.i686 lz4-devel.i686 \
        libzstd-devel.i686
```
Next, I used the following command to generate 32-bit build files with CMake:
```
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_SHARED_LINKER_FLAGS=-m32
```
Building with the generated makefiles produced a 32-bit capture layer that seemed to work correctly with the game.

To determine if the capture layer was being loaded, I used the VK_LOADER_DEBUG environment variable to increase the verbosity of messages from the Vulkan loader.  This is the setup I used:
```
export VK_LAYER_PATH=/home/dustin/gfxreconstruct/build/layer/
export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct
export VK_LOADER_DEBUG=all
steam steam://rungameid/20920 | grep -i gfxrecon
```

When the 64-bit layer failed to load, I received the following messages:
```
DEBUG: ReadDataFilesInSearchPaths: Searching the following paths for manifest files: /home/dustin/Projects/gfxreconstruct/build/layer/
INFO: Found manifest file /home/dustin/Projects/gfxreconstruct/build/layer//VK_LAYER_LUNARG_gfxreconstruct.json, version "1.1.0"
ERROR: /home/dustin/gfxreconstruct/build/layer/./libVkLayer_gfxreconstruct.so: wrong ELF class: ELFCLASS64
```

When the layer is loaded correctly, the error message should be replaced by messages like:
```
DEBUG: Loading layer library /home/dustin/Projects/gfxreconstruct/build/layer/./libVkLayer_gfxreconstruct.so
INFO: Insert instance layer VK_LAYER_LUNARG_gfxreconstruct (/home/dustin/Projects/gfxreconstruct/build/layer/./libVkLayer_gfxreconstruct.so)
```

**Comment by Evernow** [comment]
> You are correct that this is due to the game being 32-bit. I was able to capture successfully with a 32-bit build of the capture layer.
> 
> The build instructions do not currently document 32-bit builds for Linux, but I did the following:
> First, I had to install 32-bit dependencies. For Fedora, this was:
> 
> ```
> sudo dnf install libstdc++-devel.i686 glibc-devel.i686 libX11-devel.i686 libxcb-devel.i686 \ 
>         libXrandr-devel.i686 wayland-devel.i686 xcb-util-keysyms-devel.i686 lz4-devel.i686 \
>         libzstd-devel.i686
> ```
> 
> Next, I used the following command to generate 32-bit build files with CMake:
> 
> ```
> cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_SHARED_LINKER_FLAGS=-m32
> ```
> 
> Building with the generated makefiles produced a 32-bit capture layer that seemed to work correctly with the game.
> 
> To determine if the capture layer was being loaded, I used the VK_LOADER_DEBUG environment variable to increase the verbosity of messages from the Vulkan loader. This is the setup I used:
> 
> ```
> export VK_LAYER_PATH=/home/dustin/gfxreconstruct/build/layer/
> export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct
> export VK_LOADER_DEBUG=all
> steam steam://rungameid/20920 | grep -i gfxrecon
> ```
> 
> When the 64-bit layer failed to load, I received the following messages:
> 
> ```
> DEBUG: ReadDataFilesInSearchPaths: Searching the following paths for manifest files: /home/dustin/Projects/gfxreconstruct/build/layer/
> INFO: Found manifest file /home/dustin/Projects/gfxreconstruct/build/layer//VK_LAYER_LUNARG_gfxreconstruct.json, version "1.1.0"
> ERROR: /home/dustin/gfxreconstruct/build/layer/./libVkLayer_gfxreconstruct.so: wrong ELF class: ELFCLASS64
> ```
> 
> When the layer is loaded correctly, the error message should be replaced by messages like:
> 
> ```
> DEBUG: Loading layer library /home/dustin/Projects/gfxreconstruct/build/layer/./libVkLayer_gfxreconstruct.so
> INFO: Insert instance layer VK_LAYER_LUNARG_gfxreconstruct (/home/dustin/Projects/gfxreconstruct/build/layer/./libVkLayer_gfxreconstruct.so)
> ```

Thank you! That seems to have worked, but sadly still does not allow me to capture the part of the game that causes the hang. I start capturing, it hangs but when I go to replay it after force restarting, it seems like the end frames were cut. 

Is there a way to prevent the last part (which is the part causing the hang) to not be cut?

**Comment by dustin-lunarg** [comment]
> Is there a way to prevent the last part (which is the part causing the hang) to not be cut?

You could try setting `GFXRECON_CAPTURE_FILE_FLUSH=1`, which will flush the file stream after each write.  This should prevent data from being lost.

**Comment by dustin-lunarg** [comment]
The build documentation has been updated to include instructions for creating 32-bit builds on Linux.  I'm going to close this issue as I believe the initial problem has been resolved.  If you are still having problems with data loss, feel free to open a new issue.
