### ISSUE TITLE
Build directory overlap with build.py

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/gfxreconstruct#369]
When building with `scripts/build.py`, there are eight flavors of desktop build, all combinations of (`32-bit`|`64-bit`) * (`Release`|`Debug`) * (`cmake`|`script`).  Ideally, they should all build to different directories, so that a developer (or CI) can build and test all versions out of the same source tree without conflict (allowing one CI process to build all at once, and another to test all at once).

Right now there are two issues.  The first is that the 64-bit release cmake build directory `build` conflicts with the 32/64-bit release script build directory `build`.

The second is that on Windows, the script release and debug builds also share that same directory `build`.

The problem for developers is that they will overwrite a build of another flavor, requiring rebuilds that would otherwise not be necessary; and that a developer who doesn't realize that they've overwritten a previous build may not be testing the build they think they are.

The problem for CI is that this blocks the ability to build all flavors in a dedicated build machine and then test as a follow-on step.  (CI doesn't do this currently, but for other reasons we may be moving toward this in the future.)

**Comment by lunarpapillo** [comment]
If and when this is fixed, the CI test scripts for gfxreconstruct will have to be adjusted.

**Comment by xykivo** [comment]
I will take a look at this.

**Comment by lunarpapillo** [comment]
Thanks...

**Comment by dsmolars** [comment]
I think I was able to repro this on my system.
Just to so we're in sync - you want separate output for the cmake build files, and the build output files for each configuration.
This means the build directory structure will be

Release builds:
build/
  <os_name>/
    x64|x86/
      cmake_output/ <- will contains all CMake generated build files
      output/  <- will contains all build output files (exe, dll, .so ...)

Debug build:
dbuild/
  <os_name>/
    x64|x86/
      cmake_output/ <- will contains all CMake generated build files
      output/  <- will contains all build output files (exe, dll, .so ...)

Is this OK?

Note that internally at AMD the debug/release dir resides under the os_dir - e.g. build/linux/debug/x64/...

Thanks

**Comment by lunarpapillo** [comment]
Your proposed structure (build|dbuild)/<os_name>(x64|x86)/(cmake_output|output) does solve the problem, and I'm fine with that.

I think there are alternatives that can preserve more of the AMD default build structure.  For example, moving the CMake build directories to `cmake_build` and `cmake_dbuild` (so there are four top-level build directories possible: `build|dbuild|cmake_build|cmake_dbuild`) would avoid having the CMake files "pollute" the AMD structure.

But I also see the potential advantage in refactoring the CMake structure to allow different OS builds in the same tree (which it doesn't currently do).

So either alternative looks great to me.

Thanks for looking into this.

**Comment by dsmolars** [comment]
I would rather avoid having 4 top level build output directories.
So unless you prefer we put everything in a single build dir (like we do in AMD), I will implement my original suggestion:

Release builds:
build/
<os_name>/
x64|x86/
cmake_output/ <- will contains all CMake generated build files
output/ <- will contains all build output files (exe, dll, .so ...)

Debug build:
dbuild/
<os_name>/
x64|x86/
cmake_output/ <- will contains all CMake generated build files
output/ <- will contains all build output files (exe, dll, .so ...)

**Comment by lunarpapillo** [comment]
Sounds good, thanks.

**Comment by dsmolars** [comment]
Created a pull request for this issue:
https://github.com/LunarG/gfxreconstruct/pull/417

**Comment by dsmolars** [comment]
The pull request CI build fails because the output directory structure has changed (as agreed upon).
See https://github.com/LunarG/gfxreconstruct/runs/967430570

The CI job is looking for artifacts in <config>\<os>\<architecture>\bin (e.g. build\windows\x64\bin\).
However we agreed to change this to <config>\<os>\<architecture>\output\bin
