### ISSUE TITLE
Publishing Android layers binaries to match with SDK

### ISSUE THREAD

**Issue by sfricke-samsung** [LunarG/gfxreconstruct#388]
Would it be possible to release a binary release of the gfxreconstruct layers for Android on Github as the Validation Layers do
https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases

It is important that people are capturing and replaying with the same version of gfxreconstruct and assuming most people will want to use the SDK to replay, it would be very helpful to have the corresponding SDK version Android layers available to quick grab and not have to build as well

**Comment by per-mathisen-arm** [comment]
Why is it important to replay with the same version of gfxreconstruct as was used to trace?

**Comment by sfricke-samsung** [comment]
If the 1.2.142 header comes out with a new function `vkNewFunction` and I build the trace layer with this newer header and then trace an application that includes `vkNewFunction`, the 1.2.141 SDK pre-built binary replay tool will not know what to with `vkNewFunction`

**Comment by dustin-lunarg** [comment]
Binaries for Android are now available: https://github.com/LunarG/gfxreconstruct/releases/tag/sdk-1.2.141.0
