### ISSUE TITLE
kSettingsFilter is set to lunarg_gfxrecon but it should be lunarg_gfxreconstruct

### ISSUE THREAD

**Issue by christophe-lunarg** [LunarG/gfxreconstruct#398]
Hi,

By convention and to be consistent over the ecosystem, the settings filter should be named using the extension name, everything that comes after LAYER. 

Here we see the name is not correct, resulting in vkconfig not being setup:
https://github.com/LunarG/gfxreconstruct/blob/dev/framework/encode/capture_settings.cpp

I am happy to make a pull request to resolve this issue.

Thanks

**Comment by christophe-lunarg** [comment]
This issue should be resolved with https://www.google.com/url?q=https://github.com/LunarG/gfxreconstruct/pull/399

**Comment by dustin-lunarg** [comment]
Closed with #399
