### ISSUE TITLE
Android Trace Replay of Multiple Window Surfaces Fail

### ISSUE THREAD

**Issue by gbergsch** [LunarG/gfxreconstruct#415]
Trying to replay a captured PUBG trace on the capturing platform (Pixel4) results in native window attachment failure. The relevant logcat snippet:
```
07-21 07:45:45.876   600  1909 E BufferQueueProducer: [com.lunarg.gfxreconstruct.replay/android.app.NativeActivity#0] connect: already connected (cur=1 req=1)
07-21 07:45:45.876 14339 14362 E vulkan  : native_window_api_connect() failed: Invalid argument (-22)
07-21 07:45:45.876 14339 14362 F gfxrecon: API call vkCreateAndroidSurfaceKHR returned error value VK_ERROR_NATIVE_WINDOW_IN_USE_KHR that does not match the result from the capture file: VK_SUCCESS.  Replay cannot continue.
07-21 07:45:45.908   824   850 D rlsservice: MonitorDisplayStatus client num 1, display status 1, sensor status 1
07-21 07:45:45.914 14339 14362 V gfxrecon: Replay failed with error message: the requested window is already connected to another VkSurfaceKHR object, or some other non-Vulkan surface object
```

Is there a way to handle multiple android surfaces in GFXReconstruct? Perhaps an option to select only one to view during replay (with other commands dropped)?

**Comment by dustin-lunarg** [comment]
We currently can't handle multiple surfaces for Android replay.  I'll look at adding support for this.

**Comment by gbergsch** [comment]
To clarify, the support you'll look at adding is to enable multiple surfaces or to select only one to render?

**Comment by dustin-lunarg** [comment]
I'll look into both options.  Ultimately we want to be able to support multiple surfaces, but an option to select only one to render may serve as an intermediate solution that could be implemented quickly.

I think it would be possible to add an option that designates one surface to be treated as a native window surface, converting the other surfaces to headless surfaces, with minimal changes.

We can also try an intermediate solution where we create and reuse a single surface/swapchain for Android.
