### ISSUE TITLE
vkSetDebugUtilsObjectNameEXT crashes during recording

### ISSUE THREAD

**Issue by llatta** [LunarG/gfxreconstruct#461]
Looks like vkSetDebugUtilsObjectNameEXT is not implemented in the capture layer and I get crashes in the NVIDIA driver when calling it, presumably because the passed in object pointer is not unwrapped to the underlying object that the driver knows.

This was reproduced with the gfxreconstruct layer of the 1.2.154.1 SDK on Windows.

Thanks for looking into it!

**Comment by dustin-lunarg** [comment]
This should be fixed in the latest dev branch.  It was addressed with #449, in response to issue #446.

**Comment by llatta** [comment]
I can confirm this doesn't crash when making a build from latest dev branch. Closing. Thanks!
