### ISSUE TITLE
vkCmdBuildAccelerationStructureKHR crashes in the recording layer

### ISSUE THREAD

**Issue by llatta** [LunarG/gfxreconstruct#462]
Tried to make a recording of raytracing function calls and immediately get a crash on vkCmdBuildAccelerationStructureKHR as it is not unwrapping the passed in command buffer to a type the underlying layer understands. Looking in the code there is a TODO in CmdBuildAccelerationStructureKHR in framework\encode\custom_vulkan_api_call_encoders.cpp.

This was with latest dev branch (commit 0837ff0) on Windows.

Thanks for looking into it!

**Comment by dustin-lunarg** [comment]
Capture of the ray tracing API is now supported, so this issue should be resolved.
