### ISSUE TITLE
[gfxrecon] ERROR - fopen(lutris_20201225T114532.gfxrecon, wb) failed (errno = 13)

### ISSUE THREAD

**Issue by reactormonk** [LunarG/gfxreconstruct#486]
I'm trying to trace a program launched via lutris. I'm running the capture via

```gfxrecon-capture -o lutris.gfxrecon $(which lutris)```

in a new folder called `/tmp/capture`.

Running the application itself works fine, but as soon as run the program inside lutris, I get

```
Initial process has started with pid 179996
Start monitoring process.
esync: up and running.
info:  Game: PathOfExile_x64.exe
info:  DXVK: v1.7.3-4-g03f11baf
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
[gfxrecon] INFO - Settings Loader: Found option "GFXRECON_CAPTURE_FILE" with value "lutris.gfxrecon"
[gfxrecon] ERROR - fopen(lutris_20201225T114532.gfxrecon, wb) failed (errno = 13)
[gfxrecon] FATAL - Failed to initialize TraceManager
err:   DxvkInstance::createInstance: Failed to create Vulkan 1.1 instance
```

strace of the call:

```
188379 openat(AT_FDCWD, "lutris_20201225T115139.gfxrecon", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 23
```

According to the manpage:

> If pathname is relative and dirfd is the special value AT_FDCWD, then pathname is interpreted relative to the current working directory of the calling process (like open(2)). 

So I'm guessing that's relative to `lutris` working dir. Passing `gfxrecon` an absolute path works as expected.

**Comment by dustin-lunarg** [comment]
As you guessed, it is a relative path issue.  The gfxrecon-capture script provides an unmodified version of the specified filename to the GFXReconstruct capture layer, which is really a DLL/shared object that is loaded by the process being captured.  So a relative file path would be relative to the working directory of the process being captured.  

It would probably make sense for gfxrecon-capture to convert relative paths to absolute paths, relative to the gfxrecon-replay script's working directory, before setting up the capture layer.
