### ISSUE TITLE
page_guard_manager.cpp:113:28: error: size of array ‘s_alt_stack’ is not an integral constant-expression   113 | static uint8_t s_alt_stack[SIGSTKSZ];

### ISSUE THREAD

**Issue by NTMan** [LunarG/gfxreconstruct#545]
```
$ mkdir build && cd build/ && cmake ../
-- The C compiler identification is GNU 11.1.1
-- The CXX compiler identification is GNU 11.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Vulkan Header = /home/mikhail/packaging-work/git/gfxreconstruct/external/Vulkan-Headers/include/vulkan/vulkan_core.h
-- Detected Vulkan Version 1.2.176
-- Found LZ4: /usr/lib64/liblz4.so  
-- Found ZSTD: /usr/lib64/libzstd.so  
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-keysyms.so;/usr/lib64/libX11-xcb.so  
-- Found WAYLAND: /usr/lib64/libwayland-client.so  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib64/libX11.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for clock_gettime in c
-- Looking for clock_gettime in c - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mikhail/packaging-work/git/gfxreconstruct/build

$ make
[  1%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/argument_parser.cpp.o
[  2%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/file_output_stream.cpp.o
[  3%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/file_path.cpp.o
[  4%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/hash.cpp.o
[  5%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/image_writer.cpp.o
[  6%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/keyboard.cpp.o
[  7%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/logging.cpp.o
[  8%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/lz4_compressor.cpp.o
[  9%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/zlib_compressor.cpp.o
[ 10%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/zstd_compressor.cpp.o
[ 11%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/memory_output_stream.cpp.o
[ 12%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/monotonic_allocator.cpp.o
[ 13%] Building CXX object framework/util/CMakeFiles/gfxrecon_util.dir/page_guard_manager.cpp.o
In file included from /usr/include/signal.h:328,
                 from /home/mikhail/packaging-work/git/gfxreconstruct/framework/util/platform.h:52,
                 from /home/mikhail/packaging-work/git/gfxreconstruct/framework/util/logging.h:28,
                 from /home/mikhail/packaging-work/git/gfxreconstruct/framework/util/page_guard_manager.cpp:27:
/home/mikhail/packaging-work/git/gfxreconstruct/framework/util/page_guard_manager.cpp:113:28: error: size of array ‘s_alt_stack’ is not an integral constant-expression
  113 | static uint8_t s_alt_stack[SIGSTKSZ];
      |                            ^~~~~~~~
make[2]: *** [framework/util/CMakeFiles/gfxrecon_util.dir/build.make:244: framework/util/CMakeFiles/gfxrecon_util.dir/page_guard_manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:384: framework/util/CMakeFiles/gfxrecon_util.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by bradgrantham-lunarg** [comment]
Issue introduced with glibc 2.34, on Linux SIGSTKSZ now equates to a syscall

**Comment by SteveEbey73742** [comment]
so, since this also affects the vulkan sdk, and I can not compile the sdk, because of this bug, can I get an estimate, as to a resolution.

**Comment by bradgrantham-lunarg** [comment]
If `gfxreconstruct` is a blocker for you, I recommend not building `gfxreconstruct` in the SDK.  It should be possible to run `vulkansdk` with the parts of the SDK to build as individual parameters instead of `all`.

**Comment by SteveEbey73742** [comment]
@bradgrantham-lunarg  Can you tell me what to build, that does not use gfxreconstruct?

**Comment by bradgrantham-lunarg** [comment]
At the moment I'm not at a CL in which I can run the script but I believe you can build all the other components explicitly, something like `vulkansdk glslang loader layers tools lunarg-tools shaderc spirvtools spirvcross spirv-reflect dxc vulkan-extensionlayer`.

`vulkansdk help` provides a message saying something similar.

**Comment by bradgrantham-lunarg** [comment]
@NTMan , @SteveEbey73742 , if you would like to try out #624 , that PR will hopefully fix your compile issue.  It won't be incorporated into an SDK release for a few months if it's merged with the `dev` branch but we can start making sure it solves the compilation error introduced with glibc 2.34.

**Comment by NTMan** [comment]
After applying this PR the build breaks with another error https://pastebin.com/M8P6Sxd0

**Comment by bradgrantham-lunarg** [comment]
That sounds a lot like an out-of-date `Vulkan-Headers` submodule.  Could you try "git submodule update"?

**Comment by NTMan** [comment]
> That sounds a lot like an out-of-date `Vulkan-Headers` submodule. Could you try "git submodule update --recursive"?

Thanks. Now all fine. https://pastebin.com/7AeLc463

**Comment by zmike** [comment]
This is a problem for anyone on Fedora 35.

**Comment by bradgrantham-lunarg** [comment]
@zmike , if you would like to try out #624 , that PR will hopefully fix compilation on Fedora 35. It won't be incorporated into an SDK release for a few months once it's merged with the dev branch but we can start making sure it solves the compilation error introduced with glibc 2.34.

**Comment by zmike** [comment]
I did try that out and it works fine. I'm using gfxr from git, so this is ok for me. I just wanted to post and add another data point.

**Comment by bradgrantham-lunarg** [comment]
@SteveEbey73742 Please make sure you've updated the Vulkan-Headers submodule.  If you made a fresh clone, I think that command `git submodule update --init --recursive` should do it.

**Comment by SteveEbey73742** [comment]
After running that command, then compiling vulkansdk gfxreconstruct 

In file included from /usr/include/signal.h:328,
                 from /home/steve/vulkan/1.2.198.1/source/gfxreconstruct/framework/util/platform.h:52,
                 from /home/steve/vulkan/1.2.198.1/source/gfxreconstruct/framework/util/logging.h:28,
                 from /home/steve/vulkan/1.2.198.1/source/gfxreconstruct/framework/util/page_guard_manager.cpp:27:
/home/steve/vulkan/1.2.198.1/source/gfxreconstruct/framework/util/page_guard_manager.cpp:113:28: error: size of array ‘s_alt_stack’ is not an integral constant-expression
  113 | static uint8_t s_alt_stack[SIGSTKSZ];
      |                            ^~~~~~~~

**Comment by bradgrantham-lunarg** [comment]
@SteveEbey73742 - you'll need to check out the branch from #624 with `git checkout brad-fix-545` so that you're compiling `gfxreconstruct` with the fix applied.
