### ISSUE TITLE
Assertion hit when trying to trace vkd3d-proton

### ISSUE THREAD

**Issue by Oschowa** [LunarG/gfxreconstruct#551]
gfxrecon version: v0.9.8
OS: Arch Linux
Driver: Mesa recent main

When trying to trace content running with [vkd3d-proton v2.4](https://github.com/HansKristian-Work/vkd3d-proton) with gfxrecon, I hit the following assertion:  
```
src/gfxreconstruct/framework/encode/vulkan_state_tracker.cpp:275: void gfxrecon::encode::VulkanStateTracker::TrackEndRenderPass(VkCommandBuffer): Assertion `attachment_count <= render_pass_wrapper->attachment_final_layouts.size()' failed.
fish: Job 1, 'VK_INSTANCE_LAYERS="VK_LAYER_LU…' terminated by signal SIGABRT (Abort)
```

This happens both with d3d12 games (tested DEATH STRANDING and Scarlet Nexus on Proton Experimental), as well as with the `gears` demo app from vkd3d-proton.
  
To reproduce:
- clone the vkd3d-proton: `git clone --recurse-submodules https://github.com/HansKristian-Work/vkd3d-proton`
- configure with `meson -D enable_extras=true`
- build and then try to trace the resultion `gears` program with gfxrecon

**Comment by mohanku** [comment]
Seeing same assert and crash in some android apps like:
https://play.google.com/store/apps/details?id=com.MoodGames.QueenBee&hl=en_US&gl=US
https://play.google.com/store/apps/details?id=com.linear.beltit&hl=en_US&gl=US
 https://play.google.com/store/apps/details?id=com.nagastudio.giant.monster.run&hl=en_US&gl=US

**Comment by patrick-lunarg** [comment]
Currently I cannot repro this issue with the `gears` demo included with `vkd3d-proton`.

`gfxrecon` latest `dev` branch (as of 9 Sept 2021)
Arch Linux 2021.09.01
AMD RX 6800 XT
Mesa RADV driver

Tried with both `vkd3d-proton` `v2.4` and the latest `master` branch (as of 9 Sept 2021)...couldn't repro with either.

@Oschowa do you have any more info that might help me repro?

Thanks

**Comment by Oschowa** [comment]
It turns out i'm also only hitting this assert when using `GFXRECON_CAPTURE_TRIGGER="F12"`, without the capture trigger it seems to work fine.

**Comment by patrick-lunarg** [comment]
That's interesting...Ok, I'll take a look at that.
Thanks

**Comment by patrick-lunarg** [comment]
@Oschowa the issue seems to be a missing handler for `VkRenderPassCreateInfo2`. 
There should be a fix available soon to enable triggering trimmed capture while using Proton.

**Comment by bradgrantham-lunarg** [comment]
To add a little more detail, we handle capturing and replay of `RenderPass2`.  My guess is that's why capture without trimming works.  We don't appear to currently handle tracking the associated state for `RenderPass2` properly, and that's why we hit that assertion.

**Comment by patrick-lunarg** [comment]
@Oschowa PR #625 has been merged to `dev`.  I think it should address this issue.  Can you confirm whether or not it clears this for you?

**Comment by Oschowa** [comment]
I can confirm that recording a triggered capture seems to work fine now, thanks. However, I've been unable to successfully replay a capture taken from any vkd3d-proton application, be it the `gears` demo or an actual game. Replaying either crashes with device lost errors or just hangs the GPU with both RADV and the proprietary vulkan dirver. But since this is probably out of scope of this issue, I'll close this.

**Comment by bradgrantham-lunarg** [comment]
> I can confirm that recording a triggered capture seems to work fine now, thanks. However, I've been unable to successfully replay a capture taken from any vkd3d-proton application [...] Replaying either crashes with device lost errors or just hangs the GPU with both RADV and the proprietary vulkan dirver

@Oschowa - do you have time to open another issue stating this?  I wasn't able to replay trimmed output from vkd3d gears, but I could replay a non-trimmed capture.  Can you replay non-trimmed captures?
