### ISSUE TITLE
"Flickering" corruption and/or images of previous runs when replaying a trace of a vulkan sample

### ISSUE THREAD

**Issue by johnzupin** [LunarG/gfxreconstruct#587]
# Hardware

* AMD RX 6800 XT

# Software

* Ubuntu 21.04
* Mesa 21.2.2
* Sascha Willem's Vulkan Samples (https://github.com/SaschaWillems/Vulkan) 
* Gfxreonstruct PR #579

# Description of the problem:

I was testing PR #579 out on Ubuntu 21.04 using Wayland (I think it's technically XWayland?). I'm able to capture and replay traces but I'm seeing something funny. After recapturing Sacha Willem's `computecullandlod` trace, I'm seeing flashes of what looks like junk in the buffer from a previous run of another sample. Most of the time it looks like some sort corruption for one frame length, but if I run the `computecloth` sample (note I'm running the sample, not replaying a trace of it), sometimes images can clearly be seen of that `computecloth` sample during replay of the captured trace.

**Comment by bradgrantham-lunarg** [comment]
May be related to #583 and may be affected by #608

**Comment by johnzupin** [comment]
I'm unable to replicate this issue on the current dev branch (`v0.9.11-15-gb47e1ad`). Closing.
