### ISSUE TITLE
[build] not finding compression libraries should fail, and CMake variables should make libraries optional

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#610]
Recently we had a test SDK build that accidentally packaged `gfxreconstruct` with no compression libraries.  CMake did not return a failure error code (i.e. the exit code was 0) but prerequisites were not found.
```
-- Could NOT find LZ4 (missing: LZ4_LIBRARY LZ4_INCLUDE_DIR) 
-- Could NOT find ZSTD (missing: ZSTD_LIBRARY ZSTD_INCLUDE_DIR)
```
These prerequisites are optional (i.e. the keyword `REQUIRED` is not passed to `find_package`).
The conclusion of an internal discussion is that those libraries should probably be `REQUIRED` by default, but allowed to be optional if the user specifies that it be so.  Perhaps those would be CMake variables, e.g. `LZ4_OPTIONAL` as conditionals for an if-else.

**Comment by fabian-lunarg** [comment]
@bradgrantham-lunarg  
should we address `ZSTD` in a similar way or leave it with only `LZ4` mandatory+opt-out ?

**Comment by bradgrantham-lunarg** [comment]
Yes, I think that's a great idea!
