### ISSUE TITLE
VkDeviceSize is printed as as Unhandled VkFormatFeatureFlagBits2KHR in toascii

### ISSUE THREAD

**Issue by ghost** [LunarG/gfxreconstruct#612]
In this toascii output, `memoryOffset` is output as `Unhandled VkFormatFeatureFlagBits2KHR`.
The output should be the integer value of the `VkDeviceSize` `memoryOffset`.

```
"[50]vkBindImageMemory": {
    "return": "VK_SUCCESS",
    "device": "0x0x4",
    "image": "0x0x15",
    "memory": "0x0x16",
    "memoryOffset": Unhandled VkFormatFeatureFlagBits2KHR
}
```

**Comment by mikes-lunarg** [comment]
I can reproduce this on Windows too, VS2019 and VS2022:
```
"[67]vkBindBufferMemory": {
    "return": "VK_SUCCESS",
    "device": "0x0000000000000005",
    "buffer": "0x000000000000001D",
    "memory": "0x000000000000001E",
    "memoryOffset": Unhandled VkFormatFeatureFlagBits2KHR
},
```

**Comment by patrick-lunarg** [comment]
> I can reproduce this on Windows too, VS2019 and VS2022:
> 
> ```
> "[67]vkBindBufferMemory": {
>     "return": "VK_SUCCESS",
>     "device": "0x0000000000000005",
>     "buffer": "0x000000000000001D",
>     "memory": "0x000000000000001E",
>     "memoryOffset": Unhandled VkFormatFeatureFlagBits2KHR
> },
> ```

Gotcha...I've updated the description...thanks

**Comment by bradgrantham-lunarg** [comment]
We investigated briefly today and the consensus is that this is occurring because `VkFlags64` is a typedef from `uint64_t` and `VkFormatFeatureFlagBits2KHR` is a typedef from `VkFlags64`, and template specialization doesn't differentiate through typedefs.  So `uint64_t `and every other typedef from it go through the only specialization of a `uint64_t` type, `ToString<VkFormatFeatureFlagBits2KHR>` in `framework/generated/generated_vulkan_enum_to_string.cpp`.

Possible fix is generating named functions rather than template specializations.

**Comment by bradgrantham-lunarg** [comment]
The specialization `std::string ToString<VkFormatFeatureFlagBits2KHR>` first showed up in 27c015452970bd8f3a45ddd769a88608cdb0d99e.

**Comment by andrew-lunarg** [comment]
I am seeing reasonable values for `vkBindImageMemory`  in the attached UE on Android trace.
[gfxrecon_capture_20220824T095019.gfxr.zip](https://github.com/LunarG/gfxreconstruct/files/9462558/gfxrecon_capture_20220824T095019.gfxr.zip)


```
...
"[601]vkBindImageMemory": {
    "return": "VK_SUCCESS",
    "device": "0x40",
    "image": "0x6e",
    "memory": "0x53",
    "memoryOffset": 1408
},
...
"[618]vkBindImageMemory": {
    "return": "VK_SUCCESS",
    "device": "0x40",
    "image": "0x71",
    "memory": "0x53",
    "memoryOffset": 2560
},
...
```

Also for `vkBindBufferMemory`:

```
"[74]vkBindBufferMemory": {
    "return": "VK_SUCCESS",
    "device": "0x3",
    "buffer": "0x11",
    "memory": "0xf",
    "memoryOffset": 999424
},

"[80]vkBindBufferMemory": {
    "return": "VK_SUCCESS",
    "device": "0x3",
    "buffer": "0x13",
    "memory": "0xf",
    "memoryOffset": 2048000
},

"[489]vkBindBufferMemory": {
    "return": "VK_SUCCESS",
    "device": "0x40",
    "buffer": "0x43",
    "memory": "0x44",
    "memoryOffset": 0
},
...
```


Does someone have a repro trace?

**Comment by andrew-lunarg** [comment]
The memory offsets are not a problem anymore.
I've moved the 64 bit enums to their own issue: https://github.com/LunarG/gfxreconstruct/issues/786
