### ISSUE TITLE
toascii prints VK_NULL_HANDLE for handle and handle arrays that is not NULL in Vulkan structs

### ISSUE THREAD

**Issue by locke-lunarg** [LunarG/gfxreconstruct#617]
```
"[73]vkGetBufferDeviceAddressEXT": {
    "return": "Unhandled VkFormatFeatureFlagBits2KHR",
    "device": "0x0x5",
    "pInfo": {
        "sType": "VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO",
        "pNext": null,
        "buffer": "VK_NULL_HANDLE"
    }
```
But `buffer` should not be `VK_NULL_HANDLE`. The reason is in toascii, it should have gotten struct data by `GetMetaStructPointer()`, instead `GetPointer()`. `GetMetaStructPointer()` could get the original struct data that's from .gfxr file.`GetPointer()` is for replay. Some data, like handle, is 0 before it's be replaced.

The problem affects the output of all `VkHandle`s which are part of a Vulkan struct. It does not affect direct parameters of functions. We generate `ToString()` functions for one struct with a directly embedded array of handles: `VkPhysicalDeviceGroupProperties`, 16 with a pointer to an array of handles, and 91 with single handles embedded within them. This affects a total of 106 structs.

For example, from a trace of the Khronos sample hello_triangle:

`VkFramebufferCreateInfo` shows a null render pass handle and also a missing pointer to an array of attachment handles:

```c++
"[59]vkCreateFramebuffer": {
    "return": "VK_SUCCESS",
    "device": "0x6",
    "pCreateInfo": {
        "sType": "VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO",
        "pNext": null,
        "flags": 0,
        "renderPass": "VK_NULL_HANDLE", // <---------- Missing handle
        "attachmentCount": 1, // <---------- Count is one, not zero
        "pAttachments": [],   // <---------- Missing handles
        "width": 1280,
        "height": 720,
        "layers": 1
    },
    "pAllocator": null,
    "[out]pFramebuffer": "0x1d"
},
```
In another hello_triangle example, the arrays of handles of command buffer handles and semaphore handles passed to `vkQueueSubmit` via a struct are empty even though their corresponding counts say they are not.
```c++
"[76]vkQueueSubmit": {
    "return": "VK_SUCCESS",
    "queue": "0x7",
    "submitCount": 1,
    "pSubmits": [
        {
            "sType": "VK_STRUCTURE_TYPE_SUBMIT_INFO",
            "pNext": null,
            "waitSemaphoreCount": 1,  // <---------- One semaphore
            "pWaitSemaphores": [],    // <---------- Missing handles
            "pWaitDstStageMask": [
                1024
            ],
            "commandBufferCount": 1,
            "pCommandBuffers": [],    // <---------- Missing handles
            "signalSemaphoreCount": 1,
            "pSignalSemaphores": []   // <---------- Missing handles
        }
    ],
    "fence": "0xc"
},
``` 

In the one case of a struct with an array of handles directly embedded in it, rather than pointed to, the length of the array is correctly represented but the elements of it are null handles:
```c++
"[20]vkEnumeratePhysicalDeviceGroups": {
    "return": "VK_SUCCESS",
    "instance": "0x1",
    "[out]pPhysicalDeviceGroupCount": 2,
    "[out]pPhysicalDeviceGroupProperties": []
},
"[21]vkEnumeratePhysicalDeviceGroups": {
    "return": "VK_SUCCESS",
    "instance": "0x1",
    "[out]pPhysicalDeviceGroupCount": 2,
    "[out]pPhysicalDeviceGroupProperties": [
        {
            "sType": "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES",
            "pNext": null,
            "physicalDeviceCo"physicalDeviceCount": 1,unt": 1,
            // This array is embedded in the struct directly and is 32 elements long
            // but only the first element is populated:
            // ("physicalDeviceCount": 1 above tells us that)
            "physicalDevices": [
                VK_NULL_HANDLE // <------------------------------- Missing handle
            ],
            "subsetAllocation": 0
        },
        {
            "sType": "VK_STRUCTURE_TYPE_APPLICATION_INFO",
            "pNext": null,
            "physicalDeviceCount": 1,
            "physicalDevices": [
                VK_NULL_HANDLE
            ],
            "subsetAllocation": 0
        }
    ]
}
```

**Comment by bradgrantham-lunarg** [comment]
including vkCreateImageView -> VkImageCreateInfo -> image

**Comment by panos-lunarg** [comment]
I see the same happening with `VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO` in `vkAllocateMemory`
Buffer is reported as `VK_NULL_HANDLE` from `gfxrecon-toascii` but when trying to assert this with printf'ing it in real time it was proven to be wrong 
```
"[61]vkAllocateMemory": {
    "return": "VK_SUCCESS",
    "device": "0x3",
    "pAllocateInfo": {
        "sType": "VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO",
        "pNext": {
            "sType": "VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO",
            "pNext": {
                "sType": "VK_STRUCTURE_TYPE_IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID",
                "pNext": null,
                "buffer": "0x0"
            },
```

**Comment by andrew-lunarg** [comment]
> I see the same happening with `VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO`

Thanks! I'll look out for that too. What app was the trace from?

**Comment by panos-lunarg** [comment]
Fortnite and i think gfxbench too

**Comment by bradgrantham-lunarg** [comment]
I think you'll see this behavior in any Vulkan handle type that is within a struct, both a VK struct and a bare struct.  You won't see it from any handle that's passed as a parameter.

**Comment by ahcox** [comment]
> I think you'll see this behavior in any Vulkan handle type that is within a struct, both a VK struct and a bare struct. You won't see it from any handle that's passed as a parameter.

Yes. It is every struct with a handle embedded. Locke's original description covers why: `GetMetaStructPointer()` returns a wrapper for the struct which has our representation of handle values correctly for each handle, but the template function which dispatches to the right `ToString()` for parameters which are pointers to structs uses `GetPointer()`, which points to the native Vulkan struct which had all its handles explicitly set to null by the generated decode functions which read it from the trace file. 

This gives us two options:

1. Stuff the decoded handle IDs into the handles in the raw structs with type coercion and let the current code path continue.
2. Provide `ToString()` functions for the Decoded versions of the structs.

I've manually established 1. Seems to work but I think 2. Is cleaner so I want to try that before rushing to working on code gen.

**Comment by bradgrantham-lunarg** [comment]
I think #2 sounds better to me.  In fact the `ToString` functions for the `GetPointer` structs probably should go away.  The new `ToString` functions may end up printing some members from the meta struct and some others from the decoded struct.

**Comment by andrew-lunarg** [comment]
Very rough sketches at the two approaches mentioned above, proven with manually-written code that needs to be replicated for all structs in the Python code generation:
1. https://github.com/andrew-lunarg/gfxreconstruct/tree/andy-fix-617-001-coerce-and-copy-metastruct-handles-into-raw-vk-structs
2. https://github.com/andrew-lunarg/gfxreconstruct/tree/andy-fix-617-002-generate-ToString-for-decoded-structs-with-handle-members

I'll continue with approach 2. I still need to establish how `vkEnumeratePhysicalDeviceGroups` should be handled.
