### ISSUE TITLE
Impossible to capture Baldur's Gate 3

### ISSUE THREAD

**Issue by hakzsam** [LunarG/gfxreconstruct#622]
Capturing Baldur's Gate 3 (native Vulkan) is so slow that it can't reach the main menu, even after long minutes. Is gfxreconstruct hitting a pathological case?

Tested with 2fd27a2 (origin/dev).

**Comment by patrick-lunarg** [comment]
Hey @hakzsam,

It's certainly possible that gfxreconstruct is hitting a pathological case.
What hardware are you using?

**Comment by hakzsam** [comment]
I'm using a Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] with RADV (mesa-git 9a001ca41fb).

**Comment by dgraves** [comment]
Setting `GFXRECON_PAGE_GUARD_PERSISTENT_MEMORY=1` might improve capture performance for this title.

The issue may be related to the default method used to track modifications to mapped memory, which does not perform well when large memory ranges are mapped and unmapped frequently.  Some additional documentation can be found here: https://github.com/LunarG/gfxreconstruct/blob/dev/USAGE_desktop.md#selecting-settings-for-the-page_guard-memory-tracking-mode

**Comment by bradgrantham-lunarg** [comment]
Hi, @hakzsam , have you had any success with setting `GFXRECON_PAGE_GUARD_PERSISTENT_MEMORY=1` to improve performance?

**Comment by hakzsam** [comment]
Sorry for the delay.

I can confirm that setting `GFXRECON_PAGE_GUARD_PERSISTENT_MEMORY=1` improve recording performance considerably. The trace also replays fine. Tested with same config as my first post.

Feel free to close this issue, thanks!

**Comment by bradgrantham-lunarg** [comment]
No problem, @hakzsam , thanks for the update!  And thanks, @dgraves for the insight!
