### ISSUE TITLE
wrong pointer is printed for output parameters

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#646]
toascii is printing the consumer output pointer, rather than the pointer that was stored in the capture file.

### Repro

By diffing the output of two runs of of the same build of `toascii` on the same capture file, a bunch of pointers show up with different values. The offending pointers include struct members as well as function output parameters. If their values came from the trace files they would not differ.

![Screenshot from 2022-08-30 15-56-03](https://user-images.githubusercontent.com/105252583/187473273-c45ac81a-7728-4386-b0b3-e2bab72211c4.png)

### Investigation

The `VulkanAsciiConsumer` process function for Vulkan calls using void data pointers plumbs through to this `ToString` function in `custom_vulkan_ascii_consumer.h`:

```
template <typename T>
inline std::string DataPointerDecoderToString(const T& pObj)
{
    // NOTE : Currently we just output the integer value of data void pointers, for
    //  fields that use a PointerDecoder<> we output the address of the decoder
    //  itself...this isn't terribly useful, but the capture time address wouldn't
    //  be a terribly useful thing anyway.  There are structures that have data
    //  fields that can be interpreted correctly...if we want to output interpreted
    //  void pointer data we can implement custom handlers for those structures.
    return "\"" + util::PtrToString(pObj) + "\"";
}
```
`const T& pObj` in this case is a reference to a const pointer to a `decode::PointerDecoder<unsigned char, unsigned char>`.   _Note, that's a lot of `NOTE`._

That calls through to:
```
template <typename PtrType>
inline std::string PtrToString(PtrType* ptr)
{
    std::stringstream strStrm;
    strStrm << "0x" << std::hex << reinterpret_cast<uintptr_t>(ptr);
    return strStrm.str();
}
```
This function then outputs the address of the `decode::PointerDecoder<unsigned char, unsigned char>` pointed to by `ptr` rather than any representation of the pointer from the trace file stored inside it.

Since the `PointerDecoder` instances whose addresses are output are sitting on the stack in the local frame of a `Decode_vk<SOME_FUNCTION>` function, there are lots of duplicates in a trace of addresses of objects which happen to to be at the same location on the stack at the time they are output.

**Comment by andrew-lunarg** [comment]
Fixed by PR #787
