### ISSUE TITLE
Toascii: Add a default for without --output and a description in USAGE_desktop.md

### ISSUE THREAD

**Issue by locke-lunarg** [LunarG/gfxreconstruct#657]
Could it add a default for without `--output`, like previous version? Also, it needs a description about `--output` in https://github.com/LunarG/gfxreconstruct/blob/dev/USAGE_desktop.md#to-ascii.

**Comment by bradgrantham-lunarg** [comment]
It should work without `--output` now the way it worked previously.  But #656 fixes a bug which may be causing a problem that you're seeing.

**Comment by locke-lunarg** [comment]
Fixed. Thanks
