### ISSUE TITLE
capturing trim ranges is non-deterministic

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/gfxreconstruct#664]
I encountered this issue by accident while investigating a hang.  I've observed the behavior on Windows with NVIDIA graphics; I haven't attempted to reproduce on other platforms.

The attached trace is a retrace (i.e. a captured trace created by replaying the original trace) of `vkcube`:
[gfxr.zip](https://github.com/LunarG/gfxreconstruct/files/8249086/gfxr.zip)

Use that attached trace to create a trimmed trace, setting `VK_LAYER_PATH` to point at any particular GFXR build:
```
> set GFXRECON_CAPTURE_FRAMES=11-31
> set VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct
> set VK_LAYER_PATH=...
> .../gfxrecon-replay.exe --sfa gfxrecon_capture_20220314T172704.gfxr
[gfxrecon] WARNING - Replay tool has detected that the capture layer is enabled
[gfxrecon] INFO - Settings Loader: Found option "GFXRECON_CAPTURE_FRAMES" with value "11-31"
[gfxrecon] INFO - Initializing GFXReconstruct capture layer
[gfxrecon] INFO -   GFXReconstruct Version 0.9.11-dev (dev:2426205)
[gfxrecon] INFO -   Vulkan Header Version 1.3.204
[gfxrecon] INFO - Recording graphics API capture to gfxrecon_capture_frames_11_through_31_20220314T17
5237.gfxr
[gfxrecon] INFO - Finished recording graphics API capture
Total time: 0.324695 seconds
Replay FPS: 307.981336 fps, 0.324695 seconds, 100 frames, framerange 1-100
```
Repeat the above `gfxrecon-replay.exe` command several times, to produce several trimmed traces.

Then examine the sizes of all the created trimmed traces:
```
> dir *.gfxr
 Volume in drive C has no label.
 Volume Serial Number is 4205-A61B

 Directory of C:\Users\lunarg\work\LunarG\gfxreconstruct

03/14/2022  05:27 PM           143,939 gfxrecon_capture_20220314T172704.gfxr
03/14/2022  05:52 PM            58,051 gfxrecon_capture_frames_11_through_31_20220314T175237.gfxr    
03/14/2022  05:54 PM            58,064 gfxrecon_capture_frames_11_through_31_20220314T175436.gfxr
03/14/2022  05:54 PM            58,070 gfxrecon_capture_frames_11_through_31_20220314T175439.gfxr    
03/14/2022  05:54 PM            58,034 gfxrecon_capture_frames_11_through_31_20220314T175441.gfxr    
03/14/2022  05:54 PM            58,067 gfxrecon_capture_frames_11_through_31_20220314T175442.gfxr    
               6 File(s)        434,225 bytes
               0 Dir(s)  3,660,963,663,872 bytes free
```
Note how every trimmed trace has a slightly different size.

Expectation is that all trimmed traces created with the same replay tool, capture layer, original trace, and settings will produce traces of the same size (though possibly different in meta-data, e.g. if the trace includes its capture time).

**Comment by lunarpapillo** [comment]
If it's helpful, I reproduced with:
```
> build\tools\replay\Release\gfxrecon-replay.exe --version
gfxrecon-replay.exe version info:
  GFXReconstruct Version 0.9.11-dev (dev:2426205)
  Vulkan Header Version 1.3.204
```

**Comment by bradgrantham-lunarg** [comment]
Working theory is that individual captures have slightly different data, like timestamps or pointer values.  On compression, those streams of data will result in slightly different compressed file sizes.

**Comment by lunarpapillo** [comment]
Working theory seems to be confirmed; after decompressing each capture with `NONE`, I see:
```
03/14/2022  06:09 PM           845,012 NONE-1.gfxr
03/14/2022  06:10 PM           845,012 NONE-2.gfxr
03/14/2022  06:10 PM           845,012 NONE-3.gfxr
03/14/2022  06:10 PM           845,012 NONE-4.gfxr
03/14/2022  06:11 PM           845,012 NONE-5.gfxr
```

Closing.
