### ISSUE TITLE
SetRayTracingShaderGroupHandlesCommandHeader::data_size may need to be uint64_t

### ISSUE THREAD

**Issue by davidd-lunarg** [LunarG/gfxreconstruct#678]
`SetRayTracingShaderGroupHandlesCommandHeader::data_size` uses `size_t` which means that 32-bit captures will be incompatible with 64-bit replay and vice-versa.

Making this change will break backward compatibility with 32-bit captures that contain `SetRayTracingShaderGroupHandlesCommandHeader` blocks. Alternatively a new block type could be added to fix the issue, leaving the current block type to operate as-is.

**Comment by bradgrantham-lunarg** [comment]
Since this header has been in `gfxreconstruct` for more than a year, my preference is to make a new block type, rather than break any existing captures.

**Comment by bradgrantham-lunarg** [comment]
Although we could have a discussion about whether there will be any 32-bit captures that are using raytracing....

**Comment by panos-lunarg** [comment]
I can't believe this. It's the same on windows. 32bit driver does not expose the ray tracing extensions.
I'm not familiar with windows so I'll post some proof. Shout if you spot something wrong:

The one on the left is the output from `\Windows\System32\vulkaninfo.exe` 
The one on the right is the output from `\Windows\SysWOW64\vulkaninfo-1-999-0-0-0.exe`  

![Screenshot 2022-06-17 165732](https://user-images.githubusercontent.com/104391532/174323711-c281362a-2df6-43a3-aa3e-4eecc544474e.png)

I'll just write a patch and rely on someone else with nvidia hardware testing it for me

**Comment by bradgrantham-lunarg** [comment]
We've established that we don't see any non-experimental 32-bit drivers exporting raytracing.  We also don't seem to have a workable test case for a 32-bit capture even on RADV.  So our judgment call is to simply change the struct parameter.

**Comment by bradgrantham-lunarg** [comment]
Is now `uint64_t` as part of #723
