### ISSUE TITLE
The wrong value is printed for some input pointer parameters

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#683]
E.g. `pCode` in the `VkShaderModuleCreateInfo` passed to `vkCreateShaderModule`  appears to be printing the address of the buffer allocated at decode time to contain the code BLOB read from file.  It should print the original address at capture time.

### Investigation
`VkShaderModuleCreateInfo` provides a good target as it has custom ToString() code rather than generated. Below, I've modified `std::string ToString<decode::Decoded_VkShaderModuleCreateInfo>()` to output some options, starting with the current version which accesses the raw Vulkan struct's `pCode` pointer.
I believe the version we need is the second or third one, depending on whether a decimal number or hex-format number in a string is preferred, since the `address_` member of the base of the `StructPointerDecoder` that these access is decoded directly from the capture file.
```json
"[89]vkCreateShaderModule": {
    "return": "VK_SUCCESS",
    "device": "0x3",
    "pCreateInfo": {
        "sType": "VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO",
        "pNext": null,
        "flags": 0,
        "codeSize": 1512,
        "pCode": "0x5555563230d0",
        "pCode": "0x6e129708f0",    <--- Choice A  [PtrToString(decoded_obj.pCode.GetAddress())]
        "pCode": 472758290672,      <--- Choice B [ToString(decoded_obj.pCode.GetAddress())]
        "pCode": "0x5555563230d0",  [PtrToString(decoded_obj.pCode.GetPointer())]
        "pCode": "0x0"              [PtrToString(decoded_obj.pCode.GetOutputPointer())]
    },
    "pAllocator": null,
    "[out]pShaderModule": "0x18"
},
```

**Comment by andrew-lunarg** [comment]
Fixed by PR https://github.com/LunarG/gfxreconstruct/pull/789
