### ISSUE TITLE
Support device group in synchronization2

### ISSUE THREAD

**Issue by locke-lunarg** [LunarG/gfxreconstruct#693]
Gfxr didn't deal with device group for synchronization2, like QueueSubmit2. We need to figure out if we need to do something for it.

Now, the capturing crashes for device group. When it runs `vkEnumeratePhysicalDeviceGroups`, it runs `EnumeratePhysicalDeviceGroups` in `generated_vulkan_api_call_encoders.cpp` many times. It crashes in `GetInstanceTable(instance)->EnumeratePhysicalDeviceGroups` in the third time. I can't find out the reason why it runs so many times and why it crashes. When it runs `vkEnumeratePhysicalDevices`, it also runs `EnumeratePhysicalDevices` in `generated_vulkan_api_call_encoders.cpp` four times. But it doesn't crash.

**Comment by locke-lunarg** [comment]
After update to VulkanRT-1.3.211.0,  the vkEnumeratePhysicalDeviceGroups crash issue was fixed.

**Comment by bradgrantham-lunarg** [comment]
@locke-lunarg do you think this issue has gone away and should be closed?

**Comment by locke-lunarg** [comment]
Yes. It should be fixed by https://github.com/LunarG/gfxreconstruct/pull/828.
