### ISSUE TITLE
Build of Catch Tests Fails on Ubuntu 19.10

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#695]
When building catch unit test running applications such as `framework/util/test/main.cpp`, a known bug in catch is triggered at `external/catch2/catch.hpp` line 9041 where a non-const value is used to initialise a constexpr variable. The macro `MINSIGSTKSZ` which can expand either to a compile constant or to a call to a function is used.
Its definition in `/usr/include/x86_64-linux-gnu/asm/signal.h` has a comment above it:
> `/* These should not be considered constants from userland.  */`

The latest Catch2 header has fixed this.

**Comment by bradgrantham-lunarg** [comment]
This may be something I could have caught as part of https://github.com/LunarG/gfxreconstruct/pull/624.  Thanks for walking through the instructions.
