### ISSUE TITLE
Fail to replay a trace from Hitman 3

### ISSUE THREAD

**Issue by hakzsam** [LunarG/gfxreconstruct#722]
I have tried to capture a trace of Hitman 3 with c127490 (dev branch) but then it failed to replay with the following output:

```
[gfxrecon] WARNING - Skipping object handle mapping for unsupported external object type processed by vkGetDescriptorSetHostMappingVALVE
[gfxrecon] WARNING - Skipping object handle mapping for unsupported external object type processed by vkGetDescriptorSetHostMappingVALVE
[gfxrecon] WARNING - Skipping object handle mapping for unsupported external object type processed by vkGetDescriptorSetHostMappingVALVE
[gfxrecon] WARNING - Skipping object handle mapping for unsupported external object type processed by vkGetDescriptorSetHostMappingVALVE
[gfxrecon] WARNING - Skipping object handle mapping for unsupported external object type processed by vkGetDescriptorSetHostMappingVALVE
[gfxrecon] WARNING - Skipping unrecognized file block with type 32679
Total time: 1.500958 seconds
Replay FPS: 0.666241 fps, 1.500958 seconds, 1 frame, framerange 1-1
```

The trace is 4.9GiB, so not sure if it's worth uploading it.

**Comment by hakzsam** [comment]
Looks like disabling VALVE_descriptor_set_host_mapping in RADV fixed the replay.

**Comment by bradgrantham-lunarg** [comment]
@hakzsam, is disabling `descriptor_set_host_mapping` a sustainable approach?  (I would assume that it isn't.)

Can you give us some more detail on how to repro so we can look into this?  Thank you!

**Comment by hakzsam** [comment]
It would be better to add support for it I guess but it allowed me to debug a GPU hang with Hitman 3 by disabling the extension in RADV.

For reproducing the issue, you will need recent Mesa and vkd3d-proton, then you should be able to reproduce with any DX12 games (Hitman 3, Deathloop, Cyberpunk, etc) by replaying a captured trace.

**Comment by andrew-lunarg** [comment]
> For reproducing the issue, you will need recent Mesa and vkd3d-proton, then you should be able to reproduce with any DX12 games (Hitman 3, Deathloop, Cyberpunk, etc) by replaying a captured trace.

I assume it would be enough to capture the demo of such a game downloaded from Steam on a Linux platform.
Do you have a version number for the Mesa we need, or will we need to be more recent than the latest release?

**Comment by andrew-lunarg** [comment]
If we made it look to vkd3d-proton like the `VALVE_descriptor_set_host_mapping` extension's feature flag indicated that RADV _didn't_ support it during capture, would that be okay for Valve, or do you need the trace to exercise the RADV codepaths that implement the extension?

**Comment by hakzsam** [comment]
Latest Mesa release with Proton experimental should be enough to reproduce the issue.
