### ISSUE TITLE
CreateHardwareBufferCommandHeader.usage is of the wrong type

### ISSUE THREAD

**Issue by panos-lunarg** [LunarG/gfxreconstruct#745]
`CreateHardwareBufferCommandHeader.usage` is declared as a `uint32_t` while `AHardwareBuffer_Desc.usage` is `uint64_t` (https://developer.android.com/ndk/reference/struct/a-hardware-buffer-desc)

Discovered while digging around our AHB code (haven't seen any case that this is causing any failures yet) and I'm not sure if this is a bug or done so on purpose. From what I see [in the documentation](https://developer.android.com/ndk/reference/group/a-hardware-buffer#group___a_hardware_buffer_1ga47c480435db00c8e88023eea28ccce90) the higher 32bit seem to be used for some non trivial use cases so might not be used that often/at all?

If this is a bug and we want to fix it then this might a be a good opportunity to enforce some compiler flag to catch such kind of errors (narrowing down conversions) 

While the fix should be trivial I guess it will break existing android captures (or apply some logic to detect the difference)

**Comment by andrew-lunarg** [comment]
> If this is a bug and we want to fix it then this might a be a good opportunity to enforce some compiler flag to catch such kind of errors (narrowing down conversions)
:+1:

**Comment by bradgrantham-lunarg** [comment]
Unlike #678, I suspect there are probably existing captures in the wild using that struct.  We know many of them simply won't replay correctly but at least some instances of AHB can be captured and replayed correctly.
So to solve this problem I recommend we deprecate `CreateHardwareBufferCommandHeader`, make a `CreateHardwareBufferCommandHeader2` with `uint64_t`, transition all encoding to the `2` version, and update `DispatchCreateHardwareBufferCommand` and `ProcessCreateHardwareBufferCommand` to take `uint64_t usage`, add an additional FileProcessor clause for the new `CreateHardwareBufferCommandHeader2` and change the existing `CreateHardwareBufferCommandHeader` clause in FileProcessor to cast `usage` up to `uint64_t`.

**Comment by bradgrantham-lunarg** [comment]
Test would include
- replay existing capture with `CreateHardwareBufferCommandHeader`
- take a capture with the new code and verify replay detects and uses `CreateHardwareBufferCommandHeader2` correctly
