### ISSUE TITLE
[Pixel 6] Capturing GLES apps does not seem to work

### ISSUE THREAD

**Issue by panos-lunarg** [LunarG/gfxreconstruct#749]
I've been trying to capture GLES apps on Pixel 6 but it doesn't seem to work. A capture file is created but it seems that the recording stops very early for no apparent reason. For example when trying to capture [a particular app] the capture grows only up until 38Kb and then stops. Nothing in the logcat to indicate what the problem might be.

**Comment by panos-lunarg** [comment]
Ok that was my mistake. Seeing GFXR being engaged fooled me into thinking that ANGLE was activated by default but apparently it needs to be explicitly enabled. Once enabled I can see a big stream of commands now being directed into the capture file.

Unfortunately there is a segmentation fault shorty after starting. Will keep investigating

**Comment by panos-lunarg** [comment]
This looks like the 250 issue
Backtrace hints (function `GrVkGpu::uploadTexDataOptimal`) that that crash takes place when writing page guarded memory.
Setting to `unassisted` "unblocks" things although not for long as https://github.com/LunarG/gfxreconstruct/issues/744 kicks in

**Comment by bradgrantham-lunarg** [comment]
If this is a general ANGLE issue, we can put more detail here.  But I think this is probably related to the client issue discussed offline.

**Comment by panos-lunarg** [comment]
No reason keeping this around. Initially I thought there was something wrong capturing gles apps on android 12 but I was wrong.
