### ISSUE TITLE
Print differences in supported extensions

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#760]
The occasional capture fails with `VK_ERROR_EXTENSION_NOT_PRESENT` but doesn't give any more specific feedback, so the user has to dump the list of requested extensions and then inspect the output of `vulkaninfo` on the replay system to find the difference.

To provide more information, when replay decodes `vkEnumerateDeviceExtensionProperties`, print extensions that were present on capture but are not present on replay.  

Perhaps even store the replayed enumerated extension properties and print only a warning when `vkCreateDevice` is called requesting an extension that isn't available on the device.

I think it's legal to create a device without calling `EnumerateDeviceExtensonProperties`, in which case GFXR doesn't have information from the replayed API stream about the device's supported extensions.  Maybe we should special case `EXTENSION_NOT_PRESENT` and query the device extensions at that time, since replay won't proceed normally at that point anyway.

**Comment by panos-lunarg** [comment]
Done with #1030 and #1221
