### ISSUE TITLE
toascii - from_json - Build a json -> binary converter

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#762]
Being able to loop captures back from the "ascii" json to binary would be a useful robustness shakeout for **toascii** which could be integrated into CI. Currently, we rely on eyeballing a wall of text to spot problems in toascii output.

```

               ┌───────► replay
               │
               │
capture ───► binary ───► json
              file       file                                   
               ▲           │                                 
               │           │                                  
               └───────────┘                

```
## Tests it would allow:
1. Does `binary->json->binary` give bit-identical binary files?
2. Does `json->binary->json` give identical text files?
3. Does `binary->json->binary->replay` give an identical output image to `binary->replay`?

## Other Benefits
1. Allow manual tweaking of traces for debugging Vulkan drivers.
1. Allow manual tweaking of traces for debugging gfxr replay.

## Implementation Notes
* It does not need to be fast. We would not expect external users to run it.

## Task Dependencies
* We need to start on a JSON format before we begin this, although they might naturally go hand in hand, with this tool helping verify that the json output is correct and usable for tools in general to work with.
                    
## Related Ideas
1. From Brad: _"Another way to validate toascii output would be to compare the output to apidump's JSON output. One could take a capture (so the stream could be reproduced if necessary), then replay with both GFXR and apidump JSON. There would need to be a script to convert from one to the other but I think it could be really helpful."_

**Comment by werman** [comment]
> We would not expect external users to run it.

Even if not fast, it could be useful in debugging particularly nasty issues (mostly GPU hangs). So as a driver developer I would highly welcome the ability to edit a trace.

**Comment by bradgrantham-lunarg** [comment]
We expect users to modify binary capture files by implementing their own tool and derived `Consumer`.  Making a judgment call that we won't support this path.  (However, perhaps we could have a `VulkanReplayConsumer` that also took a map of edits to fields so that a user could manually tweak a capture for replay.)
