### ISSUE TITLE
Update Visual Studio versions required to build

### ISSUE THREAD

**Issue by davidd-lunarg** [LunarG/gfxreconstruct#763]
https://github.com/LunarG/gfxreconstruct/blob/dev/BUILD.md#windows-development-environment-requirements lists 2015, 2017, and 2019. Are 2015 and 2017 still supported? Is 2022 supported?

**Comment by bradgrantham-lunarg** [comment]
VS 2017 builds successfully debug, captures `vkcube`, and replays an existing capture taken with build using VS 2019.

**Comment by bradgrantham-lunarg** [comment]
Since the SDK mandates Visual Studio 2017 or later, we won't test VS 2015.

**Comment by bradgrantham-lunarg** [comment]
VS 2022 builds successfully in Debug and Release, captures `vkcube`, and replays an existing capture taken with build using VS 2019.
