### ISSUE TITLE
toascii - Use JSON5 for Output

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#764]
Edit: We are probably not going to pursue this since we don't want to raise to bar for downstream tools that parse our output.

### Real Functional Benefits
* Better numeric support:
  * Numbers may be [IEEE 754](http://ieeexplore.ieee.org/servlet/opac?punumber=4610933) positive infinity, negative infinity, and NaN.
    If we try to perfectly round trip back to binary at some stage, we will need to preserve this bad data in our input.
  * Numbers may be hexadecimal. _\[Good for pointers / addresses without requiring downstream tools to convert hex values out of strings themselves.\]_

### Nice-to-Have Benefits
We could lose a whole host of double-quotes and worry less about trailing commas:

```
{
  // comments
  unquoted: 'and you can quote me on that',    <----------------- Easier on eyes
  singleQuotes: 'I can use "double quotes" here',
  lineBreaks: "Look, Mom! \
No \\n's!",
  hexadecimal: 0xdecaf,   <----------- We like hex
  leadingDecimalPoint: .8675309, andTrailing: 8675309.,
  positiveSign: +1,
  trailingComma: 'in objects', andIn: ['arrays',],   <------- Less finicky generation
  "backwardsCompatible": "with JSON",
}
```

### More info:
* https://json5.org/
* https://spec.json5.org/

**Comment by bradgrantham-lunarg** [comment]
It sounds pretty good (love trailing comma being legal), but I always am concerned about other developers parsing our output.  How is the support level across tools and libraries, like Python `json`, `jq`, `nlohmann::json` and `jsoncpp`?

**Comment by andrew-lunarg** [comment]
> How is the support level across tools and libraries, like Python `json`, `jq`, `nlohmann::json` and `jsoncpp`?

To be assessed when we have time to look at this.

**Comment by andrew-lunarg** [comment]
Closing as one less thing to think about. Feel free to reopen if the numeric benefits outweigh costs to downstream users.
