### ISSUE TITLE
toascii - Move Function Call Ordinals Into Attributes

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#765]
We label each function call node's key with a number. It would be better to have the number be stored under the node as a regular attribute.

From:
```json
"[34]vkEnumeratePhysicalDevices": {
    "return": "VK_SUCCESS",
    "instance": "0x1",
    "[out]pPhysicalDeviceCount": 2,
    "[out]pPhysicalDevices": [
        "0x3",
        "0x4"
    ]
},
"[35]vkGetPhysicalDeviceProperties": {
    "physicalDevice": "0x3",
...
```
To:
```json
"vkEnumeratePhysicalDevices": {
    "sequence": 34,
    "return": "VK_SUCCESS",
    "instance": "0x1",
    "[out]pPhysicalDeviceCount": 2,
    "[out]pPhysicalDevices": [
        "0x3",
        "0x4"
    ]
},
"vkGetPhysicalDeviceProperties": {
    "sequence": 35,
    "physicalDevice": "0x3",
...
```

Where the name `"sequence"` is open to better suggestions.

Of course, it is confusing to do this if the function has an argument of the same name so the schema might need to be adjusted further, to e.g.:

```json
"vkGetPhysicalDeviceProperties": {
    "sequence": 35,
    "args": {
        "physicalDevice": "0x3",
         ...
    },
    ...
```

If we implement this before [moving to JSONLINES](https://github.com/LunarG/gfxreconstruct/issues/783), we should change the top level of our files from an object to an array, and wrap each call in its own object as otherwise we'll have duplicate keys in that top-level object. The next valid JSON step might look more like this: https://github.com/LunarG/gfxreconstruct/issues/783#issuecomment-1230761285

### Possible Attribute names
* `index`
* `sequence`
* `ordinal`
* `call_number`
*  ...

**Comment by bradgrantham-lunarg** [comment]
100% agreed.

**Comment by andrew-lunarg** [comment]
This was fixed by PR 811: https://github.com/LunarG/gfxreconstruct/pull/811
