### ISSUE TITLE
record and replay Android games from the Google Play store

### ISSUE THREAD

**Issue by pemgithub** [LunarG/gfxreconstruct#780]
Is it expected for gfxreconstruct to record and replay Android games from the Google Play store?

I tried a few but they seem to not work...  This is for GPU research and development.

**Comment by bradgrantham-lunarg** [comment]
Do the games use Vulkan?

Any Vulkan Android app should, in theory, be capture-able by GFXReconstruct.  We have a few known scenarios in which apps cannot be captured.  Unreal Engine games, for example, conflict with our memory write detector ("pageguard") and so GFXR crashes if that's enabled.  

Does the Android log (`adb logcat`) have any lines in them that contain `gfxrecon` or `vulkan` or `Vulkan` and indicate an error?

One thing you could try is running and capturing Android `vkcube`, as a first step, to make sure you have your setup working.

**Comment by bradgrantham-lunarg** [comment]
Android Vulkan games from the Play store can be captured.  Closing this issue.  To get more information, feel free to reopen this issue with more specifics about what you tried and the error condition you saw.  Thanks!
