### ISSUE TITLE
make JSON output be JSONlines, stepping stone to #766

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#783]
Depends on #765 to get the sequence number and function call string into the function call record.

Make toascii output be `jsonlines`.  Each Vulkan command (and later, command block in the capture file) would be a single JSON record, with no newlines so they would be each on one line.  Remove the leading `{` and trailing `}` we have now and remove the `,` we add after each record.

**Comment by andrew-lunarg** [comment]
Would be good to get an attribute (key) in the top level object on each line identifying the line as a Vulkan function call. Then a downstream tool looking out for calls could gracefully skip lines we add later.
E.g.

```
...
{ "type"="call", "index"=11, "name"="vkEnumeratePhysicalDevices", ... }
{ "type"="call", "index"=12, "name"="vkGetPhysicalDeviceProperties", ... }
...
```

**Comment by andrew-lunarg** [comment]
Noting here that our dev branch already has some of what we need in the ability to put each call on one line with the following tiny change:

```
diff --git a/framework/util/to_string.h b/framework/util/to_string.h
index 54fd03e..5487964 100644
--- a/framework/util/to_string.h
+++ b/framework/util/to_string.h
@@ -36,7 +36,7 @@ enum ToStringFlagBits
 {
     kToString_Unformatted = 0,
     kToString_Formatted   = 1,
-    kToString_Default     = kToString_Formatted,
+    kToString_Default     = kToString_Unformatted,
 };
```
This change drops the size of one example 3.7GB toascii output down to 2.6GB.

**Comment by andrew-lunarg** [comment]
This was fixed by PR 811: https://github.com/LunarG/gfxreconstruct/pull/811
