### ISSUE TITLE
Cyberpunk2077 Replay failed with VkImportMemory - vkAllocateMemory returned error value

### ISSUE THREAD

**Issue by illia-a-polishchuk** [LunarG/gfxreconstruct#802]
Reproduced when I tried to replay Cyberpunk 2077 capture

- Mesa main branch with 6c0215eb09e commit
- Ubuntu 20.04.5 LTS
- Proton Experimental
- Intel® Core™ i5-10300H CPU @ 2.50GHz × 8
- Mesa Intel® UHD Graphics (CML GT2)

Steps to reproduce:
1. Download Cyberpunk 2077 from Steam
2. Enable Proton Experimental in Steam settings 
3. Build latest release mesa from main branch (the commit 6c0215eb09e)
4. export VK_ICD_FILENAMES=/home/illia/issues/cyberpunk-7211/mesa/build/share/vulkan/icd.d/intel_icd.x86_64.json
5. export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct
6. export VK_LAYER_PATH=/home/illia/sources/gfxreconstruct/build/layer/:$VK_LAYER_PATH
7. export GFXRECON_CAPTURE_FILE=/home/illia/traces/gfxrecon_capture.gfxr

Try to replay captured file:
`./gfxrecon-replay /home/illia/traces/gfxrecon_capture_20220913T144728.gfxr`

The error appears:
`[gfxrecon] FATAL - API call vkAllocateMemory returned error value VK_ERROR_INVALID_EXTERNAL_HANDLE that does not match the result from the capture file: VK_SUCCESS. Replay cannot continue.`

Vulkan validation error messages:

```
Objects: 1
        [0] 0x555cba6d96d0, type: 3, name: NULL
        VUID_Undefined(ERROR / SPEC): msgNum: 2044605652 - Validation Error: 
        [ VUID_Undefined ] Object 0: handle = 0x555cba6d96d0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x79de34d4 | 
            VkImportMemoryHostPointerInfoEXT: required parameter pHostPointer specified as NULL.
Objects: 1
        [0] 0x555cba6d96d0, type: 3, name: NULL
        VUID-VkMemoryAllocateInfo-pNext-03332(ERROR / SPEC): msgNum: 980427729 - Validation Error: 
        [ VUID-VkMemoryAllocateInfo-pNext-03332 ] Object 0: handle = 0x555cba6d96d0, 
        type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x3a7023d1 | 
        If the pNext chain includes a VkImportMemoryHostPointerInfoEXT structure, opaqueCaptureAddress must be zero. 
        The Vulkan spec states: If the pNext chain includes a VkImportMemoryHostPointerInfoEXT structure, 
        VkMemoryOpaqueCaptureAddressAllocateInfo::opaqueCaptureAddress must be zero
        (https://vulkan.lunarg.com/doc/view/1.3.216.0/linux/1.3-extensions/vkspec.html#VUID-VkMemoryAllocateInfo-pNext-03332)
```

Replay can be downloaded here:
https://drive.google.com/drive/folders/1H8TDq_eSXYYOcBID2aQiTwMn1K8js5A9

**Comment by illia-polishchuk-gl** [comment]
Debugged the issue

Cyberpunk 2077 DirectX12 translated to Vulkan uses VkImportMemoryHostPointerInfoEXT for some of VkAllocateMemory calls

Logged pHostPointer parameters passed from Cyberpunk to mesa driver, and they're not zero
But when replaying capture the pHostPointer of VkImportMemoryHostPointerInfoEXT is always zero
Look's like GFX fails to save this filed  while tracing game

**Comment by effolkronium** [comment]
Fixed the issue in this PR: https://github.com/LunarG/gfxreconstruct/pull/803

Implemented allocation for external memory
Resetted opaqueCaptureAddress to 0 if replay uses VkImportMemoryHostPointerInfoEXT
