### ISSUE TITLE
toascii - Add a Metadata Header to JSON Lines Format

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#809]
It would be useful to have some metadata in every JSON file output.

### Fields to Include
* Version Number [_of JSON Schema?_]
* Commit-id tool was built against 
  * Also a bool for uncommitted changes? (Only of interest to gfxr devs)
* Source capture filename

### Maybes
* is_trimmed: bool [Requires seeking back to fix it]
* Frame range captured [Do we have this info soon enough?]
* Number of lines [optional, requires seeking back and leaving ugly reserved spaces ]
  * ! It probably can't be added at the front of the file until the whole file is generated so perhaps not worthwhile.
* List of functions in capture [Requires long insert at front of file, so not great ]

### Laters
* Set of flags passed to tool (any command-line switches and env vars affecting output). [_There are currently none._]

### Metadata Footer
Is it worth gathering the data we only pick up during processing and presenting it in a footer?

**Comment by bradgrantham-lunarg** [comment]
> * is_trimmed: bool

I'm not sure we know that until after we've started parsing the capture file.

**Comment by andrew-lunarg** [comment]
> > * is_trimmed: bool
> 
> I'm not sure we know that until after we've started parsing the capture file.

Good point. Curse the lexicographer who didn't make sure "true" and "false" occupied the same number of characters. We could always seek back and overwrite a default false with the help of a cheeky space:
```
"false,"
"true, "
```

**Comment by andrew-lunarg** [comment]
@bradgrantham-lunarg How much of the source file's path do we want to expose in the header?

* Just the filename?
  * (-) Might lose useful information encoded in the directory structure for some users (e.g. `/captures/windows/ihv_red/driver_version/trimmed/optimised/game_one/gfxrecon_capture.20220928T155218.gfxr` )
* Full path to capture file?
  * (-) Could expose sensitive info in path. E.g. (`/secret_project_for_client_x/feature_john_is_blocking_but_ill_get_in_during_his_pto/captured_by_employee_first_name_second_name/gfxrecon_capture.20220928T155218.gfxr`)

**Comment by andrew-lunarg** [comment]
@brad I have some dummy values being output on the first line of the file. They look like this:
```json
{"header":{"source":"gfxrecon_capture.20220928T155218.gfxr","version":"0.8.0","commit":"2ab193321131ab2d120b46bdc0723c0c8704e95c"}}
```
