### ISSUE TITLE
Enable `toascii` but now it's `convert`

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#818]
- [x] #833 
- [x] #819 
- [x] #794 
- [x] #809
- [x] #820 
- [x] #847
- [x] Maybe #832
- [ ] Remove the CMAKE conditional and restore USAGE messages - undo bb5f5ad295dea436450a3d1a8b54f9f302067888
- [ ] Add `convert` to `tools/gfxrecon/gfxrecon.py`

PR https://github.com/LunarG/gfxreconstruct/pull/852 should allow the tickboxes without issues to be ticked.

**Comment by andrew-lunarg** [comment]
## Naming
I like taking the opportunity to move to a completely different name, more in keeping with the other tools\*. Something like **`gfxrecon-convert`**.

Have we ever limited ourselves to only outputting ascii (7-bit encoding) anyway? Strings derived from C identifier names and our few keywords fit, but as we expand to metadata and binary blobs, maybe we want to use that eighth bit or even allow fatter text encodings like utf-8.

Starting the name of a tool with `to` or `2` is quite unconventional. Normally the `to` or `2` comes in the middle\*\*.

### Alternative names:
* `totext`, AKA `gfxrecon-totext`
  * Keeps it vague
* `dump`, AKA `gfxrecon-dump`
  * Harks back to `api-dump`, `objdump`, `hexdump`, `tcpdump`, `rtmpdump`, etc.
  * Can dump json
  * Can dump plain text
  * Can dump C++
  * Sounds like it is in same family as existing tools \*.
* `convert`, AKA `gfxrecon-convert`
  * Says what the tool does when applied to a trace file: converts it (to JSON, to C code, to tabbed plain text, ...)
  * Clearly different from existing tool names (`extract` and `info` semantically overlap `dump`). 
  * Sounds like it is in same family as existing tools \*\*.

### Existing Tools
\*
```
gfxrecon-compress
gfxrecon-extract
gfxrecon-info
gfxrecon-optimize
gfxrecon-replay
```

### Tools With "to" or "2" in the Name on my System
The pattern is always `x`_to_`y`.
\*\* 
```
/usr/bin/pdftotext
/usr/bin/infotocap
/usr/bin/pdftohtml
/usr/bin/pdftops
/usr/bin/bmtoa
/usr/bin/ppmtoacad
/usr/bin/pbmtopgm
/usr/bin/pnmtorast
/usr/bin/pbmto10x
/usr/bin/cmuwmtopbm
/usr/bin/mgrtopbm
/usr/bin/gemtopbm
/usr/bin/ppmtoyuv
/usr/bin/pbmtoatk
/usr/bin/pbmtozinc
/usr/bin/pnmtotiffcmyk
/usr/bin/pbmtox10bm
/usr/bin/brushtopbm
/usr/bin/pbmtowbmp
/usr/bin/ppmtosixel
/usr/bin/fitstopnm
/usr/bin/pbmtog3
/usr/bin/ppmtopgm
/usr/bin/ppmtoeyuv
/usr/bin/pbmtoxbm
/usr/bin/pnmtosgi
/usr/bin/fstopgm
/usr/bin/jpegtopnm
/usr/bin/qrttoppm
/usr/bin/lispmtopgm
/usr/bin/pbmtoepsi
/usr/bin/ppmtoneo
/usr/bin/bioradtopgm
/usr/bin/ximtoppm
/usr/bin/ppmtotga
/usr/bin/leaftoppm
/usr/bin/sputoppm
/usr/bin/pdftoppm
/usr/bin/ybmtopbm
/usr/bin/bmptoppm
/usr/bin/xbmtopbm
/usr/bin/pbmtopsg3
/usr/bin/ppmtopj
/usr/bin/ppmtomap
/usr/bin/pbmtonokia
/usr/bin/ppmtoicr
/usr/bin/bmptopnm
/usr/bin/pnmtorle
/usr/bin/ppmtorgb3
/usr/bin/pgmtolispm
/usr/bin/anytopnm
/usr/bin/pjtoppm
/usr/bin/ilbmtoppm
/usr/bin/pbmtomgr
/usr/bin/xpmtoppm
/usr/bin/pnmtopng
```
```
/usr/bin/ps2ascii
/usr/bin/gxl2gv
/usr/bin/fig2dev
/usr/bin/ucs2any
/usr/bin/yaml2obj-14
/usr/bin/qdbusxml2cpp
/usr/bin/graphml2gv
/usr/bin/es2tri
/usr/bin/foo2slx
/usr/bin/ps2pdf12
/usr/bin/pf2afm
/usr/bin/h2xs
/usr/bin/ps2pdf13
/usr/bin/gts2dxf
/usr/bin/foo2lava
/usr/bin/wmf2svg
/usr/bin/ps2pdf
/usr/bin/stl2gts
/usr/bin/pdf2ps
/usr/bin/ps2ps2
/usr/bin/h2ph
/usr/bin/pl2pm
/usr/bin/foo2zjs
/usr/bin/wmf2eps
/usr/bin/dot2gxl
/usr/bin/foo2qpdl
/usr/bin/eps2eps
/usr/bin/bzip2recover
/usr/bin/ps2epsi
/usr/bin/file2brl
/usr/bin/foo2xqx-wrapper
/usr/bin/enc2xs
/usr/bin/es2gears_x11
/usr/bin/gts2oogl
/usr/bin/gts2xyz
/usr/bin/pnm2ppa
/usr/bin/ps2ps
/usr/bin/foo2hp
/usr/bin/foo2xqx
/usr/bin/f2py3.10
/usr/bin/wmf2x
/usr/bin/mm2gv
/usr/bin/es2_info
/usr/bin/fig2ps2tex
/usr/bin/gv2gml
/usr/bin/obj2yaml-14
/usr/bin/foo2hbpl2
/usr/bin/l2ping
/usr/bin/ps2txt
/usr/bin/gv2gxl
/usr/bin/foo2oak-wrapper
/usr/bin/f2py3
/usr/bin/wmf2gd
/usr/bin/hex2hcd
/usr/bin/pod2html
/usr/bin/wmf2fig
/usr/bin/addr2line
/usr/bin/foo2lava-wrapper
/usr/bin/foo2ddst
/usr/bin/foo2hiperc
/usr/bin/foo2hp2600-wrapper
/usr/bin/pod2man
/usr/bin/gts2stl
/usr/bin/bzip2
/usr/bin/pdf2dsc
/usr/bin/ps2pdf14
/usr/bin/gml2gv
/usr/bin/gxl2dot
/usr/bin/foo2oak
/usr/bin/pod2text
/usr/bin/pod2usage
/usr/bin/ps2pdfwr
/usr/bin/pic2tpic
/usr/bin/arm2hpdl
```

**Comment by bradgrantham-lunarg** [comment]
I like `gfxrecon-convert`.
