### ISSUE TITLE
toascii - Strip "[out]" Prefix From Variable Names

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#819]
Names of variables in the JSON should be identical to their names in the specification XML and C headers. Name mangling to encode information is not the right approach.

@bradgrantham-lunarg I want to go ahead and do this immediately. We all dislike it. We can at least be looking at cleaner JSON while deciding how we want to convey this information in a subsequent iteration of the format, if we want it in the format at all.

**Comment by bradgrantham-lunarg** [comment]
👍 Sounds good to me.
