### ISSUE TITLE
Refactor PageGuardManager::GetSystemPageSize() out of PageGuardManager

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#827]
It has no reason to be a non-static member function. Better as a free function in a system/platform abstraction header. It should also return a `uint32_t` as the functions it calls does, not `uint64_t`. There may be similar functions suitable for the same treatment.

**Comment by bradgrantham-lunarg** [comment]
@andrew-lunarg Was this fixed by merging #826?

**Comment by andrew-lunarg** [comment]
Fixed by this commit https://github.com/LunarG/gfxreconstruct/pull/826/commits/5e8b40abad52611a4420961169714cd42332a1ac
in PR #826
