### ISSUE TITLE
Add an Annotation Block With the Build Version of the Capture Layer

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#831]
Inject the same information reported by the `--version` parameter of the command line tools.
Put it early in the capture file, before any API calls.
* Extend `gfxrecon-info` to report the version info.
* Extend `gfxrecon-convert` to store the info in the header object of its json lines output (https://github.com/LunarG/gfxreconstruct/issues/809).
* Extend `gfxrecon-optimize` to not strip the annotations.

We can expand the header with more information: https://github.com/LunarG/gfxreconstruct/issues/868

**Comment by bradgrantham-lunarg** [comment]
I marked this P1 because capture layer build info would help us debug some of the crashes we've seen in the past where a block unexpectedly changed because a Vulkan struct changed.

**Comment by andrew-lunarg** [comment]
An annotation block is a `key:value` string pair with an enum type specifying if the value is plain text, xml, or json. The lengths of the two strings are stored as 32 bit numbers. Are we okay with not having them be 64 bit?
We have a chance to change that now before anyone uses an annotation. The uses for a > 4GB annotation value escape me but perhaps that is a failure of imagination and there is the argument for consistency with other sizes/lengths in `format.h`.
```cpp
struct AnnotationHeader
{
    BlockHeader    block_header;
    AnnotationType annotation_type;
    uint32_t       label_length;
    uint32_t       data_length;
};
```

**Comment by andrew-lunarg** [comment]
`FileTransformer` needs annotation block support added otherwise `compress` and `optimize` will strip annotations out as unknown blocks.

**Comment by andrew-lunarg** [comment]
## Annotation Design Option 1 - Standard JSON Header Annotation Shared By All Tools

Stuff lots of fields into one header annotation as JSON to avoid lots of little annotations in the file and having to date and identify each one.
All tools use a common header schema with some optional components.
Each tool to modify a capture over time makes it’s own fresh header, and the sequence of dated header annotations forms a history log without each tool having to embed a json parser to be able to edit the header from a previous tool and append its own edits to it. It can inject its own header at the front of the binary capture file so the history can be read reverse-chronologically.

A sketch of the structure of this header annotation would be as follows.
```
Annotation label = “header”
Annotation value = json schema below
{
    “tool”:    “capture|compress|optimize”, // third party tools too
    “infile”:  “/path/to/gfxr”, @optional
    “outfile”: “/path/to/gfxr”,
    "gfxrecon-version": "0.9.15-dev",
    "vulkan-version": "1.3.231",
    “date”: “2022-10-18 14:13:51+01:00”, // rfc3339 to seconds
    “os”:   “linux”,
    “arch”: “x64”,
    // Commandline options and env vars in force:
    “settings: {
        “capture_frames”: “1-100”,
        “memory_tracking_mode”: “page_guard”,
        “page_guard_align_buffer_sizes”: true,
        “capture_compression_type”: “zlib”,
        …
    }
}
```

It might need a better name than **"header"** given there can be lots of them up near the top of a file and the `convert` json format already has a "header" json line type.

_I've called this design option 1 here, but I've already convinced myself I want to do it this way of there are no objections_.

**Comment by per-mathisen-arm** [comment]
Looks good. Would be nice to have a 'user' / 'author' field as well, taken from the current OS user. This exists in patrace and has proven very useful in practice for multi-user environments.

**Comment by bradgrantham-lunarg** [comment]
Probably the lengths should be extended to 64 bits.  I don't know about label length but I can imagine data length could be more than 4GB if some as-yet-unwritten tool decided to emit a ton of data.

Just to make sure I get it, this would be a new `kAnnotation` block and it would contain the JSON you described above.     If we have this header, would we omit the "source" field from `convert`s current output, for example?

Sounds good to me!

**Comment by andrew-lunarg** [comment]
> Just to make sure I get it, this would be a new `kAnnotation` block and it would contain the JSON you described above.
It would be our first annotation block. There's just some unused skeleton code for annotations on dev. It would contain the above json and could be expanded as we think of new things to add.

> If we have this header, would we omit the "source" field from `convert`s current output, for example?

I think we keep them both. The file might have been moved between capture and conversion. Having both paths preserves that history.

**Comment by andrew-lunarg** [comment]
@bradgrantham-lunarg Implementing the output in `gfxr-convert` I realised the nice json above has to be escaped to fit on a line and to allow json inside a json string. even pretty-printing via jq would keep the whole "data" payload as one line, escaped. It comes out like this:

```json
{"index":0,"annotation":{"type":"kJson","label":"header","data":"{\n    \"tool\": \"capture\",\n    \"gfxrecon-version\": \"0.9.15-dev (andy-fix-831-annotate-captures-with-layer-version:621b79a*)\",\n    \"vulkan-version\": \"1.3.231\"\n}\n"}}
```

I wonder if I should give annotations with the label "header"\* their own top-level type like "vkFunc" in the output and extract them from the data field rather than embedding them escaped like above. Something like this:

```json
{"index":0,"annotation-header":{"tool": "capture", "gfxrecon-version": "0.9.15-dev (andy-fix-831-annotate-captures-with-layer-version:621b79a*)","vulkan-version": "1.3.231"}}
```
This would pretty-print with `jq`.
I could do the same thing to generically to any annotation of type `kJson`: prefix its label with "annotation-" to give it a type at top level and extract it and delete newlines.

\* still needs a better name.
