### ISSUE TITLE
Assert is triggered in vmaCreateAllocator when driver's vulkanApiVersion > 1.1

### ISSUE THREAD

**Issue by werman** [LunarG/gfxreconstruct#845]
When replaying with `-m rebind` if the driver has higher than 1.1 VK api version, this assert is triggered:
https://github.com/LunarG/gfxreconstruct/blob/aaeaa34c05d22bbe736768eda00dce029dc2ea0c/external/VulkanMemoryAllocator/include/vk_mem_alloc.h#L16810-L16811

**Comment by bradgrantham-lunarg** [comment]
Does replay complete successfully in Release build?

**Comment by bradgrantham-lunarg** [comment]
Suspect this implies a rev of VMA.  The one we have in there is pretty old.  We could go to the last 2.X.X revision or just swallow the work required to upgrade to 3.0

**Comment by werman** [comment]
> Does replay complete successfully in Release build?

The trace replays correctly without that assert barring the other issue I filed.

**Comment by locke-lunarg** [comment]
@werman Could you test this PR? Thank you.
https://github.com/LunarG/gfxreconstruct/pull/879

**Comment by werman** [comment]
@locke-lunarg I'll test it tomorrow.

**Comment by werman** [comment]
@locke-lunarg Works without any issue.

**Comment by locke-lunarg** [comment]
Thank you @werman
