### ISSUE TITLE
replay of vkcube with 1.3 instance provokes VMA crash on 1.2 driver

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#883]
```
[gfxrecon] INFO - Replay adjusted the vkEnumeratePhysicalDevices array count: capture count = 2, replay count = 1
[gfxrecon] INFO - Replay adjusted the vkEnumeratePhysicalDevices array count: capture count = 2, replay count = 1
[gfxrecon] INFO - Replay adjusted the vkGetPhysicalDeviceQueueFamilyProperties array count: capture count = 4, replay count = 3
[gfxrecon] WARNING - The replay device differs from the original capture device; replay may fail due to device incompatibilities:
[gfxrecon] WARNING -   Capture device info:    [vendorID = 0x10de, deviceId = 0x249d, deviceName = NVIDIA GeForce RTX 3070 Laptop GPU]
[gfxrecon] WARNING -   Replay device info:    [vendorID = 0x10de, deviceId = 0x1f07, deviceName = GeForce RTX 2070]
ERROR: ----stderr---------------------------------------------------
Assertion failed: m_VulkanFunctions.vkGetDeviceBufferMemoryRequirements != nullptr, file D:\j\workspace\manual-gfxreconstruct\gfxreconstruct\external\VulkanMemoryAllocator\include\vk_mem_alloc.h, line 14652
```
I suspect we initialize VMA with the recorded capture apiVersion and not the replay created instance API version.

**Comment by bradgrantham-lunarg** [comment]
Not sure if this is really a P1 or 1.0 release issue.  I suspect this only happens if someone captures on 1.3 and replays on 1.2, which should be somewhat uncommon.  But we might start getting complaints about this shortly if it's more common than I thought, so leaving elevated for now.

**Comment by locke-lunarg** [comment]
I think we should check whether or not  the device `VkPhysicalDeviceProperties::apiVersion` support the capture apiVersion during replaying. If it doesn't support, we could just print a warning log. Maybe we could add an option to set apiVersion for replay.

**Comment by lunarpapillo** [comment]
To reproduce, run a **Jenkins manual-gfxreconstruct** job, with:
- `TEST_SUITE`: `883.json`
- `BUILD_MODE`: `Debug`
- `BITS`: `32` or `64`, as desired
- `NODE`: `sansalvacion`

**Comment by lunarpapillo** [comment]
FYI, I also added this test case to `gerrit-suite.json` so it'll get some testing to make sure we don't regress.
