### ISSUE TITLE
Support for VK_EXT_graphics_pipeline_library

### ISSUE THREAD

**Issue by ishitatsuyuki** [LunarG/gfxreconstruct#889]
Please support the graphics pipeline library EXT. This extension is seeing significant use in layering efforts, mainly in DXVK.

There's a bunch of assertion failure, due to (non-exhaustive list):
- empty `pSetLayouts` elements in `VkPipelineLayoutCreateInfo`
- ShaderModule replaced by `VkShaderModuleCreateInfo` in pNext of VkPipelineShaderStageCreateInfo
- empty `pipelineLayout` in `VkGraphicsPipelineCreateInfo`

This can be easily reproduced by running `dEQP-VK.pipeline.pipeline_library.*` in VKCTS with layer attached, on a [supported driver](https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_EXT_graphics_pipeline_library&platform=all) (Nvidia is the easiest one but you can also try lavapipe).

**Comment by bradgrantham-lunarg** [comment]
labeling P1 because of DXVK

**Comment by bradgrantham-lunarg** [comment]
@ishitatsuyuki Can you still replicate any issues you were having with graphics pipeline library?  Could you test current `dev` to see if it resolves your capture issues?

**Comment by ishitatsuyuki** [comment]
Tested Overwatch 2 and it doesn't launch with the layer attached, #1120 may be related. CTS looks fine however.

**Comment by ishitatsuyuki** [comment]
Actually `dEQP-VK.pipeline.pipeline_library.graphics_library.misc.non_graphics.shader_module_info_comp` seems to fail, might be a good repro.
