### ISSUE TITLE
Desktop range capture regression

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#890]
Reported in https://github.com/LunarG/gfxreconstruct/pull/867#discussion_r1014552808
> #867 breaks desktop range capture. Desktop hotkey captures now only last one frame long because !IsTrimEnvVarEnabled() always evaluates to true

**Comment by bradgrantham-lunarg** [comment]
Hey, @panos-lunarg  , could you see about reproducing this and take a look if range and hotkey trimming have been short-circuited by `!IsTrimEnvVarEnabled`?

**Comment by panos-lunarg** [comment]
Addressed in #891
