### ISSUE TITLE
Linux AMD captures are unreliable

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/gfxreconstruct#903]
````
gfxrecon-replay: ../../src/xcb_conn.c:215: write_vec: Assertion `!c->out.queue_len' failed.
```
This may be a bug in XCB or a bug in the way we invoke X11.  If it is not a bug in GFXR, we may need to workaround it with repeated flushes or some such on `XCloseDisplay` or possibly reach into XCB structures to determine when it is safe to do so.

**Comment by bradgrantham-lunarg** [comment]
@davidlunarg Do you think this is fixed from your recent investigations into Projects issues?

**Comment by davidlunarg** [comment]
This issue is no longer present on Ubunutu 22.04. I hesitate to close this issue because earlier versions of Ubuntu are supported by grxreconstruct. Or maybe we can close it because there exists a know workaround?

**Comment by KarenGhavam-lunarG** [comment]
IMHO, we should close it since there is a known workaround. More important things to work on...

**Comment by bradgrantham-lunarg** [comment]
I think close it; we know this is an issue that may be resolved by later versions of libx11 or libxcb and in any case we haven't identified any way that it's GFXReconstruct's bug.
