### ISSUE TITLE
SharedMutex is buggy

### ISSUE THREAD

**Issue by ishitatsuyuki** [LunarG/gfxreconstruct#909]
SharedMutex is broken. It tracks `has_read_lock_` to allow upgrading a read lock to write lock except it never unsets the flag.

https://github.com/LunarG/gfxreconstruct/blob/2a2c74f9d0b2fead65a6442aa9492685948d0e99/framework/util/shared_mutex.cpp#L69-L72

Then it will happily allow a writer lock to be taken with readers alive. This leads to corrupt entries getting inserted inside initialization blocks.

I suggest that we replace this with `std::shared_mutex`. Some reasons:
- We only take the mutex on each Vulkan function entrypoint. Vulkan has no re-entrancy guarantee AFAIK so we'll never run into a situation where upgrades are required.
- Most of the time it's just reader lock, the writer lock is only taken on vkQueuePresent(). There's nearly no contention and lock implementation should have no effect on performance. (I don't see why we should use spinning here either.)
- The current implementation performs more atomic operations than necessary.
- There is another questionable synchronization handling:
  https://github.com/LunarG/gfxreconstruct/blob/2a2c74f9d0b2fead65a6442aa9492685948d0e99/framework/util/shared_mutex.cpp#L44-L48
  `wait_for_writer_` is stored while mutex is unlocked, so another thread could come in trying to acquire the writer lock, sets the flag but ends up getting it wiped.

**Comment by andrew-lunarg** [comment]
Thanks for the analysis. Do you have a reliable repro for it causing a problem in use? I do appreciate threading bugs can be indeterminate and hard to repro.

> I suggest that we replace this with std::shared_mutex

That's another point for raising our minimum from C++14 to 17: https://en.cppreference.com/w/cpp/thread/shared_mutex

**Comment by panos-lunarg** [comment]
Perhaps @davidd-lunarg has something to suggest here.
I remember having a similar conversation with him in the past, when I tried to replace it with `std::shared_mutex` in a PR but he said that we have `SharedMutex` in place for performance reasons. I also remember mentioning something about a patch with fixes for `SharedMutex`.

**Comment by perim** [comment]
FYI, I made a tracing implementation doing almost no mutexing (that is, none for the general case), where each thread instead streams to its own file, then the files are merged together on end of tracing. Hopefully I can open source it soon for study.

**Comment by ishitatsuyuki** [comment]
I forgot to consider Windows whose mutex implementation always roundtrips to the kernel which indeed is very slow. I only tested on Linux which explains why the difference appeared to be negligible.

Short term we probably want to put a band aid on the biggest holes of the current SharedMutex; right now it barely does its job.

For the long term, I think most of the locks taken in gfxreconstruct is quite redundant (the hotspot is command recording and they're externally synchronized, descriptors are externally synchronized as well but a little more trickier), so avoiding taking mutexes sounds better than e.g. trying to pick a fast shared mutex library.

**Comment by panos-lunarg** [comment]
I cherry-picked @davidd-lunarg's patch for `SharedMutex` from a private branch we keep internally: #910 
@ishitatsuyuki please have a look and let us know if you believe it addresses the issues you have discovered.

**Comment by davidd-lunarg** [comment]
#979 Replaces `util::SharedMutex` with `std::shared_mutex` and should resolve this issue.

**Comment by ishitatsuyuki** [comment]
Thanks for fixing this! Closing as the I have hacked in the std implementation before and checked that it should solve the capture corruption issues.
