### ISSUE TITLE
VkPhysicalDeviceShaderCoreBuiltinsPropertiesARM Gained a new Field

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/gfxreconstruct#924]
The `shaderCoreMask` member is new in vk.xml post the sdk 1.3.236 update: https://github.com/LunarG/gfxreconstruct/pull/919.

```<member limittype="bitmask"><type>uint64_t</type>                   <name>shaderCoreMask</name></member>```

```
 <type category="struct" name="VkPhysicalDeviceShaderCoreBuiltinsPropertiesARM" returnedonly="true" structextends="VkPhysicalDeviceProperties2">
            <member values="VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_PROPERTIES_ARM"><type>VkStructureType</type> <name>sType</name></member>
            <member optional="true"><type>void</type>*                          <name>pNext</name></member>
            <member limittype="bitmask"><type>uint64_t</type>                   <name>shaderCoreMask</name></member>
            <member limittype="max"><type>uint32_t</type>                       <name>shaderCoreCount</name></member>
            <member limittype="max"><type>uint32_t</type>                       <name>shaderWarpsPerCore</name></member>
        </type>
```
See line 7649.

## ToDo
* Add a versioned/deprecated encode / decode for the previous layout so that backward compatibility is preserved.

**Comment by bradgrantham-lunarg** [comment]
This was mentioned in https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5512, no previous implementations of the extension exist (as far as ARM knows), so we can ignore this change.
