### ISSUE TITLE
[replay] VK_ERROR_DEVICE_LOST(vkQueuePresentKHR) on Android

### ISSUE THREAD

**Issue by chenyangchenyang** [LunarG/gfxreconstruct#990]
**Replay crashed on splash screen**

Detail:

gfxr File(Capture&Replay on same android device):
[MyProject_gfxrecon_capture_trim_trigger_20230213T102211.zip](https://github.com/LunarG/gfxreconstruct/files/10730008/MyProject_gfxrecon_capture_trim_trigger_20230213T102211.zip)

python .\gfxrecon.py replay --remove-unsupported --push-file .\MyProject_gfxrecon_capture_trim_trigger_20230213T102211.gfxr /sdcard/MyProject_gfxrecon_capture_trim_trigger_20230213T102211.gfxr

**adb logcat:**
[adb_logcat.txt](https://github.com/LunarG/gfxreconstruct/files/10730039/adb_logcat.txt)

**Key Words：**
Line 161: 02-13 10:24:32.691 5640 5667 I gfxrecon: Loading state for captured frame 391
Line 162: 02-13 10:24:32.691 5640 5667 I gfxrecon: Loading state for captured frame 391
Line 175: 02-13 10:24:32.705 5640 5667 I gfxrecon: Replay has removed the following layers from VkInstanceCreateInfo when calling vkCreateInstance:
Line 176: 02-13 10:24:32.705 5640 5667 I gfxrecon: VK_LAYER_LUNARG_gfxreconstruct
Line 374: 02-13 10:24:33.977 5640 5667 I gfxrecon: Finished loading state for captured frame 391
Line 375: 02-13 10:24:33.977 5640 5667 I gfxrecon: Finished loading state for captured frame 391
Line 423: 02-13 10:24:36.100 5640 5667 F gfxrecon: API call vkQueuePresentKHR returned error value VK_ERROR_DEVICE_LOST that does not match the result from the capture file: VK_SUBOPTIMAL_KHR. Replay cannot continue

**Version: gfxreconstruct-v0.9.16.1**

**Mobile Info:**
GpuFamily: Mali-G77 MC9
GlVersion: OpenGL ES 3.2 v1.r26p0-01eac0.bed3b8f44871361148086fa6397ba747
VulkanAvailable: true
VulkanVersion: 1.1.131
AndroidVersion: 11
DeviceMake: alps
DeviceModel:
DeviceBuildNumber: full_k6893v1_64_144hz_vdo-userdebug 11 RP1A.200720.011 mp1V899 dev-keys
UsingHoudini: false
Hardware: MT6893Z/CZA
Chipset: unknown

How to resolve please?

**Comment by andrew-lunarg** [comment]
It looks like you have the capture layer active during replay. Did you want to capture a second time during replay? There are legitimate uses for doing that and it should work but disabling the capture layer for replay would at least simplify your situation.

**Comment by bradgrantham-lunarg** [comment]
@chenyangchenyang , it looks like we may have to investigate your capture in-depth to figure out what's going on.  

As a last thought, have you successfully captured and replay `vkcube` on Android?  We know that app works with capture and replay, so if there's anything else that needs to be changed to get replay on Android, trying vkcube may make that more obvious.

**Comment by panos-lunarg** [comment]
Do you have the same problem when replaying a non trimmed capture?

From the logcat it seems there is a problem with the swapchain images/indices
```
02-13 10:24:36.100  5640  5667 E vulkan  : QueueSignalReleaseImageANDROID failed: -4
02-13 10:24:36.100  5640  5667 F gfxrecon: API call vkQueuePresentKHR returned error value VK_ERROR_DEVICE_LOST that does not match the result from the capture file: VK_SUBOPTIMAL_KHR.  Replay cannot continue.
```
Please try `--use-captured-swapchain-indices` when replaying the trimmed capture to see if it fixes the issue. It shouldn't but we have seen a similar issue in the past.

**Comment by chenyangchenyang** [comment]
> Do you have the same problem when replaying a non trimmed capture?
> 
> From the logcat it seems there is a problem with the swapchain images/indices
> 
> ```
> 02-13 10:24:36.100  5640  5667 E vulkan  : QueueSignalReleaseImageANDROID failed: -4
> 02-13 10:24:36.100  5640  5667 F gfxrecon: API call vkQueuePresentKHR returned error value VK_ERROR_DEVICE_LOST that does not match the result from the capture file: VK_SUBOPTIMAL_KHR.  Replay cannot continue.
> ```
> 
> Please try `--use-captured-swapchain-indices` when replaying the trimmed capture to see if it fixes the issue. It shouldn't but we have seen a similar issue in the past.

It is failed for replaying

detail:

Command:
python .\gfxrecon.py replay --use-captured-swapchain-indices --remove-unsupported --push-file .\MyProject_gfxrecon_capture_20230227T192959.gfxr /sdcard/MyProject_gfxrecon_capture_20230227T192959.gfxr

gfx:
[MyProject_gfxrecon_capture_20230227T192959.zip](https://github.com/LunarG/gfxreconstruct/files/10839203/MyProject_gfxrecon_capture_20230227T192959.zip)

adblogcat:
[adblogcat_gfxrecon.txt](https://github.com/LunarG/gfxreconstruct/files/10839210/adblogcat_gfxrecon.txt)

screen_recording:
[gfxrecon_replay.zip](https://github.com/LunarG/gfxreconstruct/files/10839216/gfxrecon_replay.zip)

**Comment by panos-lunarg** [comment]
This time I cannot see anything suspicious in the logcat. On the other hand it seems that the trace is consumed successfully:
```
02-27 19:33:31.014 12013 12040 V gfxrecon: Total time: 8.562401 seconds
02-27 19:33:31.014 12013 12040 V gfxrecon: Replay FPS: 130.220484 fps, 8.562401 seconds, 1115 frames, framerange 1-1115
```
Can you please make sure that the trace is recorded correctly? Can you give us a logcat while _capturing_?

**Comment by chenyangchenyang** [comment]
> This time I cannot see anything suspicious in the logcat. On the other hand it seems that the trace is consumed successfully:
> 
> ```
> 02-27 19:33:31.014 12013 12040 V gfxrecon: Total time: 8.562401 seconds
> 02-27 19:33:31.014 12013 12040 V gfxrecon: Replay FPS: 130.220484 fps, 8.562401 seconds, 1115 frames, framerange 1-1115
> ```
> 
> Can you please make sure that the trace is recorded correctly? Can you give us a logcat while _capturing_?

Yes, It is recorded correctly
capture logcat:
[capture_adb_logcat.txt](https://github.com/LunarG/gfxreconstruct/files/10845872/capture_adb_logcat.txt)

**Comment by chenyangchenyang** [comment]
> This time I cannot see anything suspicious in the logcat. On the other hand it seems that the trace is consumed successfully:
> 
> ```
> 02-27 19:33:31.014 12013 12040 V gfxrecon: Total time: 8.562401 seconds
> 02-27 19:33:31.014 12013 12040 V gfxrecon: Replay FPS: 130.220484 fps, 8.562401 seconds, 1115 frames, framerange 1-1115
> ```
> 
> Can you please make sure that the trace is recorded correctly? Can you give us a logcat while _capturing_?


when replay gfx， I capture a renderdoc file
[gfxrecon.zip](https://github.com/LunarG/gfxreconstruct/files/10846114/gfxrecon.zip)

shader is captrue correctly,But Mesh & Texture is Error
![image](https://user-images.githubusercontent.com/28689129/221741851-dfd767fe-67ff-464a-a370-58248e735f9e.png)
![image](https://user-images.githubusercontent.com/28689129/221741898-b6ff8570-a43f-4029-bd1f-8cee07981463.png)

**Comment by panos-lunarg** [comment]
Renderdoc investigation looks interesting but let's focus on the capture logcat first:
```
02-28 09:34:19.794  4076  4122 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.memory_tracking_mode" with value "assisted"
```
I see you are using `assisted` memory tracking mode. I am fairly confident that `assisted` mode is not going to work with UE and the issues that you might have with `assisted` + UE are exactly what you are encountering: missing assets.

Please try using `page_guard` (which is the default) memory tracking mode instead when recording. This mode also has known issues with UE and it is probably giving you a crash when recording but we have a workaround.
If you do get a crash then try setting `debug.gfxrecon.page_guard_signal_handler_watcher 1` and `debug.gfxrecon.page_guard_signal_handler_watcher_max_restores 1` when capturing.
Hope that this will resolve your issue

**Comment by chenyangchenyang** [comment]
> Renderdoc investigation looks interesting but let's focus on the capture logcat first:
> 
> ```
> 02-28 09:34:19.794  4076  4122 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.memory_tracking_mode" with value "assisted"
> ```
> 
> I see you are using `assisted` memory tracking mode. I am fairly confident that `assisted` mode is not going to work with UE and the issues that you might have with `assisted` + UE are exactly what you are encountering: missing assets.
> 
> Please try using `page_guard` (which is the default) memory tracking mode instead when recording. This mode also has known issues with UE and it is probably giving you a crash when recording but we have a workaround. If you do get a crash then try setting `debug.gfxrecon.page_guard_signal_handler_watcher 1` and `debug.gfxrecon.page_guard_signal_handler_watcher_max_restores 1` when capturing. Hope that this will resolve your issue


Hi，Thanks~
It is Work in UE Demo
But It is crash in our ue project
Is there other recommend config about memory ?

**Comment by panos-lunarg** [comment]
Ok then this means that the signal handler for `SEGSEGV` is being replaced by UE. This is usually done when you ask from UE to enable UE's crash handler (possibly from other places as well). For that reason we have implemented a watcher thread that keeps an eye on the signal handler.

You enabled that watcher thread with `debug.gfxrecon.page_guard_signal_handler_watcher 1`. 
Every time the signal handler is being restored by that watcher thread the message `PageGuardManager: Signal handler has been removed. Re-installing.` should appear in logcat. 

Try increasing `debug.gfxrecon.page_guard_signal_handler_watcher_max_restores` to more than `1`. Usually `2` does the trick. You can also set it to `0` which will effectively keep the thread alive for ever.

**Comment by chenyangchenyang** [comment]
> Ok then this means that the signal handler for `SEGSEGV` is being replaced by UE. This is usually done when you ask from UE to enable UE's crash handler (possibly from other places as well). For that reason we have implemented a watcher thread that keeps an eye on the signal handler.
> 
> You enabled that watcher thread with `debug.gfxrecon.page_guard_signal_handler_watcher 1`. Every time the signal handler is being restored by that watcher thread the message `PageGuardManager: Signal handler has been removed. Re-installing.` should appear in logcat.
> 
> Try increasing `debug.gfxrecon.page_guard_signal_handler_watcher_max_restores` to more than `1`. Usually `2` does the trick. You can also set it to `0` which will effectively keep the thread alive for ever.

Hi,
It is crash during record capture

adb logcat(gfxrecon):

02-28 19:12:10.415 18776 18847 D vulkan  : added global layer 'VK_LAYER_LUNARG_gfxreconstruct' from library '/data/app/~~GPtInTRlX_LX0E3FYIaXkg==/com.tog.project-kfAdJJc7hQtRhti5yqDIcQ==/lib/arm64/libVkLayer_gfxreconstruct.so'
02-28 19:12:16.353 18776 18847 D UE4     : [2023.02.28-19.12.16:353][  0]LogVulkanRHI: Display: * VK_LAYER_LUNARG_gfxreconstruct
02-28 19:12:16.354 18776 18847 D UE4     : [2023.02.28-19.12.16:354][  0]LogVulkanRHI: Display: * VK_LAYER_LUNARG_gfxreconstruct
02-28 19:12:16.357 18776 18847 I vulkan  : Loaded layer VK_LAYER_LUNARG_gfxreconstruct
02-28 19:12:17.086 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.capture_file" with value "/sdcard/gfxrecon/UE_gfxrecon_capture.gfxr"
02-28 19:12:17.127 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.capture_compression_type" with value "LZ4"
02-28 19:12:17.146 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.capture_file_flush" with value "true"
02-28 19:12:17.247 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.log_file" with value "/sdcard/gfxrecon/UE_gfxrecon_capture.log"
02-28 19:12:17.287 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.log_file_flush_after_write" with value "true"
02-28 19:12:17.388 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.memory_tracking_mode" with value "page_guard"
02-28 19:12:17.506 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.page_guard_persistent_memory" with value "0"
02-28 19:12:17.528 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.page_guard_align_buffer_sizes" with value "1"
02-28 19:12:17.587 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.page_guard_unblock_sigsegv" with value "0"
02-28 19:12:17.607 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.page_guard_signal_handler_watcher" with value "1"
02-28 19:12:17.627 18776 18847 I gfxrecon: Settings Loader: Found option "debug.gfxrecon.page_guard_signal_handler_watcher_max_restores" with value "-1"
02-28 19:12:17.723 18776 18847 I gfxrecon: Initializing GFXReconstruct capture layer
02-28 19:12:17.723 18776 18847 I gfxrecon:   GFXReconstruct Version 0.9.16-unknown (9c0e5a3)
02-28 19:12:17.742 18776 18847 I gfxrecon: Recording graphics API capture to /sdcard/gfxrecon/UE_gfxrecon_capture_20230228T191217.gfxr
02-28 19:12:17.743 18776 18847 I gfxrecon:   Vulkan Header Version 1.3.236
02-28 19:12:17.750 18776 18847 D UE4     : [2023.02.28-19.12.17:750][  0]LogVulkanRHI: Display: -    Found device layer VK_LAYER_LUNARG_gfxreconstruct
02-28 19:12:32.972 18776 19044 W gfxrecon: PageGuardManager: Signal handler has been removed. Re-installing.

Is there other recommend config ?

**Comment by panos-lunarg** [comment]
>I have setting debug.gfxrecon.page_guard_signal_handler_watcher_max_restores to -1

`-1`? I'm not sure how negative values will work there. Have you tried with more than `1`?
Try setting it to `0` and count how many times `PageGuardManager: Signal handler has been removed. Re-installing.` is printed. Then set max_restores to that many times and hopefully it will work

**Comment by chenyangchenyang** [comment]
> > I have setting debug.gfxrecon.page_guard_signal_handler_watcher_max_restores to -1
> 
> `-1`? I'm not sure how negative values will work there. Have you tried with more than `1`? Try setting it to `0` and count how many times `PageGuardManager: Signal handler has been removed. Re-installing.` is printed. Then set max_restores to that many times and hopefully it will work

About debug.gfxrecon.page_guard_signal_handler_watcher_max_restores
If setting it to 0，it is crashed without Message(PageGuardManager: Signal handler has been removed. Re-installing)
if setting it to 100，it is crashed with one time Message(PageGuardManager: Signal handler has been removed. Re-installing)

adb logcat:
[100_logcat_gfxrecon.txt](https://github.com/LunarG/gfxreconstruct/files/10851092/100_logcat_gfxrecon.txt)

**Comment by chenyangchenyang** [comment]
> I see.
> 
> In that case I am afraid I don't know what the problem might be. We will need something to reproduce this on our side and try to find the root case. Can you share the apk of your project?
> 
> One last thing you can do is try the `unassisted` memory tracking method. This should probably work but it will generate a very big capture file and have a big performance impact when capturing

Hi,
I will try to ask my leader to share apk(project is confidential)

**Comment by panos-lunarg** [comment]
Given that this is a UE project that you have control over the source, one last thing I can suggest trying is to look into where UE is installing the signal handler for `SIGSEGV`.

As far as I know usually this is done by UE when you enable some specific modules. For example enabling the crash handler like this:
```
#include "Android/AndroidPlatformMisc.h"
...
FPlatformMisc::SetCrashHandler()
```

This will effectively call `sigaction` and replace the signal handler for `SIGSEGV` (along with other signals). So finding where UE calls `sigaction`, placing a breakpoint there, and from the backtrace deduce which modules are causing this. You can either disable that module or perhaps comment out the `sigaction` function altogether.

I.e. for the above example with the signal handler this is done in the `Engine/Source/Runtime/Core/Private/Android/AndroidPlatformMisc.cpp` file.

We understand that this is not ideal but figuring out how to properly solve this problem is something we have in our backlog.

**Comment by chenyangchenyang** [comment]
> Given that this is a UE project that you have control over the source, one last thing I can suggest trying is to look into where UE is installing the signal handler for `SIGSEGV`.
> 
> As far as I know usually this is done by UE when you enable some specific modules. For example enabling the crash handler like this:
> 
> ```
> #include "Android/AndroidPlatformMisc.h"
> ...
> FPlatformMisc::SetCrashHandler()
> ```
> 
> This will effectively call `sigaction` and replace the signal handler for `SIGSEGV` (along with other signals). So finding where UE calls `sigaction`, placing a breakpoint there, and from the backtrace deduce which modules are causing this. You can either disable that module or perhaps comment out the `sigaction` function altogether.
> 
> I.e. for the above example with the signal handler this is done in the `Engine/Source/Runtime/Core/Private/Android/AndroidPlatformMisc.cpp` file.
> 
> We understand that this is not ideal but figuring out how to properly solve this problem is something we have in our backlog.

Hi,
I have comment FPlatformMisc::SetCrashHandler() and then there are two new questions
1. It is still crash before I enter to scene(crash happen on loading resources)，but crash time is delay
2. No Visible 3D Mesh during replay gfx(either no mesh or error vertexBuffer,renderdoc can't attach(when try to attach,it is carsh))

config:
[Tog_gfxrecon_capture.txt](https://github.com/LunarG/gfxreconstruct/files/10858808/Tog_gfxrecon_capture.txt)

**Comment by chenyangchenyang** [comment]
> Given that this is a UE project that you have control over the source, one last thing I can suggest trying is to look into where UE is installing the signal handler for `SIGSEGV`.
> 
> As far as I know usually this is done by UE when you enable some specific modules. For example enabling the crash handler like this:
> 
> ```
> #include "Android/AndroidPlatformMisc.h"
> ...
> FPlatformMisc::SetCrashHandler()
> ```
> 
> This will effectively call `sigaction` and replace the signal handler for `SIGSEGV` (along with other signals). So finding where UE calls `sigaction`, placing a breakpoint there, and from the backtrace deduce which modules are causing this. You can either disable that module or perhaps comment out the `sigaction` function altogether.
> 
> I.e. for the above example with the signal handler this is done in the `Engine/Source/Runtime/Core/Private/Android/AndroidPlatformMisc.cpp` file.
> 
> We understand that this is not ideal but figuring out how to properly solve this problem is something we have in our backlog.


hi,
Do you have other recommend modifies about ue source code?

**Comment by panos-lunarg** [comment]
I would try to find all places where `sigaction` is called.

For example I would begin by commenting out the `SIGSEGV` signal from 
```
static constexpr int32 TargetSignals[] =
{
	SIGQUIT, // SIGQUIT is a user-initiated "crash".
	SIGILL,
	SIGFPE,
	SIGBUS,
//	SIGSEGV,
	SIGSYS,
	SIGABRT
};
```
in `Engine/Source/Runtime/Core/Private/Android/AndroidPlatformMisc.cpp`

The I would try commenting out
`int result = sigaction(TargetSignals[i], ....` from `HookTargetSignals()` and `RestorePreviousTargetSignalHandlers()` in the same file.

If you are still getting the same problem then you'll need to find all the other places that `sigaction` might be called from UE on Android and do the same. Unfortunately I am not familiar with UE so I don't know where that could be

**Comment by chenyangchenyang** [comment]
> I would try to find all places where `sigaction` is called.
> 
> For example I would begin by commenting out the `SIGSEGV` signal from
> 
> ```
> static constexpr int32 TargetSignals[] =
> {
> 	SIGQUIT, // SIGQUIT is a user-initiated "crash".
> 	SIGILL,
> 	SIGFPE,
> 	SIGBUS,
> //	SIGSEGV,
> 	SIGSYS,
> 	SIGABRT
> };
> ```
> 
> in `Engine/Source/Runtime/Core/Private/Android/AndroidPlatformMisc.cpp`
> 
> The I would try commenting out `int result = sigaction(TargetSignals[i], ....` from `HookTargetSignals()` and `RestorePreviousTargetSignalHandlers()` in the same file.
> 
> If you are still getting the same problem then you'll need to find all the other places that `sigaction` might be called from UE on Android and do the same. Unfortunately I am not familiar with UE so I don't know where that could be

Hi,

I have disabled all sigaction function in our ue project but it is still crash

There are two key points:
1. I only disable sigaction  in source code , but i don't know whether there are external plugin(xxx.so) call sigaction. Do you know that how to check  sigaction  function during app running
2. When app crash，I don't know the crash reason beacuse of no crash stack(for disable sigaction). How to  find the crash root case

**Comment by panos-lunarg** [comment]
Right. In that case I'm afraid you'll need to attach a debugger. Either visual studio or android studio

**Comment by chenyangchenyang** [comment]
> Right. In that case I'm afraid you'll need to attach a debugger. Either visual studio or android studio

It is crash(after app running some seconds) once attach a debugger(VSCode)

memcpy is crashed(uniform buffer update)

//UE 4.27.2,VulkanMemory.cpp
void FMemoryManager::AllocUniformBuffer(FVulkanAllocation& OutAllocation, uint32 Size, const void* Contents)
{
//xxx
FMemory::Memcpy(OutAllocation.GetMappedPointer(Device), Contents, Size); **//crash**
//xxx
}

![image](https://user-images.githubusercontent.com/28689129/222310867-9fb23087-c206-48e3-b935-7d82beb403f4.png)

**Comment by panos-lunarg** [comment]
Nice. The destination address of that `memcpy` is write protected by the `page_guard` mechanism, the `sigsegv` handler registered by GFXR should have handled that seg fault but the handler has been replaced by someone else hence the app crashes without a proper backtrace being printed.

If you could place a breakpoint at `sigaction` then from the backtrace you can pin point who replaced the `SIGSEGV` handler.

**Comment by panos-lunarg** [comment]
> I try to hook sigaction function(using xhook,https://github.com/iqiyi/xHook)

Interesting project. I was aware of it. Thanks!

> When i try to replace(hook) sigaction of all xxx.so's with empty function, I found scene is error(no visible 3d mesh)

You need to remove all calls to `sigaction` that are about `SIGSEGV` **except** the one that comes from GFXR itself.
Perhaps if you add some hidden "handshake" so your empty sigaction  function can recognize the specific call and pass it to the **real** `sigaction`. GFXR's call to `sigaction` is [here](https://github.com/LunarG/gfxreconstruct/blob/dev/framework/util/page_guard_manager.cpp#L480)

**Comment by chenyangchenyang** [comment]
> > I try to hook sigaction function(using xhook,https://github.com/iqiyi/xHook)
> 
> Interesting project. I was aware of it. Thanks!
> 
> > When i try to replace(hook) sigaction of all xxx.so's with empty function, I found scene is error(no visible 3d mesh)
> 
> You need to remove all calls to `sigaction` that are about `SIGSEGV` **except** the one that comes from GFXR itself. Perhaps if you add some hidden "handshake" so your empty sigaction function can recognize the specific call and pass it to the **real** `sigaction`. GFXR's call to `sigaction` is [here](https://github.com/LunarG/gfxreconstruct/blob/dev/framework/util/page_guard_manager.cpp#L480)

Oh，visible 3d mesh can be render normally. when  I need to remove all calls to sigaction  except the one that comes from GFXR itself
But It is still crash when enter other scene

I don't know the root case because of not call stack. When I try to attch to vscode debugger, app is crash immediately(I guess that debugger tool contains a lot of sigaction, which is incompatible with GFXR)

Do you know  that how to resolve/inside the problem

**Comment by panos-lunarg** [comment]
> I don't know the root case because of not call stack. When I try to attch to vscode debugger, app is crash immediately(I guess that debugger tool contains a lot of sigaction, which is incompatible with GFXR)

Ah right, you'll need to tell to the debugger to ignore segmentation faults. On desktop i use this parameter in the vscode's `launch.json`. Hope this works for android too

```
"setupCommands": [
                {
                   "description": "Ignore SIGSEGV",
                   "text": "handle SIGSEGV nostop noprint pass",
                   "ignoreFailures": true
                },
                {
                   "text": "handle SIGSEGV nostop noprint pass"
                }
            ],
```
(for example something like this: https://pastebin.com/raw/Tv92iPWu)

**Comment by chenyangchenyang** [comment]
> > I don't know the root case because of not call stack. When I try to attch to vscode debugger, app is crash immediately(I guess that debugger tool contains a lot of sigaction, which is incompatible with GFXR)
> 
> Ah right, you'll need to tell to the debugger to ignore segmentation faults. On desktop i use this parameter in the vscode's `launch.json`. Hope this works for android too
> 
> ```
> "setupCommands": [
>                 {
>                    "description": "Ignore SIGSEGV",
>                    "text": "handle SIGSEGV nostop noprint pass",
>                    "ignoreFailures": true
>                 },
>                 {
>                    "text": "handle SIGSEGV nostop noprint pass"
>                 }
>             ],
> ```
> 
> (for example something like this: https://pastebin.com/raw/Tv92iPWu)

![image](https://user-images.githubusercontent.com/28689129/222646572-01379f6c-f8ff-425c-b0a9-7e206680c939.png)
As config, It is still crash immediately  when vscode debugger is attached
crash call stack the same as memtioned above
![image](https://user-images.githubusercontent.com/28689129/222646095-06027f3c-6d52-447b-9603-824f9ad97a74.png)

**Comment by panos-lunarg** [comment]
A brief explanation of what's going on just for the sake of clarity and make sure we are on the same page:

> `page_guard` is a mechanism that tracks user accesses to VkDeviceMemory mapped to user space.
> GFXR in order to be able to capture updates made to device memory from the user (i.e. uniform buffers) "guards" the mapped region by removing write rights from that memory.
> 
> When the user tries to write to that memory it causes a segfault. GFXR's segfault handler then runs and handles that: that is it takes note that the specific region was written by the user and removes the protection so that execution can proceed.
> 
> So when you attach a debugger while capturing, the debugger notices those segfaults and breaks at them, while in reality they are harmless.

So, if I understand correctly, what you see when you attach the debugger are these segfault which are going to be handled by GFXR's segfault handler. You'll need to find a away to tell the debugger to ignore segfaults in order to go further.

>I don't know the root case because of not call stack. When I try to attch to vscode debugger, app is crash immediately(I guess that debugger tool contains a lot of sigaction, which is incompatible with GFXR)

Right, I see in xHook's readme that that tool also tampers with segfault handler. I guess this perplexes the issue more.
I'm not sure how to work around this.

**Comment by chenyangchenyang** [comment]
> When the user tries to write to that memory it causes a segfault. GFXR's segfault handler then runs and handles that: that is it takes note that the specific region was written by the user and removes the protection so that execution can proceed.

Interesting  idea. where is the source code mentioned above

> Right, I see in xHook's readme that that tool also tampers with segfault handler. I guess this perplexes the issue more.
I'm not sure how to work around this.

Yes,  key function **xhook_enable_sigsegv_protection**，I will inside xhook

**Comment by panos-lunarg** [comment]
> Interesting idea. where is the source code mentioned above

This is implemented in the [page_guard_manager.cpp](https://github.com/LunarG/gfxreconstruct/blob/dev/framework/util/page_guard_manager.cpp)

**Comment by chenyangchenyang** [comment]
The problem of sigaction(external xxx.so) has been resolved by hook.
Replay has been succeed for our ue project.
This issue will be closed
Thanks @panos-lunarg

**Comment by panos-lunarg** [comment]
Awesome! Can you please elaborate a bit on how you did it?

**Comment by chenyangchenyang** [comment]
> Awesome! Can you please elaborate a bit on how you did it?

hi it is hack

After ue engine has initialized，Hook sigaction function of all external(xxx.so) except GFXR's (using xhook,https://github.com/iqiyi/xHook) with empty function can resolve current issue(of course,  it is hack, it is not successful for all ue project)

**Comment by panos-lunarg** [comment]
Interesting.
Thank you for working this out with me and for your feedback. Glad you found a workaround for your case.
This is a recurring problem we face and not just with UE titles.
