### ISSUE TITLE
[replay] SYNC-HAZARD-WRITE-AFTER-READ during any vulkan replay.

### ISSUE THREAD

**Issue by mokafolio** [LunarG/gfxreconstruct#991]
**Describe the replay bug:**
Replay works fine but every replayed capture emits the same `SYNC-HAZARD-WRITE-AFTER-READ` if synchronization validation is enabled during replay. This error happens with every replay I tested and does not happen if I validate the applications in question directly.

**Verify before submission:**
* Was trimming enabled? No
* Was replayer renamed if necessary? No
* Was --sync used if title is known to need forced synchronization? Does not make a different

**Build Environment:**
I am on Ubuntu 22.04 using the official version that comes with the Vulkan SDK (version 1.3.239).

**To Reproduce**
1. Run `gfxrecon-capture-vulkan.py -o vkcube.gfxr vkcubev`
2. Run `gfxrecon-replay vkcube_***.gfxr`

**System environment:**
 - Ubuntu 22.04, Nvidia 3070TI (Laptop), Driver Version: 525.78.01

**Comment by bradgrantham-lunarg** [comment]
Raised back to P1 because we may be doing something wrong in Virtual Swapchain

**Comment by bradgrantham-lunarg** [comment]
Hi!  Do you build from the source or do you use the SDK or the OS packages?  If you build from source, could you try `dev` branch as of today (119cef2) and see if replaying your vkcube capture causes any validation errors?

**Comment by mokafolio** [comment]
I am using the SDK. I will give it a shot to build from source for comparison tomorrow and report back!

**Comment by mokafolio** [comment]
from build folder I am running it like this `./tools/replay/gfxrecon-replay vkcube_20230227T142238.gfxr`. Version output is:
```gfxrecon-replay version info:
  GFXReconstruct Version 0.9.19-dev (dev:274a40f)
  Vulkan Header Version 1.3.241```. 
  
For what it's worth, specifically with nvidia drivers, the validation layers give me different results on linux and windows, especially related to synchronization. Makes me wonder if there is something fishy going on either in the validation and/or drivers. Admittedly, they are usually correct (way) more often than not.

**Comment by mokafolio** [comment]
To clarify, `QueueSubmit` validation needs to be enabled for the error to be triggered on recent `dev` build. Regular synchronization validation passes. (Not sure if this was the same case when I opened the issue).

**Comment by locke-lunarg** [comment]
It got this log

SYNC-HAZARD-WRITE-AFTER-READ(ERROR / SPEC): msgNum: 929810911 - Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle = 0x1ffcd608c30, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x376bc9df | vkQueueSubmit: Hazard WRITE_AFTER_READ for entry 0, VkCommandBuffer 0x1ffd605c780[], Recorded access info (recorded_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier, seq_no: 1, reset_no: 4). Access info (prior_usage: SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_ACQUIRE_READ_SYNCVAL, read_barriers: VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT|VK_PIPELINE_STAGE_2_COPY_BIT|VK_PIPELINE_STAGE_2_RESOLVE_BIT|VK_PIPELINE_STAGE_2_BLIT_BIT|VK_PIPELINE_STAGE_2_CLEAR_BIT, , batch_tag: 7, vkAcquireNextImageKHR aquire_tag:7: VkSwapchainKHR 0xead9370000000008[], image_index: 0image: VkImage 0xcad092000000000d[]).

**Comment by locke-lunarg** [comment]
@mokafolio Could you test this PR? Thank you.
https://github.com/LunarG/gfxreconstruct/pull/1029

**Comment by mokafolio** [comment]
So there seems to be an improvement. I still get the following:

```
    Objects: 1
        [0] 0x55c3719e63b0, type: 4, name: NULL
SYNC-HAZARD-READ-AFTER-WRITE(ERROR / SPEC): msgNum: -455515022 - Validation Error: [ SYNC-HAZARD-READ-AFTER-WRITE ] Object 0: handle = 0x55c372ac11a0, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xe4d96472 | vkCmdBlitImage: Hazard READ_AFTER_WRITE for srcImage VkImage 0x55c372ac11a0[], region 0. Access info (usage: SYNC_BLIT_TRANSFER_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_COPY_TRANSFER_WRITE|SYNC_RESOLVE_TRANSFER_WRITE|SYNC_BLIT_TRANSFER_WRITE|SYNC_CLEAR_TRANSFER_WRITE, command: vkCmdPipelineBarrier, seq_no: 1, reset_no: 10).
    Objects: 1
        [0] 0x55c372ac11a0, type: 10, name: NULL
SYNC-HAZARD-WRITE-AFTER-READ(ERROR / SPEC): msgNum: 929810911 - Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle = 0x55c3719e63b0, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x376bc9df | vkQueueSubmit: Hazard WRITE_AFTER_READ for entry 0, VkCommandBuffer 0x55c372aa2ac0[], Recorded access info (recorded_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier, seq_no: 1, reset_no: 10). Access info (prior_usage: SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_ACQUIRE_READ_SYNCVAL, read_barriers: VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT|VK_PIPELINE_STAGE_2_COPY_BIT|VK_PIPELINE_STAGE_2_RESOLVE_BIT|VK_PIPELINE_STAGE_2_BLIT_BIT|VK_PIPELINE_STAGE_2_CLEAR_BIT, , batch_tag: 115, vkAcquireNextImageKHR aquire_tag:115: VkSwapchainKHR 0x55c3729925f0[], image_index: 0image: VkImage 0x55c372a9e490[]).
```

But in only appears to happen a handful of times at the beginning of the program and not spam every frame.

**Comment by bradgrantham-lunarg** [comment]
@mokafolio Could you please upload your layer settings file that you are using?  I think you can open it by right-clicking in the layer settings panel in VKConfig.

**Comment by mokafolio** [comment]
[Synchronization.zip](https://github.com/LunarG/gfxreconstruct/files/10971214/Synchronization.zip)

**Comment by locke-lunarg** [comment]
@mokafolio  Thank you. Could you also update your .gfxr file?

**Comment by mokafolio** [comment]
Sure, here you go. It's also been recorded with the recent fork you posted.
[vkcube_20230314T093205.zip](https://github.com/LunarG/gfxreconstruct/files/10972187/vkcube_20230314T093205.zip)

**Comment by locke-lunarg** [comment]
The layer setting is default and plus enabling VALIDATION_CHECK_ENABLE_SYNCHRONIZATION_VALIDATION_QUEUE_SUBMIT. The captured file is Linux + RTX 3070 Ti. I replayed it on my Ubuntu + RTX 2060 without issues. Could I ask you what Vulkan SDK version did you use?

**Comment by mokafolio** [comment]
`1.3.239`

**Comment by mokafolio** [comment]
I have to apologize: It realized this morning that I forgot to checkout to to correct branch after cloning your fork. I just tested it again and can confirm that it appears to be fixed. Thank you!
