### ISSUE TITLE
Remove competing surface extensions with --wsi option

### ISSUE THREAD

**Issue by bartosz-muszarski-arm** [LunarG/gfxreconstruct#998]
Currently --wsi option forces the specified wsi surface, which is helpful for playback on different platforms.
With this option enabled, related surface extension is included in enabled extensions list in VkInstanceCreateInfo, right next to other surface extensions used originally. However, if the surface extension used originally in the trace is not supported on the device, it will still trigger vkCreateInstance VK_ERROR_EXTENSION_NOT_PRESENT error.
To workaround this issue we could use --remove-unsupported option. Still, that's not an ideal solution as it would remove all other unsupported extensions as well. 
Using --wsi option to force a specific surface type should also remove other surface extensions already enabled in vkCreateInstance calls, making it easier to replay on different platforms. This should not impact any other unsupported extensions.
We're planning to implement that feature, any suggestions or ideas?

**Comment by bradgrantham-lunarg** [comment]
Thanks!

So you want to specify` --wsi` but want failure only for non-WSI extensions that are missing, e.g. in automation if `ray_query` was captured but can't be replayed?  I don't think that's a high priority for us but we'd review a PR to hopefully merge!

**Comment by bradgrantham-lunarg** [comment]
Probably can roll this into any effort we make to remove problematic extensions on Android replay like `VK_EXT_tooling_info`. @MarkY-LunarG

**Comment by MarkY-LunarG** [comment]
I was thinking we want an option as well.  I don't want to just blindly do this.

**Comment by per-mathisen-arm** [comment]
Why wouldn't you want to always do this? If you don't, --wsi will be broken unless your selected wsi is the same as the traced wsi, which makes the option of somewhat questionable utility...

**Comment by bradgrantham-lunarg** [comment]
We don't ever guarantee replaying on another WSI will work, so generally we have also provided `--remove-unsupported` anyway.

**Comment by per-mathisen-arm** [comment]
I am just very confused as to what could possibly be the use case where you want to use --wsi and have your replay immediately fail.

**Comment by bradgrantham-lunarg** [comment]
> I am just very confused as to what could possibly be the use case where you want to use --wsi and have your replay immediately fail.

I'm not saying it's not a good idea.

The usual case we've seen people asking for is replaying Android on Windows or Linux, and that is often going to fail anyway because of Android extensions that don't exist on Linux, so you have to provide `--remove-unsupported` anyway.

**Comment by per-mathisen-arm** [comment]
FWIW, we do this kind of cross-platform replay between Linux and Android all the time, although until now with our vktrace fork, not with gfxreconstruct. We're willing to put in the work to make it work for gfxreconstruct as well.
